# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#### Everything for Computing
#catagory = FactoryGirl.create(:catagory, name:"computing", navgraphic: "navgraphics/computing.png", headergraphic: "computing", color: "computing", video: "EPDesign.m4v")
catagory = Catagory.create(name:"Computing", navgraphic: "navgraphics/computing.png", headergraphic: "computing", color: "computing", keypoints: "this is a key point", video:"//www.youtube.com/embed/lZxJgTiKDis")
#catagory = Catagory.create(name:"Computing", navgraphic: "navgraphics/computing.png", headergraphic: "computing", color: 
#"computing", keypoints: "this is a key point", game_name:"comp_game.js")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "first", main_idea:"Computing refers to any device or machine whose behavior is controlled by logical instructions", header:"<span class='accent1'>Computing</span> refers to any device or machine whose behavior is controlled by <span class='accent1'>logical instructions</span>", section_image: "section_images/programmable_devices.png", image_position: "imagerightlarge",content: "Computing is just a general word to describe machines that use logic to control what they do. Computing includes things we normally think of as computers – like laptops – as well as things we don’t normally think of as computers, but that also have logic that helps them work, such as modern televisions, DVD players, rockets, or even some parts of cars. An example of a computerized part of a car is something called an “Electronic Fuel Injection system”. Those are big fancy words that just mean that a computer system on the car reads data from sensors and uses that data to adjust the amount of fuel to be burned. So, many things beyond what we normally call computers really do have computers - or computing - in them, don’t they? So, what's a computer, then?")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "third", main_idea:"A computer is an electrically-powered machine that can perform math and logical actions", header:"A computer is an <span class='accent1'>electrically-powered machine</span> that can perform math and <span class='accent1'>logical actions</span>", section_image: "section_images/computing-ex.png", image_position: "imagerightmedium", content: "Let’s break that down. First, it is an “electricity-powered machine”. What things can be described by those words? It includes battery-powered devices, like an iPhone or Nintendo DS, because the batteries will generate an electric current once the device is on. So far, a toaster would qualify, too, wouldn’t it? Let’s take the second part, “that can perform math and logical actions”. That means that the machine is capable of taking some actions based on some logic. Logic in the world of computing often looks something like, 'if A and B are true, then do C,' or 'do D until E is true.' <br><br>Most toasters aren’t that thoughtful – you put the bread in, move a lever to show how toasted you want it, and then push the slider down to toast. It uses the electric power to heat the inside to toast your bread, but it is really just a simple little electric appliance with some mechanical pieces.<br><br>What if you had a smart toaster that stored toasting preferences for each family member, such as how much toasting is desired, and maybe who likes butter, and also allowed each family member to press a button to toast to their preferences and add butter if needed? Then, your little toaster would have some type of computing logic in it! Cool, right? What other &quot;smart&quot; household tools can you imagine? I know some young people that would love a smart bedroom door: 'If mom or dad or me, open door, otherwise stay locked. If little sister, echo &quot;Go Away!&quot; and hurl spitballs.'<br><br>
Back to the iPhone and Nintendo DS. An iPhone has all kinds of logical programming in it, from how the phone itself should work to all the programs, or &quot;Apps&quot; that are loaded on the phone. It’s a computer. That’s why it’s called a 'smart' phone. A gaming console? Also a computer. It has logic for how it runs itself, and how to run games that get connected in some way, and those games are all computer programs.<br><br>
Examples of computers include desktop computers (often called &quot;PCs&quot;), laptop computers, tablet computers, smartphones, and more. But lots of devices these days include some computing: cars, DVD or Blueray players, DVRs, programmable sprinkler systems, and lots more. Every day our world gets more computerized!")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fourth", main_idea:"Computing includes both hardware and software", header:"Computing includes both <span class='accent1'>hardware</span> and <span class='accent1'>software</span>", section_image: "section_images/smart_phone_with_apps_coming_out.jpg", image_position: "imageleftmedium", content: "<i>Hardware</i> is just a word that refers to the physical parts of a computer. For a smart phone, it would be the physical phone and all the parts in it. <i>Software</i> means all the programming for the computer. For a smartphone, that includes all the software that is built in to the phone (which is called &quot;iOS&quot; for Apple phones), as well as all the add-on programs (called &quot;Apps&quot; in the smart phone world).<br><br> Let's make that really concrete with an example. Say you wanted to create a computerized machine to make sandwiches at your house. You would need some hardware - say, a plate-like thing to hold the bread, a knife-like thing to spread things on bread, and a moving arm to move the knife to spread things on bread. Those are physical pieces of the machine, or hardware. Then, you need some programming - the software. For example, <i>For Billy, spread peanut butter on slice one until bread covered; spread strawberry jam on slice two until covered. For Sally, spread peanut butter on slice one until bread covered; spread grape jelly on slice two until covered. For Dad, spread mayo and add cheese.</i> That's not a particularly well-written program, but you get the idea. Software is computerized logic, or computer programs.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fifth", main_idea:"Computer programs are logical descriptions of things that should be done under certain conditions", header:"Computer programs are <span class='accent1'>logical descriptions</span> of things that should be done under certain <span class='accent1'>conditions</span>", section_image: "section_images/mission_control_and_mars_rover.png", image_position: "imagerightlarge", image_caption: "Top: The NASA Mars Science Laboratory named Curiosity is controlled remotely at the Jet Propulsion Laboratory in La Canada, Calif. Christopher Halloran / Shutterstock.com, Bottom: Curiosity self-portrait at 'Windjana' drilling site on Mars. NASA/JPL-Caltech/MSSS", content: "Software is a category of computer things that refers to the computer logic in a program. A specific piece of software, like Angry Birds, is a computer program. A computer program is sometimes called an &quot;Application&quot;, or for mobile devices like iPads and smart phones, often just called an &quot;App&quot;. Regardless of what you call it, a program is a set of logical instructions that were put together for a particular use. Some are very small programs, some are huge.<br><br>Any work you can describe in some way, you can program, as long as the physical (hardware) functions you need  are supported by the device. For example, you could program a rocket to go to the moon by itself, if it had the physical functions built in to it that rockets need. The physical portions of the device are the machine's hardware. The programming that describes how to start up the rocket, lift off, navigate to the moon, and land comprise the &quot;computing&quot; portion of the device. The computing portion of the machine has to take in all the inputs (like ground temperature, wind direction and speed), make the non-computer portion work happen (fire up the engines), and provide output as to how the work is proceeding (like altitude data or engine temperature provided to Mission Control). <br><br>These days, computer programs look a lot like normal, everyday English, although each computer language has some special ways to express things, called a syntax. Computer programs used to be written in very low-level ways that looked more like what machines can read. A woman named Grace Hopper invented the way to write programs that is like how we write normally, when she invented the first high-level programming language. We'll do a special profile on her soon. These days, since programming languages look so much like everyday language we all use, if you can come up with instructions for it, you can program it! That doesn't mean programming is always easy, though.")

question = Question.create(catagory_id: catagory.id, question_num: "1", question_content: "What is computing?", question_image: "section_images/programmable_devices.png",explanation: "Computing refers to a device or machine whose behavior is controlled by logical instructions. Laptop computers are computing devices - so are smartphones, gaming consoles, and modern televisions.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "The work done by a computer")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Any work done by a device or machine whose behavior is controlled by logical instructions", correct: "true")
question = Question.create(catagory_id: catagory.id, question_num: "2", question_content: "In the picture at the right, the computing part of this phone includes:", question_image: "section_images/smart_phone_with_apps_coming_out.jpg", explanation: "Computing includes both hardware and software. Hardware is just a word that refers to the physical parts of a computer. For a smart phone, it would be the physical phone and all the parts in it. Software means all the programming for the computer. For a smartphone, that includes all the software that is built in to the phone (which is called iOS for Apple phones), as well as all the add-on programs (called Apps in the smart phone world).")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Just the apps on the phone")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "The apps on the phone and the software that runs the phone ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "The phone itself, the software that runs the phone, and all the apps that have been installed on the phone", correct: "true")
question = Question.create(catagory_id: catagory.id, question_num: "3", question_content: "In the picture at the right, which devices have computing - or programming - in them?", question_image: "section_images/programmable_devices.png",explanation: "Computers are computing devices. But, so is a programmable thermostat. People may set their home temperature control to only run the heat or air conditioning when they are are home, or to turn down the temperature overnight. And, a DVD player reads digital, or computerized, data on the DVD to play movies or music. In fact, DVD stands for Digital Video Disc. Whenever you see the word digital, you know that it is related to something that is computerized.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Only the laptop computer is a computing device")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Just the laptop computer and the programmable thermostat are computing devices")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "The laptop, the programmable thermostat, and the DVD player are all computing devices", correct: "true")

## Everything for Computing: Programming Languages
topic = FactoryGirl.create(:topic, name:"programming languages",  navgraphic: "navgraphics/proglanguages.png", catagory_id: catagory.id, keypoints: "" )
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"A programming language is a set of instructions that can be used to write computer programs", header:"A programming language is a set of <span class='accent1'>instructions</span> that can be used to write computer programs", content: "A programming language is a set of instructions that can be used to write computer programs (or 'Apps'). There are many computer programming languages, and they are used for different things. <br><br>Some languages are used to create web-based programs. Some are used to create programs on mobile devices, like iPhones and tablets. Some languages are used to create programs for big computer systems. <br><br>Each programming language has its own set of instructions. And, each language has its own ways to put the instructions together, which we call a “syntax.” Although each programming language is different, there are often similarities between them. So, when you learn a new programming language, you can use what you already know to learn the language more quickly.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"There are visual tools that introduce kids to programming concepts", header:"There are <span class='accent1'>visual</span> tools that <span class='accent1'>introduce</span> kids to programming concepts", content: "Kids are often introduced to programming ideas through visual tools. You may have seen some of these tools before, like Scratch, or Tynker, or Lego Robotics. <br><br>These are visual programming tools designed for kids. They have programming-like environments, and let you pick instructions you want to use for your program from a visual list. Visual tools are good ways for kids to learn about programming ideas and concepts without having to learn about how to write a program from scratch. Some of these important concepts are things like looping (do something 10 times) or IF statements (do something IF something else is true).")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", section_image: "section_images/helloworld-proglang.png", image_position: "imagerightlarge", main_idea:"There are also books and web sites that can teach you how to create real web sites and apps", header:"There are also <span class='accent1'>books</span> and <span class='accent1'>web sites</span> that can teach you how to create <span class='accent1'>real</span> web sites and apps", content: "The visual tools for kids are good places to start learning about programming concepts. But, they are not exactly like programming. Most programs and applications require the creators to know about the instructions and syntax for the tools they are using.  It’s not impossible to write a program from scratch, even for a kid. (Or, even, a grown-up who has never tried programming before. Sometimes grown-ups are afraid to try programming, because they worry that they don’t know how to do it. When you learn, maybe you can teach some adults you know!) <br><br>  There are good books and web sites that can help you learn to program using the languages that are used to create real programs, web sites, and “Apps”. Each programming language has a “syntax”, which means that there are particular ways to write the code. <br><br> Above are some examples in different programming languages for how to have a program display the text, “Hello, World!” to the screen. A Hello World program is often the first program written when learning a new programming language. It’s a simple way for you to get used to writing a program for that language. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"People decide which language to use based on what they know and where the program will be run", header:"People decide which language to use based on what they <span class='accent1'>know</span> and where the program will be <span class='accent1'>run</span>", section_image: "section_images/ProgLanguageExamples.png", image_position: "imagerightlarge",content: "When someone decides to write a program, often the first decision is what programming language to use. This choice isn't always easy, as there are many different languages to choose from. You might pick a language you already know and are comfortable with. <br><br>Another factor in choosing a language is where the program, or App, will be run. For example, you might be creating a web application, or an app for a mobile phone (like an iPhone). If you are creating an App for an iPhone, you usually use Apple's tools to create it. But, for non-Apple phones, you might be using Google's tools to create the apps. If you are creating a web application, there are a number of different languages you could use, and you might use more than one to create your complete application. There are a variety of different ways to create web applications, and different tools that can help you.")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What is a programming language?", question_image: "section_images/computing-ex.png",explanation: "Each programming language has its own way of specifying instructions for the computer, called a syntax. However, computer languages have many similarities, and languages were often heavily influenced by other languages.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "A specific way to specify instructions for what the program should do", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A language spoken in on a remote tropical island")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "Which of the following can help you learn about programming?", question_image: "section_images/computing-ex.png",explanation: "There are many ways to learn about programming. You can start with free online tools like Scratch. There are great books like Python for Kids. There are lots of online resources and multiple books, too, to help kids learn about programming.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Use a visual, online tool, such as Scratch (scratch.mit.edu) or Code.org (studio.code.org) to start programming using drag-and-drop tools")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Grab a book, such as Python for Kids or Javascript for Kids and follow along to create real programs")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Follow on online tutorial, like the Ruby on Rails tutorial at www.railstutorial.org")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of these are great ways to learn about programming", correct: "true")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "How does a programmer decide which language to use for a particular program or 'App'?", question_image: "section_images/computing-ex.png",explanation: "Some programming languages and tools are used for web sites. Some are really good for big software programs. Some are used for specific devices, like Apple computers and phones, or Android phones. The choice of language depends on where the program will run, and maybe also what languages the programmer knows best.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "She can just pick her favorite language")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "There is only ever one really popular language that everyone uses")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "The programming language needs to be able to write programs for where it will be run, such as on a web site or iPhone. But the programmer can choose among multiple languages that support that environment, based on their preferences, among other things", correct: "true")

#topic = FactoryGirl.create(:topic, name:"how computers work",  navgraphic: "navgraphics/computershowwork.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"anatomy of a computer",  navgraphic: "navgraphics/computershowwork.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Desktops, Laptops, Tablets, and Smartphones are all computers ", header:"Desktops, Laptops, Tablets, and Smartphones are all <span class='accent1'>computers</span>", section_image: "section_images/computertypes.png", image_position: "imagerightsmall", content: "Whether or not you notice it, computers are everywhere you look. Chances are you use them every day. When someone says the word “computer”, you might imagine something like the picture on the right. This is called a Desktop Computer. We will start by looking at this example of a computer. Then we will look at laptops, tablets, and smartphones to see how they are similar or different. First, we are going to look at how a desktop computer is similar to the human body.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"You have a skeleton; a computer has a chassis.", header:"You have a <span class='accent1'>skeleton</span>; a computer has a <span class='accent1'>chassis</span>",  section_image: "section_images/chassis_89852872.jpg", image_position: "imageleftsmall", content: "A computer has different parts just as you have different body parts. You have a skeleton that protects all your important body parts from damage. A computer has a skeleton, or chassis, which is the housing for all of the components. It can be made of either plastic or metal, or sometimes both.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"The brain of a computer is called a CPU", header:"The <span class='accent1'>brain</span> of a computer is called a <span class='accent1'>CPU</span>", section_image: "section_images/cpu_264334046.jpg", image_position: "imagerightsmall", content:"A desktop computer also has a “brain” that does all of the thinking the way you have a brain. This “brain” is called the microprocessor. It is also known as the CPU, or the Central Processing Unit. The CPU has the instructions for running the computer. It reads the memory and translates what the memory has to say into instructions that the rest of the computer can understand. Just like the brain, this job is necessary for the computer to do anything.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"You have memory - so does a computer", header:"You have <span class='accent1'>memory</span> - so does a <span class='accent1'>computer</span>", content: "Your brain can store memories. That's why you can remember how to tie your shoes, and that your mom asked you to take out the trash. A computer can store information, too. Computers actually have a few different ways to store information. Information that needs to be kept when a computer is shut down is kept in some type of non-volatile storage. Non-volatile in this case just means that the information is kept when the power is off. There is also working memory whose contents do not need to be kept when the computer is turned off. Non-volatile storage includes something called Read Only Memory, or <i>ROM</i>, which generally has a small amount of key information for the computer. Non-volatile storage also includes the computer's hard drive. Working memory is often called Random Access Memory, or <i>RAM</i>.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"You have a hearbeat; a computer has a clock", header:"You have a <span class='accent1'>hearbeat</span>; a computer has a <span class='accent1'>clock</span>", section_image: "section_images/hbclock_28108849.jpg", image_position: "imageleftsmall", content: "What does your heart do? It beats and keeps everything in your body running. This is exactly what the clock in a Desktop Computer does! The clock keeps time and ensures that all the different “body parts” of the computer’s “body” run in sync with each other. But if your heart stops beating, what happens to you? Your body dies! The same thing happens to a computer’s system if the clock stops or breaks. The clock is essential to any and every computer.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"You have a voice and gestures for output; a computer has speakers and a display", header:"You have a voice and gestures for  <span class='accent1'>output</span>; a computer has speakers and a display", section_image: "section_images/speakervoice.png", image_position: "imagerightsmall", content: "If you want to tell someone something, you have a voice box. Your voice  allows you to speak and communicate to other people. Computers have speakers inside that can beep or make noises when things happen. For example, you might hear a chime when you get new email messages. Or, the computer might beep at you if you try to do something you are not allowed to. Sounds from the speaker are one way that the computer can generate <i>output</i>. Output means something that the computer does to put information out.<br><br>The computer screen itself is another type of output. The screen shows you want you are doing. It might also give you messages, such as suggesting spelling changes, or telling you that something has happened. You might think of this type of non-audio output as being similar to your gestures. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"You have five senses; a computer takes input from a keyboard, mouse, maybe even a touch screen", header:"You have five senses; a computer takes <span class='accent1'>input</span> from a keyboard, mouse, maybe even a touch screen", section_image: "section_images/inputs.png", image_position: "imageleftsmall", content: "Your body gets input from the world around you. For example, you can read instructions on your homework. You can hear adults in your life asking you to do something. You can smell when lunch is close being served. Sight, hearing, touch, smell, and taste are your inputs. <br><br>Computers take their outside input from things like a keyboard, a mouse, voice commands, or a touch screen. Those are a computer's sensory inputs. In the computing world, information that comes into a computer or program are called <i>inputs</i>.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "seventh", main_idea:"A computer has a communication channel to carry signals, like your nervous system", header:" A computer has a communication channel to carry signals, like your nervous system", content: "Have you ever heard of your nervous system? Your nervous system is a communication network for the human body that carries information from our brain to parts of our body. The computer has lots of copper traces that go throughout the entirety of the printed circuit boards, and they act like a nervous system. They carry electrical signals that help the different parts of the computer understand and communicate with and to each other. The communication system that carries information between parts of a computer is called the <i>bus</i>.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "eighth", main_idea:"A computer needs an energy source, just like you do", header:"A computer needs an <span class='accent1'>energy source</span>, just like you do", content: "Every electronic device needs a power source, whether it is a battery, a solar panel, or for a desktop computer, a thing called a <i>power supply</i>. You plug the cord into a wall outlet. This cord plugs into the power supply. The power supply carries the power from the wall into the computer.  The power supply changes the power to something it can use. It also divides up the power so that each piece of the computer gets the amount of power it needs. If you open up the computer, you will see dozens of wires sticking out of the power supply, to carry power to all the parts where it is needed.")
#section = FactoryGirl.create(:section, topic_id: topic.id, linking: "eighth", main_idea:"The motherboard connects components so that they work together", header:"The <span class='accent1'>motherboard</span> connects components so that they work together", content: "Almost all of these parts are connected to something that is known as the motherboard. The motherboard is a part of the computer that allows everything to talk and communicate with each other, as well as tell everything in the computer what to do. Cool, huh? It’s kinda what your Mom (or Dad) does! In fact, it’s so much like what a stereotypical mom does that they called it a </i>mother</i>board because it is the “head of the house”, and is in charge of running the “household”, so to speak.")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What is the brain of a computer called?", question_image: "section_images/cpu_264334046.jpg",explanation: "A computer has a brain that does the thinking and logic. This brain is the CPU, or the Central Processing Unit. The CPU has the instructions for running the computer. It reads from memory and translates what it reads into instructions that the rest of the computer can understand. Just like a human brain, this CPU's work is necessary for the computer to do anything. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Mr. Roboto",)
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A CPU", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "A thinker")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "What is the skeleton, or frame, of a computer called?", question_image: "section_images/chassis_89852872.jpg",explanation: "Just like you have a skeleton that protects all your important body parts from damage, a computer has a skeleton, called a chassis. The chassis is the frame and housing for all of the components. It can be made of plastic or metal, or sometimes both. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "The skeleton thing-y")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "The computer box")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "The chassis", correct: "true")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "You have five senses - you can see, touch, hear, smell, and taste - that help you take information, or input, from the world around you. What is an input that computers can use?", question_image: "section_images/inputs.png",explanation: "Computers take their outside input from things like a keyboard, a mouse, voice commands, or a touch screen. Those are a computer's sensory inputs. In the computing world, information that comes into a computer or program are called inputs. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "A touchscreen")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A keyboard")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "A computer mouse")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of the above might be inputs for a computer", correct: "true")

topic = FactoryGirl.create(:topic, name:"computer networking",  navgraphic: "navgraphics/computernetworking.png", catagory_id: catagory.id, available: "yes")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Computer networking is the set of technologies that lets you surf the Internet", header:"<span class='accent1'>Computer networking</span> is the set of technologies that lets you <span class='accent1'>surf</span> the Internet", section_image: "section_images/phonebrowsersurf.png", image_position: "imagerightsmall", content: "The Internet lets you surf the web, send an email, and talk to your grandmother on Skype or FaceTime. The Internet is a very large collection of computers and other connected devices all over the world. <br><br>
In 1969, there were only four devices on the Internet (then called the ARPANET). Now there are more than three billion Internet users around the world. <br><br>Many of the devices on the Internet are computers - but not all. Gaming systems, smartphones, home security systems, home temperature systems, and even some cars can also be Internet-connected devices.  ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"The Internet Backbone is a set of large networks that connect national and international networks together", header:"The <span class='accent1'>Internet Backbone</span> is a set of <span class='accent1'>large networks</span> that <span class='accent1'>connect</span> national and international networks together", section_image: "section_images/bbglobe_91895672.jpg", image_position: "imageleftsmall", content: "The Internet is made up of separate large networks that are connected together. This collection of large national or international networks is called the Internet Backbone. <br><br>Each large network on the Backbone is operated independently. There are network standards that define how they connect to each other and share information. These defined standards allow them to connect and work together across the world! <br><br>When you send an email from the US across the world, say to Japan, how does it get there? ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Internet Backbone networks are very high-speed networks", header:"Internet Backbone networks are very <span class='accent1'>high-speed networks</span>", section_image: "section_images/highspeednetwork.png", image_position: "imagerightsmall", content: "As the email travels around the globe, it crosses multiple networks on the Internet Backbone. These Backbone networks are very high-speed networks. In the US, companies such as AT&T, Level 3, or Sprint run these networks. Internationally, there are other providers for networks within the Backbone, like NTT in Japan, China Telecom in China, and more.<br><br>But your email doesn’t go right to the Internet Backbone and then to your friend in China. Your computer will be connected to the Internet Backbone through what is called an Internet Service Provider, or ISP. Although some ISPs also manage parts of the Backbone, not all do. There may be multiple steps between your computer and the Backbone. Each step in the journey is called a hop.<br><br>So your computer somewhere in the US will get to the Internet through an ISP. There may be multiple hops on the Backbone, and if you are sending your email to Japan, it will eventually cross over into NTT’s part of the Backbone. And then it will make its way to a local ISP, and finally to your friend.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"WiFi is a standard to connect devices wirelessly", header:"<span class='accent1'>WiFi</span> is a <span class='accent1'>standard</span> to connect devices <span class='accent1'>wirelessly</span>", section_image: "section_images/wifi.png", image_position: "imageleftsmall", content: "Before WiFi was in wide use, people used cables to connect their computers to their home routers, which were connected to their ISP. These days many devices are connected wirelessly to their home router. When you pick a WiFi network, you are picking a local wireless router that will allow you to connect and send and receive data wirelessly. WiFi is a network standard for connecting devices wirelessly to a local network. The standard defines how to connect, disconnect, and exchange data. Computers that network wirelessly have to follow the standard.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"Many network standards define how different parts of the Internet work together", header:"Many <span class='accent1'>network standards</span> define how different parts of the Internet <span class='accent1'>work</span> together", section_image: "section_images/protocols.png", image_position: "imagerightsmall", content: "Many standards define how different parts of the Internet work together. The standards cover how to send and receive email messages, how to upload files, how to specify what a web page looks like, how to define a location on the Internet, and many more things. These shared standards are the reason that all these different devices and networks all over the world can work together.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"Each hop on the network is connected through a device called a router", header:"Each <span class='accent1'>hop</span> on the network is connected through a device called a <span class='accent1'>router</span>", section_image: "section_images/networkdiagram.png", image_position: "imageleftsmall", content: "Each hop between you and your friend is connected through a device called a router. Routers can be small devices for local access to an ISP. They can also be complex devices for handling many, many transactions on the Internet Backbone – these are called Backbone Routers. For every type of network connection you can imagine, there is a router that implements that connection.<br><br>Routers figure out how to send information across the Internet from source to destination using addressing information from domain names (”foo.com”) or email address (”joe@gmail.com”). These logical addresses map to physical destinations, just like your street address maps to your house!")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "seventh", main_idea:"The web is the part of the internet that web browsers can access", header:"The <span class='accent1'>web</span> is the part of the <span class='accent1'>internet that <span class='accent1'>web browsers</span> can access", section_image: "section_images/websurf.png", image_position: "imagerightsmall", content: "Is the Web the same thing as the Internet? Sort of. The Web is the part of the Internet that has web pages that are written to a particular standard (HTML) and accessible by a different network standard (HTTP). HTML stands for Hypertext Markup Language and is the way you specify what a web page has on it. In addition, you can add styling and many web site features using other standards, like CSS, Javascript, PHP, and more.")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What is a router?", question_image: "section_images/router.png",explanation: "Routers are complex devices that connect devices and networks together. Some routers connect people's home computers to their local Internet Service Provider. Some routers, called Backbone Routers, connect very large, high-speed networks together.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "A device that figures out how to connect different parts of networks together and route network traffic", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A web page you visit on the internet to do your homework")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "A device for cleaning out plumbing if your toilet gets clogged")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "What is WiFi?", question_image: "section_images/wifi.png",explanation: "WiFi is a network standard that computers and other devices use to connect to a local network. When you connect to a WiFi network, you are connecting to that network's WiFi router, which will route your traffic for you. The WiFi network standard defines how devices connect, disconnect, and exchange data.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "A technology for playing music with good quality")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A standard for connecting a computer or other device to a network without having to use cables to connect", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "A married woman")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "Why are network standards important?", question_image: "section_images/protocols.png",explanation: "Many standards define how different parts of the internet work together. Network standards are the reason that different devices and networks all over the world can work together. There are network standards for many things, such as how to send and receive email messages, how to route messages, how to upload files, how to specify what a web page looks like, and more")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Without network standards, it would be hard to get different devices to work together.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Without standards, it would be hard to figure out how to send an email to each of your different friends.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Without network standards, we would not be able to walk into a coffee shop and connect our phones or laptops to the free WiFi")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of the above are true", correct: "true")

topic = FactoryGirl.create(:topic, name:"computer security",  navgraphic: "navgraphics/computersecurity.png", catagory_id: catagory.id, available: "yes")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Computer security is used to protect information from unauthorized access or change", header:"Computer security is used to protect information from <span class='accent1'>unauthorized access</span> or <span class='accent1'>change</span>", section_image: "section_images/confidentialityintegrityavailability.png", image_position: "imagerightlarge", content: "People want to keep their computers, phones, and tablets secure. That means that they do not want to have their sensitive information, like bank account data, stolen or changed without their permission. <br><br>People, governments, companies, and other organizations all want their computer systems to be secure. They also want to be able to access their computers and information whenever they need to. <br><br>Computer security is commonly referred to as having three key dimensions: Confidentiality, Integrity, and Availability. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Confidentiality means that information is secure and private from people who should not access it", header:"<span class='accent1'>Confidentiality</span> means that information is secure and <span class='accent1'>private</span> from people who should not access it", section_image: "section_images/lockedlaptop_100796185.jpg", image_position: "imageleftmedium", content: "Many things are done with computers now that used to be done on paper. This computerization means that there is now a vast amount of information held by computers. Much of this information should only be available to people who are allowed to have it. For example, computer systems used by doctors, hospitals, and insurance companies hold people's private information, like social security numbers and health histories. Banking systems store bank account numbers, account balances, social security numbers, and more. Corporations keep trade secrets on computer systems. And governments keep information about government employees and officials, military staff and systems, intelligence, strategies, and much more that they would not want in the hands of other countries. Private information can be stolen, sold, used for profit, or used to harm companies or countries. <br><br>For example, multiple companies have had their payment systems hacked into and credit card numbers stolen and sold to others. Hacking is when people write computer code to get into computer systems they are not supposed to access. The people who purchase these credit card numbers often create new fake credit cards from them, and then use the credit cards to purchase things that the credit card owner does not know they are paying for. Stealing credit card numbers is a type of &quot;cybercrime&quot;. A cybercrime is an crime that is accomplished through unauthorized access of a computer system. Confidentiality means that information can only be accessed by people who should be able to access it. Confidentiality is important not only for peoples' home computers, but also large computer systems used by companies and governments. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Integrity means that the information is secure from unauthorized changes ", header:"<span class='accent1'>Integrity</span> means that information is secure from <span class='accent1'>unauthorized changes</span>", section_image: "section_images/dataprotect_103215926.jpg", image_position: "imagerightxsmall", content: "People, companies, and governments do not want their important data to be changed by someone who should not be able to change the data. For example, a bank should protect its customers' bank accounts from theft. It should not be possible to hack into the bank and move money out of accounts without permission. Stealing money by hacking accounts and moving money to places it is not supposed to be is called &quot;cybertheft&quot;. It is a type of cybercrime. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"Availability means that a system can be accessed when needed without delay", header:"<span class='accent1'>Availability</span> means that a system can be <span class='accent1'>accessed</span> when needed <span class='accent1'>without delay</span>", section_image: "section_images/compsec_152697521.jpg", image_position: "imageleftsmall", content: "You have probably at some point tried to access a web site and have not been able to get to it. Sometimes web sites have problems that make them unavailable. The problems could be related to problems the company is having with a web site update, for example. They may have made a change that accidentally broke something. Or, sometimes there is a problem in the network, and that can cause delays and lower performance. <br><br>But, sometimes the problem is that someone is intentionally attacking the site. One type of attack is called a &quot;Denial of Service&quot; (DOS) attack. That means that someone is sending many, many requests to the web site, just to make the web site run slow and become unavailabile. This attack can be done by having the requests come from many different locations at once. Sometimes other sites are used to launch the attack, and those site owners may have no idea that their systems are being used for it. A Denial of Service attach from many different locations is called a &quot;Distributed Denial of Service&quot; or DDOS attack. The whole goal of this type of computer system attack is to bring a system down so that people cannot access it. DDOS attacks have been used to bring down news sites, like CNN, social media sites, like Facebook, commerce sites like Amazon.com, and government sites, like the White House and the Pentagon.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"A computer virus is software written to do something bad to a computer system", header:"A <span class='accent1'>computer virus</span> is software written to do something <span class='accent1'>bad</span> to a computer system", section_image: "section_images/trojanhorse_418097401.jpg", image_position: "imagerightmedium", content: "A computer virus is a type of software program that is written to do something bad to a computer. Sometimes the type of software that is written to do bad things to computer systems is called &quot;malware&quot;. Malware can destroy information on your computer, or force your computer to run poorly. Or, it could be used to capture passwords for bank accounts or other systems, for example by capturing what you are typing. A computer program that sits in the background capturing what you do or type is called a &quot;trojan horse&quot;. <br><br>A virus could to trick you into thinking that your computer has a problem, maybe through a message box that comes up when you are in a web browser. Sometimes these might give you a phone number to call to help you &quot;fix&quot; your problem. When you call, you will be connected to someone who will ask you for personal information. Or, they may have you do something to give them remote access to your computer (which will then let them capture passwords or do other destructive things.)<br><br>Or, a virus could lock you out of your system and data until you pay someone money, a &quot;ransom&quot;, for them to release your computer - this is called &quot;ransomware&quot;.<br><br>Antivirus software is a type of software that is designed to protect your computer from viruses. New viruses are created all the time, so antivirus software has to be updated all of the time, too. To keep your computers safe, be careful about Internet sites you visit, don't click on links to places you don't know much about, and don't ever enter passwords on a public WiFi hot spot. If you see a message that your computer has a virus, and tells you to call a number - don't do anything, and get an adult with some computer skills to help you. And don't ever share your passwords! Any time your computer is behaving differently and doing unexpected things, you should tell an adult. You might have a computer virus.")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What are three important dimensions of computer security?", question_image: "section_images/confidentialityintegrityavailability.png",explanation: "Confidentiality means that sensitive information, like bank account data, credit card numbers, and other personal information cannot be accessed by people who should not be able to see it. Integrity means that information cannot be changed by people who are not supposed to change it. Availability means that people can get to their computers and information whenever needed. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Apples, bananas, and canteloupe")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Aardvarks, bats, and cave men")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Confidentiality, integrity, and availability", correct: "true")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "What kind of data should be kept confidential from hackers?", question_image: "section_images/dataprotect_103215926.jpg",explanation: "Much of information now stored on computers should only be available to people who are allowed to have it. For example, computer systems used by doctors and insurance companies hold social security numbers and health histories. Banking systems store account numbers and account balances. Corporations keep trade secrets on computer systems. Governments keep information about employees and military information that should not be in the hands of other countries. As more and more important information is held by computers, it becomes even more important to protect it.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Information about bank accounts")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Identifying information like social security numbers and drivers licenses")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Credit card numbers, names, and addresses")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of the above", correct: "true")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "What is malware?", question_image: "section_images/trojanhorse_418097401.jpg",explanation: "Malware is software designed to do something bad to computers and computer systems. There are many different types of malware, and new malware is written all the time. Ransomware locks people out of their systems until money is paid to free it. A trojan horse sneaks onto computers and then silently does bad things, like capturing passwords, in the background.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Computer software that is used to play games")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Computer software that comes from a company named Mal Inc.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Computer software that is written to do bad things, like steal information and lock people out of their data", correct: "true")



#topic = FactoryGirl.create(:topic, name:"future of computing",  navgraphic: "navgraphics/computing_devices.png", catagory_id: catagory.id, available: "no")
#topic = FactoryGirl.create(:topic, name:"how computers work",  navgraphic: "navgraphics/computeranatomy.png", catagory_id: catagory.id, available: "no")

