# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#### Everything for Energy
#catagory = FactoryGirl.create(:catagory, name:"energy", navgraphic: "navgraphics/energy.png", headergraphic: "energy", color: "energy", video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"history of energy", navgraphic: "navgraphics/historyofenergy.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"renewable energy",  navgraphic: "navgraphics/renewableenergy.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"nonrenewable energy",  navgraphic: "navgraphics/nonrenewableenergy.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"energy transmission",  navgraphic: "navgraphics/energytransmission.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"energy storage",  navgraphic: "navgraphics/energystorage.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"energy consumption",  navgraphic: "navgraphics/energyconsumption.png", catagory_id: catagory.id, video: "EPDesign.m4v")

catagory = Catagory.create(name:"Energy", navgraphic: "navgraphics/energy.png", headergraphic: "energy", color: "energy", video:"//www.youtube.com/embed/XpRU_HVB1Eg")


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "first", main_idea:"Energy is the capacity to do work", header:"Energy is the <span class='accent1'>capacity</span> to do <span class='accent1'>work</span>", section_image: "section_images/mag_flashlight_with_d_batteries.png", image_position: "imagerightmedium", content: "To understand what that means, think about a flashlight. Flashlights use batteries as an energy, or power, source. When you switch on the flashlight, the light comes on. The batteries in your flashlight have the capacity – or ability – to do the work of powering your flashlight. The energy stored in batteries is a form of chemical energy. The energy is provided by a chemical reaction. <br><br> Capacity is also how much work something can do. For example, two D-cell batteries might be able to power a large flashlight, but not an entire home.  Even for the flashlight, those D-cell batteries won’t last forever. Eventually the batteries will be drained and will need to be replaced. The energy capacity of a battery is limited.")


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "second", main_idea:"People get energy from food; we measure the energy provided by food in calories", header:"<span class='accent1'>People</span> get energy from <span class='accent1'>food</span>; we measure the energy provided by food in <span class='accent1'>calories</span>", section_image: "section_images/plate_with_food_gauge.jpg", image_position: "imagerightmedium", content: "Did your parents, or coaches, or teachers ever tell you that &quot;Food is fuel&quot;? Our bodies get energy from food, and the energy we get is measured in calories. A calorie is a unit of energy. (What food labels call a &quot;calorie&quot; is actually 1,000 calories as scientists define a calorie. Bet you didn't know you're eating around 2,000,000 calories a day!) The scientific definition of one calorie is the amount of energy required to increase the temperature of one gram of water (a small amount) one degree Celsius (another small amount). Food really is fuel! ")


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "third", main_idea:"We use energy to power our world", header:"We use energy to <span class='accent1'>power</span> our <span class='accent1'>world</span>", section_image: "section_images/electricity_to_your_home.png", image_position: "imageleftlarge", content: "A hundred years ago, people didn’t have televisions, cell phones, or microwaves. But, today, we are surrounded by these machines in the developed world. We have to provide energy to power those devices just like we need energy – calories from food – to power our bodies. If &quot;food is fuel&quot; for our bodies, what’s the source of power for our modern devices?<br><br>Many of the household devices we own are powered by electricity. You plug a cord into the wall – for example, for a toaster – which uses the electricity provided to your house to power whatever you plugged in. That’s how we power toasters, microwaves, televisions, blenders, mixers, and other household appliances. We don’t normally think about where the energy comes from when we plug them in, but they get their energy from the “electric grid.” When you drive around town, you probably see power lines that deliver that electricity from the grid to businesses, homes, schools, hospitals, and other places. The electric grid is the way that we connect energy sources – which we will cover in the next section – with places that need energy, like houses and businesses.<br><br>Not everything is powered by plugging a power cord into the wall. Lots of things we use everyday use batteries as an energy source. Cars use batteries, too, and non-electric cars also burn gasoline for power (electric cars do plug in to a wall socket to recharge).
")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fourth", main_idea:"Energy sources are all around us, both renewable and non-renewable", header:"Energy sources are all around us, both <span class='accent1'>renewable</span> and <span class='accent1'>non-renewable</span> ", section_image: "section_images/energy_sources.png", image_position: "imagerightlarge", content: "There are a variety of ways that we generate energy to power our modern world, many of which people have used for hundreds or even thousands of years. Some of these are considered renewable, like wind and sunlight, which means that we are not in danger of running out of them. Some of these are being consumed faster than they are being created, such as coal, which means that we will some day run out of that energy source.<br><br>Non-renewable energy sources include coal, petroleum, and natural gas. These three energy sources are called “fossil fuels” because they are created by ancient living things, like plants and animals, that were buried in the ground millions of years ago. Because it takes millions of years to create coal or petroleum, we use them up much faster than new coal or petroleum is created. That’s why they are called “non-renewable”. We extract energy from fossil fuels by burning them, such as burning gas to run a car or burning coal to generate electricty at a power plant.<br><br> Renewable energy sources include wind, sunlight, and water. Solar Power uses the power of the sun's light to create electricity.  Hydroelectric Power refers to making electricity from the power of water in motion. For example, water flowing over a man-made dam falls downward due to the force of gravity (the same reason a ball falls down if you throw it in the air). The power in this falling water can be used to turn turbines at the bottom, which can generate electricity through a process called electromagnetic induction.")

question = Question.create(catagory_id: catagory.id, question_num: "1", question_content: "What is Energy?", question_image: "section_images/mag_flashlight_with_d_batteries.png",explanation: "Energy is the capacity to do work. Our bodies get energy from food. The devices we rely on get their energy from sources like electricity, batteries, or gasoline.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "The capacity to do work")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "What your body gets from eating healthy food")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "What batteries provide for a handheld gaming console")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of the above", correct: "true")

question = Question.create(catagory_id: catagory.id, question_num: "2", question_content: "We use energy for:", question_image: "section_images/electricity_to_your_home.png",explanation: "Household appliances use electricity provided to our homes. Vehicles run off energy sources like gasoline, jet fuel, or electricity. We use energy to run around the park; we get energy to run around from the food we eat.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Running household appliances like microwaves and televisions")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Powering vehicles like cars, trains, and airplanes")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Running around the park")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of the above", correct: "true")

question = Question.create(catagory_id: catagory.id, question_num: "3", question_content: "Coal is:", question_image: "section_images/coal_76286749.jpg",explanation: "Coal is considered a non-renewable form of energy. It takes millions of years to turn an ancient plant into coal. We use up the energy much more quickly than it can be created.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: " A renewable form of energy")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A non-renewable form of energy?", correct: "true")




topic = FactoryGirl.create(:topic, name:"energy sources",  navgraphic: "navgraphics/energysources.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"The two types of energy are renewable and non-renewable", header:"The two types of energy are <span class='accent1'>renewable</span> and <span class='accent1'>non-renewable</span>", section_image: "section_images/energysrcs-various2.png",image_position: "imagerightlarge", content:"There are a variety of ways that we generate energy to power our modern world, many of which people have used for hundreds or even thousands of years. Some of these are considered renewable, like wind and sunlight, which means that we are not in danger of running out of them. However, some sources are being consumed much faster than they are being created, such as coal, which means that we will someday run out of that energy source.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", section_image: "section_images/fossilfuelsarray.png",image_position: "imageleftmedium", main_idea:"Non-renewable energy sources are used up faster than they can be replaced", header:"Non-renewable energy sources are used up <span class='accent1'>faster</span> than they can be <span class='accent1'>replaced</span>", content:"Non-renewable energy sources include coal, petroleum, and natural gas. These three energy sources are called “fossil fuels” because they are created by ancient living things, like plants and animals, that were buried in the ground millions of years ago. After long periods of time under intense pressure and heat, these ancient living things change into fuels like coal and petroleum. Because it takes millions of years to create coal or petroleum, we use them up much faster than new coal or petroleum is created. That’s why they are called “non-renewable”.  Non-renewable resources are the primary source of energy in the world today.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"We get power from fossil fuels by burning them", header:"We get power from <span class='accent1'>fossil fuels</span> by <span class='accent1'>burning</span> them",  section_image: "section_images/burningcoal.png",image_position: "imagerightlarge", content:"We extract energy from fossil fuels by burning them, such as burning gas to run a car or burning coal to generate electricity at a power plant. Fossil fuels are extremely flammable and create a hot flame. When the fuels are burned, heat is generated.  This heat is used to heat water, which in turn creates steam. The steam is used to turn turbines. These turbines turn generators, which create energy that we can use.<br><br>
When these fuels are burned, they create various gases called emissions.  Large amounts of these gases create pollution.  In addition to their limited supply, the pollution they create is the largest downside to fossil fuels. If you have heard of the terms “climate change” or “global warming”, you may already know that burning fossil fuels are among the causes of pollution that create climate change. Climate change refers to long-term changes to the weather we experience, for example more frequent droughts or more frequent severe weather. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"Nuclear energy uses the power of atoms to create energy", header:"<span class='accent1'>Nuclear</span> energy uses the power of <span class='accent1'>atoms</span> to create energy", section_image: "section_images/nuclearenergybycountry.png",image_position: "imagerightsmall", image_caption: "Source: International Atomic Energy Agency, March 2015", content:"Atoms are the smallest division of life.  Everything in the world is made up of atoms. Each atom has a central particle called a “nucleus”. Nuclear energy gets its name from the fact that the power comes from the nucleus. We produce nuclear energy by splitting uranium or plutonium atoms in a process called <i>nuclear fission</i>. When these atoms are split, the action releases a huge amount of energy.  The heat created from this process is then turned into steam, which is used to turn turbines. The percent of energy production by harnessing nuclear energy varies widely by country, as the table shows.<br><br>Nuclear fission processes occur in a special structure in a nuclear power plant, called a “containment structure”, which is designed to keep dangerous radiation from escaping the plant. Nuclear processes generate something called nuclear waste.  This consists of the leftovers after nuclear fission. This radioactive waste is dangerous to people and animals, and has to be carefully disposed of. <br><br>Every once in a long while, there are accidents of some kind at nuclear power plants. Past examples include the failure of the Fukushima power plant in Japan after the 2011 earthquake and tsunami, an accident in 1979 at the “Three Mile Island” power plant in the US, and the Chernobyl power plant in Russia in 1986. Each of these resulted in radioactive material released into the surrounding environment. Because of the danger of nuclear accidents, some people do not like nuclear power generation. Japan generated 30% of their power via nuclear power plants before the Fukushima accident; now Japan is largely against nuclear power, and produces less than 2% of its energy through nuclear power.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"Renewable energy sources are not used up", header:"<span class='accent1'>Renewable</span> energy sources are <span class='accent1'>not used up</span>", section_image: "section_images/callout_renewables.png",image_position: "imagerightmedium", content:"Renewable energy sources are considered the best for the environment since nothing from nature has to be destroyed or used up. Renewable energy is growing and expanding, but is still not close to fossil-fuels in their use. About 19% of the energy used in 2014 came from renewable resources.  Some countries are using much more renewable energy than others, as the table on the right shows. Often when the prices of fossil fuels increase, the use of renewable energy grows. Some examples of renewable energy sources are solar power, hydroelectric power and wind power. These are each described below.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"sixth", main_idea:"The power created by the sun is called solar power ", header:"The power created by the <span class='accent1'>sun</span> is called <span class='accent1'>solar power</span> ", section_image: "section_images/solarenergy2.png",image_position: "imagerightlarge", content:"Solar power uses the power of the sun's light to create electricity. This energy is collected through solar panels. Solar panels are made up of a large number of solar cells. These cells help focus the sun’s energy and transform this into usable electric energy. Many solar panels are placed over a large area to create solar arrays. These are angled at a position to get the most out of the sun’s rays and be facing the sun at the most times during the day.<br><br>In addition to large arrays people are installing solar panels on their homes and businesses.  This allows people to create their own power and not have to purchase it.  However, solar panels are not cheap and require a lot of money to install them in the first place.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"seventh", main_idea:"Power created by water is called hydroelectric power", header:"Power created by <span class='accent1'>water</span> is called <span class='accent1'>hydroelectric power</span>", section_image: "section_images/three_gorges_dam_128863591.jpg",image_position: "imageleftmedium", content:"Hydroelectric power refers to making electricity from the power of water in motion. For example, water flowing over a man-made dam falls downward due to the force of gravity (the same reason a ball falls down if you throw it in the air). The power in this falling water can be used to turn turbines at the bottom, which can generate electricity through a process called electromagnetic induction.<br><br>This is the most widely used form of renewable energy. However, it does have its disadvantages. Hydroelectric power requires bodies of water to be damned up.  This effects the ecosystem and animals living in the area.  It impacts their movement within the body of water. In addition, if a region is experiencing a drought – an uncommonly dry year or years – then they may no longer be able to generated as much power using hydroelectric dams, as there may be much less water available.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"eighth", main_idea:"Wind power is collected by wind turbines", header:"<span class='accent1'>Wind power</span> is collected by <span class='accent1'>wind turbines</span>", section_image: "section_images/wind_turbines_on_land_163319147.jpg",image_position: "imageleftmedium", content:"We are able to harness the power of wind by using large wind turbines and windmills to generate electricity.  These turbines are set up in wind farms in large open areas consisting of up to thousands of turbines.  They are positioned to be facing the most common direction of the wind and slowly turn as the wind blows. There are even windfarms being set up in the ocean to take advantage of strong ocean winds and not affect large open landscapes.<br><br>Although wind power is one of the cheapest forms of energy, the amount of wind in an area is not consistent and predictable. Since wind is variable force the amount of energy it generates is also not consistent. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"eighth", main_idea:"Turbines are key to power generation", header:"<span class='accent1'>Turbines</span> are key to power generation", content:"You may have noticed a common theme in this section. Power generation comes about often by turning turbines. These turbines may be turned by steam, by wind, or by water. And the steam could result from burning a fossil fuel or creating a nuclear reaction. But the result in any case is that a turbine is turned. And, turning a turbine can generate electricity through a process called <i>electromagnetic induction</i> - a topic for another section.")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "Name two categories of energy sources", question_image: "section_images/energysrcs-various2.png",explanation: "The two main categories of energy sources are renewable - like wind, sun, and water - and non renewable - like coal, oil, and natural gas.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Ham and eggs")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Bread and butter")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Renewable and non-renewable", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "Mom and Dad")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "Why are non-renewable energy sources like coal and oil called non-renewable?", question_image: "section_images/burningcoal.png",explanation: "Non-renewable energy sources come from ancient living things, like plants and animals. For example, it took millions of years for the coal we use took to change from living plants into coal. We use up non-renewable energy sources, like coal, oil, and natural gas, much more quickly than the millions of years it took to create the new coal, oil, or gas we now have.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Because it sounds cool")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Because we will never run out of them")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Because we use them up much faster than they can be replaced", correct: "true")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "Which of the following are renewable energy sources?", question_image: "section_images/energysrcs-various2.png",explanation: "Renewable energy sources are sources that we are not in danger of running out of, like wind and solar (sun).")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Wind, coal, and natural gas")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Wind, sun, and water", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Natural gas, coal, and petroleum")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "Solar, wind, and coal")


topic = FactoryGirl.create(:topic, name:"energy conversion",  navgraphic: "navgraphics/energyconversion.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"There are different forms of energy", header:"There are different <span class='accent1'>forms</span> of energy", section_image: "section_images/energy_forms.png", image_position: "imagerightmedium", content:"There are many different forms of energy. Think of some things you see around you that use energy. Batteries may power a handheld game or a flashlight. Your toaster and refrigerator are plugged into the wall, which is connected to the power in your house. The power in your house usually comes from the power company, but could come from other sources like solar panels on your roof. You get your energy from food. The thing you are trying to power usually takes its energy from only one, or maybe two forms. For example, a laptop computer can run on its battery, or can run plugged in even with a dead battery. But, if you are tired and want more energy, you can’t plug yourself into a wall!  You have to eat food or drink liquid to get your energy. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"Energy must be changed into the right form in order to be used", header:"Energy must be <span class='accent1'>changed</span> into the right form in order to be used", section_image: "section_images/coal_powered_toaster.png", image_position: "imageleftmedium", content:"Sometimes we can get energy in one way, but we need to use it in another way. Think of energy companies that extract oil from the ground or mine coal. Our modern houses are set up to run off of electricity. So, in order to use coal as a power source for houses and businesses on the electric grid, we need to be able to turn it into electricity. We don’t burn coal in our houses to heat them or power our toasters! By the time it reaches the outlets in our house, it has already been converted to electricity for us. In order to get the energy we want into the right form we must <i>convert</i> it. Converting energy means changing energy from one form to another.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"Energy cannot be created or destroyed", header:"Energy cannot be <span class='accent1'>created</span> or <span class='accent1'>destroyed</span> ", section_image: "section_images/sticky_note.png", image_position: "imagerightsmall",content:"You might get tired of all the rules in your daily life, but did you know that even science has rules it must follow? One rule is called the “law of conservation of energy”. This law means that energy cannot be created or destroyed. Nothing in nature and nothing that people can do can violate this rule – it’s a rule because it is just not possible to break it. This is the rule that controls the converting of energy. And, it is something engineers must keep in mind when making new things.  It means that energy can only change forms, but there is no way for us to create completely new energy or get rid of energy from the world.  It must come from somewhere else to start with, or be passed off to something else. <br><br>However, there is not a way for us to create a perfect transfer of energy. Some energy is always lost in ways that were not intended, such as the creating of heat, light, or sound. Think of your oven, which you use to heat your food; it also tends to heat your kitchen as well. This is energy intended to heat your food that was lost to the surrounding environment. These small things take away energy that could have been going to a different and more useful purpose. Engineers use words like “efficiency” to talk about how much of the energy goes to the intended use versus being lost in other ways. Engineers think about this loss when designing ways to move or convert energy.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"The two major kinds of energy are kinetic and potential energy", header:"The two major kinds of energy are <span class='accent1'>kinetic</span> and <span class='accent1'>potential</span> energy", section_image: "section_images/roller_coaster_combo.png", image_position: "imagerightlarge",content:"Kinetic energy is the energy of motion. When a rollercoaster reaches the bottom of a hill and is going fast it has a high kinetic energy. Electricity is a type of kinetic energy because it is moving energy between tiny particles allowing the electric energy to move. The movement of electric energy is called a current.<br><br>Potential energy is the measure of stored energy. It is the work something has the potential to do. A roller coaster has its highest potential energy at the top of the hill. This is because it has the potential to speed up greatly.  At the bottom of the hill, it does not have the option to get faster without some extra input because it is closer to the ground. Those things are true because of the force of gravity, which is the force that pulls things to the ground, like a ball that falls to the ground when you let go of it.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"When energy moves between kinetic and potential energy it is being converted", header:"When energy moves between kinetic and potential energy it is being <span class='accent1'>converted</span> ", content:"As the roller coaster car moves down the hill it loses potential energy and gains kinetic energy.  As the speed of the car increases the amount of kinetic energy goes up. As the height of the rollercoaster car decreases, the potential energy goes down. <br><br>Since energy cannot be created or destroyed, there is an almost even exchange between kinetic and potential energy.  Small amounts of energy are lost in the creation of sound or friction between the roller coaster cars and the track. To read more about friction check out the Machines section.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"sixth", main_idea:"Power plants and engines convert potential energy into usable energy for machines", header:"Power plants and engines convert potential energy into <span class='accent1'>usable energy</span>  for machines", section_image: "section_images/converting_energy.png", image_position: "imagerightmedium", content:"Fuels like coal and gas contain potential energy. This energy is released and converted when heated and burned. Combustion is the process of burning fossil fuels to create usable energy.  Check out the Machines section for more on combustion.<br><br>The energy that comes from your wall plugs is called electricity and is made from power plants.  These power plants convert potential energy from many sources into the kinetic energy of electric power. Things in our house that need power get power by plugging into the wall. They may then convert the energy again.  For example, kitchen blenders change this electricity into mechanical energy to create the motion of the spinning blades. TVs change electricity into the light and sound needed to create the images and sounds for TV shows.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"seventh", main_idea:"Food contains a type of potential energy called chemical energy", header:"Food contains a type of potential energy called <span class='accent1'>chemical energy</span> ", content:"The way we get energy into our bodies is by eating food.  Food contains different kinds of sugars and molecules that are the things that power our bodies (including our brains – you are consuming energy to sit here learning about energy!).  Our bodies convert the chemical energy from the food into energy usable by our bodies. Our bodies do this by performing chemical reactions inside of our stomach. This energy is then absorbed into our bloodstreams. Then, we convert this chemical energy into motion and everything we do in our everyday lives. This energy keeps us breathing, our heart beating, our muscles moving, and our brain working.<br><br>We get “sugar rushes” after eating too much candy, because candy contains a higher amount of sugar than other foods, and sugar provides a quick source of energy into our blood streams. Because sugar is such a quick source of energy, the energy we get from it is used up quickly, too. A while after eating very sugary foods, you may feel completely wiped out; we call this a “sugar crash”.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"eighth", main_idea:"Humans can convert energy", header:"<span class='accent1'>Humans</span>  can convert energy", section_image: "section_images/family_riding_bicycles.jpg", image_position: "imagerightmedium", content:"After our body converts the chemical energy into energy our body can use, we can then convert the energy again. Whenever you pedal a bike you are converting the chemical energy in your body into mechanical work. You are moving your legs with the chemical energy and this then turns the pedals and creates a forward motion.<br><br>When you play baseball you are creating an energy transfer in addition to converting energy. You are using your chemical energy to create kinetic energy and swing the baseball bat.  This kinetic energy is then being transferred to the baseball causing it to then move in the opposite direction.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"ninth", main_idea:"Energy and energy conversion are big parts of engineering", header:"Energy and energy conversion are <span class='accent1'>big parts</span> of engineering", content:"We need energy for engineering. Because it’s not always in the form we need to use it, energy conversion is an important topic in engineering. We convert potential energy in coal, oil, and natural gas to kinetic energy in the form of electricity in our house. We convert the potential energy of the gasoline in the gas tank of our car to the mechanical energy that makes the car move. We convert potential energy of batteries into the kinetic electric energy of handheld gaming devices or mobile phones. And, we convert the potential energy of food into mechanical energy of our bodies by eating food, getting nutrients from it, and using the energy provided by it to fuel our bodies. Energy conversion is everywhere!")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "Which of the following are examples of energy conversion?", question_image: "section_images/coal_powered_toaster.png",explanation: "Energy conversion takes energy in one form and turns it into another. A nuclear power plant splits atoms to heat water to create steam to turn turbines that generate electricity. A battery uses a chemical reaction to generate electricity. Your body processes food to store energy for your body. All of these are examples of changing a source of energy from one form to another.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Your body turning food into energy that your body can use to run, jump and play")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A coal plant burning coal to produce electricity for the grid")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "A car burning gasoline to run the engine")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of these are examples of energy conversion", correct: "true")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "When we generate electricity for the grid, are we creating energy or merely converting it from one form to another?", question_image: "section_images/burningcoal.png",explanation: "The Law of Conservation of Energy says that energy can never be created or destroyed. We are merely converting energy, for example from the potential energy of coal into electricity.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "We are creating energy - that's why they call it power generation")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "We are converting energy from one form to another. You can't create energy where none exists. You can only convert it from one form to another.", correct: "true")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "Which of the following is NOT a true statement?", question_image: "section_images/roller_coaster_combo.png",explanation: "Kinectic energy is energy of motion, for example a roller coaster going down a hill, water flowing over a dam, or an electric current on a wire. Potential energy is stored energy, or a capability of doing work this isn't currently being applied. Examples of potential energy are a new battery in a package, water at the top of a dam, or a roller coaster at the top of a hill. An electric current results from moving electrons, so it is also a form of kinetic energy.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Kinetic energy is energy of motion")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Potential energy is stored energy")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "A roller coaster at the bottom of a hill is a good example of potential energy", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "An electric current is a type of kinetic energy")

topic = FactoryGirl.create(:topic, name:"electricgrid",  navgraphic: "navgraphics/electricgrid.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Power that comes out of our walls comes from the energy grid", header:"Power that comes out of our <span class='accent1'>walls</span> comes from the <span class='accent1'>energy grid</span>",  content:'We don’t normally think about where the energy comes from when we plug something into a wall socket, but the energy comes from the “electric grid.” When you drive around town, you probably see power lines that deliver that electricity from the grid to businesses, homes, schools, hospitals, and other places. The electric grid is the way that we connect energy <i>sources</i> with places that <i>need</i> energy, like homes and businesses.')
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"The electric grid was built to make the movement of energy around the US more efficient", header:"The electric grid was built to make the <span class='accent1'>movement of energy</span> around the US more efficient",  section_image: "section_images/power_lines.png", image_position: "imagerightlarge", content:"The electric grid was created in the early 1900s to make the movement of energy around the country more efficient. Around this time, demand for energy was increasing. Companies found it easier to work together to connect their systems to provide electricity to people.  Lots of electric transmission lines were connected to each other, giving people better access to electricity. <i>Transmission lines</i> carry the electricity for long distances, while <i>distribution lines</i> carry electricity small distances within neighborhoods.<br><br>The result of these companies connecting their lines is the five grids that combine to make what today we call the electric grid. The two larger, or major, grids are the Eastern Interconnection and the Western Interconnection. The three smaller, or minor, grids are the Texas Interconnection, the Quebec Interconnection and the Alaska Interconnection. Together, these five grids provide electricity for most of the United States, Canada and parts of Mexico.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"Transformers allow electricity to be moved more efficiently", header:"<span class='accent1'>Transformers</span> allow electricity to be moved more <span class='accent1'>efficiently</span>", section_image: "section_images/transformers.png", image_position: "imagerightsmall", content:"When you see large power lines next to roads, they are carrying electricity at an extremely high voltage. Voltage is a measure that relates to how much electric current is moving through a wire or device. The higher the voltage in a wire, the more power you get out of it, and the more efficiently power can be transmitted. This means more of the electricity makes it to the final location. Therefore, when we are moving electricity around the country, we are doing so at a much higher voltage than is safe or possible to use to power our items in our home.<br><br>
We use <i>transformers</i> to change voltage levels between the levels that our homes use and the levels that transmission lines use. Transformers allow for the voltage to be stepped up &#40;made greater&#41; or stepped down &#40;made lower&#41;. Transformers step up the voltage after it is generated at a power plant and step down the voltage before providing the power to homes. These transformers are located at electrical substations, on power poles, and in boxes connected to power lines in every neighborhood across the country.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"The energy that the grid provides is alternating current (AC)", header:"The energy that the grid provides is <span class='accent1'>alternating current (AC)</span>",  content:"There are two types of electric current: alternating current (AC) and direct current (DC).  In the late 1880s the widespread use of electricity was just beginning. At that time, there was a controversy about whether it was better to distribute power to homes and businesses using AC or DC current. Thomas Edison had just patented the incandescent light bulb, which runs on electricity. Patents give inventors the exclusive rights to an invention for a limited period of time. In order for people to buy and use these new light bulbs, electricity had to be distributed from where it was created, in power plants, to where people would use the light bulbs, like homes and businesses.<br><br>The controversy between AC and DC current is sometimes referred to as the “War of Currents”. It was waged between two of the foremost inventors of the industrial age: Thomas Edison and George Westinghouse. Thomas Edison not only held the patent on the incandescent light bulb, but he also held many important patents for the distribution of DC power. George Westinghouse was a very successful engineer and inventor. He was also interested in the distribution of electricity. He acquired critical patents for the distribution of AC power from an inventor named Nicola Tesla. <br><br>Edison tried to show that AC power was dangerous because of the high voltages involved. However, AC power quickly outpaced DC in the race for the distribution of electricity, primarily because it was more cost effective. Transformers allowed AC current to travel at high voltages on smaller, less expensive wires, and then be stepped down to a safe voltage for usage. Because AC could travel farther more efficiently, power users could be further away from power sources, which helped use of electricity to grow quickly.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"The grid brings energy to your home through a multi-step process", header:"The grid <span class='accent1'>brings energy to your house</span> through a multi-step process",  content:"The overall process that the grid follows to get energy to your home is:<br><br>1. A power plant generates the electricity. There are over 7,000 power plants that are currently connected into the US electric grid.  See the Energy Sources section to learn how different power plants generate electricity.<br>2. A transformer prepares the electricity to be transmitted through electrical lines by stepping up the voltage.<br>3. Over 450,000 miles of transmission lines carry the electricity around the United States to the needed location.	<br>4. Another transformer prepares the electricity for use by houses by stepping down the voltage<br>5. Distribution lines carry the electricity the final distance to houses and businesses.<br>6. One last transformer steps down the voltage of the electricity before it enters homes to make it 120 volt AC.<br>7. Electricity is carried throughout the building and powers all things that are plugged into the walls.<br><br>Next time you plug something in at your house, think about the trip the energy had to take to get to you. It could have come hundreds of miles to help power your TV, microwave or MP3 player!")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"sixth", main_idea:"Other parts of the world have electric grids as well", header:"Other <span class='accent1'>parts of the world</span> have electric grids as well",  content:"There are electric grids all over the world. The continent of Europe has one that reaches over 400 million customers in 24 countries. Although this grid also uses AC, it uses 220 volt current. This is double the volts of the American grid, which uses 110 volts. If you travel to Europe, you won’t be able to plug your devices into the wall. You will need to plug a converter into the wall first. The converter will act as transformer and step down the voltage to work with your device. You might wonder why different parts of the world use different standards for electricity. The answer is largely for historical reasons. Once a standard is established it can be very expensive to change to a new one.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"sevent", main_idea:"The electric grid is how we connect power sources with power users", header:"The electric grid is how we <span class='accent1'>connect</span> power <span class='accent1'>sources </span> with power <span class='accent1'>users</span>",  content: "When you plug a device into an outlet on the wall, you are using the electric grid. The electricity you are using may have been generated by wind moving a turbine, by coal being burned to generate steam to turn a turbine, or some other method. However the electricity was generated, the electric grid delivers that electricity to your home in the exact way you need it to power whatever machine or device you are using. The electric grids around the world make many modern conveniences possible.")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What is the electric grid?", question_image: "section_images/power_lines.png",explanation: "The electric grid is how we connect power sources with power users. Electricity is generated by power plants, carried over transmission lines, and distributed to places that need it.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "The infrastructure that carries electricity from the power plants generating the electricity to the houses, businesses, and other locations that need it", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A pan that you use to cook pancakes")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "No, really, it's a pan you use to cook pancakes")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "Identify the statement that is NOT true", question_image: "section_images/transformers.png",explanation: "There are electric grids all over the world. There are five interconnected grids providing most of the electricity for North America alone. The five interconnected American grids all use 110 Volts. However, the European grid uses 220 Volts. Just about anywhere that has electricity must have some kind of electric grid infrastructure. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Transformers change voltage levels between the levels that our homes use and the levels that transmission lines use.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "The electric grid was built to make the movement of energy around the US more efficient.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Transmission lines carry the electricity for long distances, while distribution lines carry electricity small distances within neighborhoods.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "There is only one grid in the world, and one voltage level used on it.", correct: "true")


#topic = FactoryGirl.create(:topic, name:"energy use",  navgraphic: "navgraphics/energyuse.png", catagory_id: catagory.id, available: "no")
#topic = FactoryGirl.create(:topic, name:"energy storage",  navgraphic: "navgraphics/energystorage.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"energy storage",  navgraphic: "navgraphics/energystorage.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Energy storage is used to keep energy available for later use", header:"Energy <span class='accent1'>storage</span> is used to keep energy available for <span class='accent1'>later use</span>", section_image: "section_images/batteries_just_batteries.png", image_position: "imagerightmedium", content:"Why store energy? We store energy in order to have it later when we need it. What examples can you come up with of stored energy?<br><br>How about a battery? Batteries hold chemical potential energy. We use batteries in electric and electronic devices – like gaming consoles, smart phones, tablets, and laptops. The chemical potential energy is available as electricity when it is needed. Batteries provide a way to store energy as chemical potential energy, and then convert it later to electricity.<br><br>How about gasoline in a car? A gas tank also stores potential energy in the form of gasoline. When your car needs the gas to power the car, the gasoline is burned. The combustion (burning) of the fuel converts the chemical potential energy of the gasoline into mechanical kinetic (movement) energy in the parts of your car. <br><br>How about your body? You also store potential energy. When you eat, your body absorbs the calories and nutrition. Your body stores the energy for when you need it. You can still run two hours after lunch, can’t you? You don’t need to keep eating constantly in order to keep moving. But, you do need to eat healthy meals regularly to ensure that you have enough energy for everything you do. Energy in foods is an example of energy storage in nature.<br><br>When it comes to the electric grid, energy storage can help us save energy for when we need it. We rely on the energy grid every day, but our energy demand at any given time may not match the supply at that time.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"Our energy demand does not always match our energy supply", header:"Our energy <span class='accent1'>demand</span> does not always match our energy <span class='accent1'>supply</span>",  section_image: "section_images/energyterms.png", image_position: "imageleftmedium", content:"Sometimes our <i>supply</i> of energy available on the grid is more or less than our <i>demand</i>. Energy <i>supply</i> is how much energy is available on the grid at a particular time. Energy <i>demand</i> is how much energy people want to use at that time. Energy demand varies from day to day, and even over the course of a day. On hot days, many people run their air conditioning. On cold days, many people run their heaters. Heating and air conditioning both consume a lot of power. Overnight, most people are sleeping rather than running their televisions or microwaves, so demand is lower overnight.<br><br>Our electricity consumption has increased over time, as more and more things we rely on every day require electricity to work. Look around the room – how many of the things you use every day require electricity? In the past 50 years, demand for electricity in the US alone has quadrupled.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"We can use energy storage to balance out energy demand and supply", header:"We can use <span class='accent1'>energy storage</span> to <span class='accent1'>balance</span> out energy <span class='accent1'>demand</span> and <span class='accent1'>supply</span>",  section_image: "section_images/EnergyScalefinal.png", image_position: "imagerightsmall",content:"There can be issues on an electric grid if the need for electricity does not match the amount that is being produced at that time.  If people are trying to use more electricity than is available at a specific time, then the result may be blackouts or brownouts.<br><br>A blackout is when all power is lost to an area, causing all the lights to go out, or “go black”. A brownout is a drop in voltage in the grid causing less energy to reach an area. This brownout may actually be created on purpose to stop the complete loss of power to an area. Alternately, the people managing the power for an area may use “rolling blackouts” to conserve energy when the available supply is low. A rolling blackout is a series of small power outages that roll through different areas in an attempt to fairly share the limited electricity available among all the people who want it.<br><br>The largest blackout in United States history happened in 2003. During this blackout over 50 million people in the northeast were impacted by the loss of power. After this occurred the United States worked to stop future events like this from happening. If we have energy stored, we can have a plan in place in case a blackout or brownout occurs. The storage of energy became a topic that was more important after these issues of blackouts and brownouts. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"Energy storage is critical for renewable energy sources like wind and solar power ", header:"Energy storage is critical for <span class='accent1'>renewable</span> energy sources like <span class='accent1'>wind</span> and <span class='accent1'>solar</span> power",  section_image: "section_images/renewable_energy_sources.png", image_position: "imagerightmedium", content:"Energy storage is becoming even more important as renewable energy becomes more common. Renewable energy is available when it is available, rather than when we demand it. For example, the wind blows when it blows. So, wind turbines generate electricity due to the forces of nature – not when we want more electricity. The sun shines when it shines – not when we ask it to! If you are using solar energy to power your home, you still need energy at night when the sun is not shining.<br><br>Renewable energy is made on its own schedule. However, we can make efficient use of it by storing any excess energy. This way energy can be generated whenever the sources of energy are available. Storing excess capacity can also help meet electric needs when there are times of high demand. An example of a period of high demand might be a heat wave across a large portion of the country – so that many people are running their air conditioners at the same time. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"Energy can be stored in many forms", header:"Energy can be <span class='accent1'>stored</span> in many <span class='accent1'>forms</span>",  section_image: "section_images/hydroelectric_power.png", image_position: "imageleftsmall", content:"People have developed many different ways of storing energy. We have already mentioned a few ways above. Another way to store energy on the grid is by creating dams. Dams are large man-made structures that hold back powerful bodies of water. A dam holding back water is storing the potential energy of the force of the water at the top of a dam. The water held back by a dam is higher than the water below the dam. There are turbines at the bottom of the dam. When water is allowed to flow over the dam down to the lower side, the water falls with tremendous force due to gravity. The falling water turns turbines at the bottom. These turbines generate electricity. The force of gravity allows the potential energy of the captured water to be converted to the kinetic energy of falling water. And then the turning of the turbines at the bottom of the dam converts the energy of the falling water to electricity. So, if the grid has excess electricity at any given time, one way to store it is to use the excess energy to pump water to the top of the dam. Using the excess energy to pump it back up to the top of a dam converts it back into potential energy.<br><br>There are other ways to store excess energy from the grid. As more electricity generation comes from renewable sources, there will be ongoing innovations in energy storage. Large batteries can be used to store energy for the grid. As battery costs continue to drop, using batteries for grid storage will become more cost effective. There are other technical ways to store energy for the grid, including something called a flywheel and compressed air storage. The next decade will likely see a lot of innovation in energy storage, and a lot of projects to implement storage on the grid. There are already a number of projects all over the world.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"sixth", main_idea:"Using stored energy requires converting, or changing, the energy from one form to another", header:"Using stored energy requires <span class='accent1'>converting</span>, or changing, the energy from one <span class='accent1'>form</span> to <span class='accent1'>another</span>",  content:"Humans use stored energy every time they go for a run, skate or even just lift up a cup off table. These actions are changing the energy that we get from food, chemical energy, into kinetic energy, or the energy of motion.<br><br>A similar change must occur when energy stored in coal, gasoline, or even water held behind a dam is changed into energy that we can use to power our devices. When coal or gasoline is burned, it heats water that changes into steam.  This steam then turns turbines to create kinetic energy.  Water that leaves a dam gets out through turbines as well. The act of turning a turbine generates electricity that we can then use in our homes.<br><br>Every time stored energy is accessed, it is changed from potential energy to kinetic energy. And, it is changed from some particular type of potential energy (like chemical) to some particular type of kinetic energy (motion, electricity, etc.). And, the act of storing energy does the reverse – it changes kinetic energy (like electricity) and converts it to potential energy (like water at the top of a dam). Energy conversion is critical to energy storage.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"seventh", main_idea:"Energy storage is still changing and evolving", header:"Energy <span class='accent1'>storage</span> is still changing and <span class='accent1'>evolving</span>",  content:"New innovations and advances are being made in energy storage.  Some of the innovations are on a small scale, while some are on a large scale. <br><br>Previously when your cell phone ran out of power, you had to plug back into a wall in order to get more power. However, portable cell phone chargers are becoming more popular. These chargers are small batteries that can store a lot of energy. Some can even charge your phone up to three times before you have to charge the portable charger’s battery again. These portable chargers are helping make the charging process mobile.<br><br>On the other side of things, we have new large batteries that can store enough energy to power a house. The company Tesla has created a large battery for a home or business that charges from power made by solar panels on the roof. Use of solar-charged batteries to power a home is one step towards independence from the energy grid. Large batteries such as these can give homes and cities protection from blackouts and brownouts. If the electric grid has an issue, homes with these batteries can run off the energy stored in the batteries for some amount of time. Many cities in California are building areas with more storage for this reason. <br><br>A new plane being developed in Switzerland has taken advantage of batteries and energy storage to make a completely solar plane. Its goal is to be the first aircraft to make a complete trip around the world only using solar power. It has solar panels in the wings that power the motor and charge batteries during the day. Then at night the motor runs solely off the batteries. The longest flight the plane has made so far is from Japan to Hawaii. Solar-and-battery planes are not ready for everyday use. But, they do demonstrate one way that innovations in renewable energy sources and energy storage are being explored and tested.<br><br>Advances have also been made in water dams and hydroelectric energy. For example, at a water dam in China, any extra energy that is produced is stored for later times when it is needed. The extra energy is used to move the water from the low side of the dam up to the high side. When the energy is needed during peak times, the water to can be allowed to flow back over the dam and through the turbines to generate electricity.<br><br>As new technologies keep being made, we are moving into a society that uses more renewable energy and is capable of storing more energy.  We can move around more with our stored energy and more further away from dependence on the energy grid.")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What are some reasons we might want to store energy?", question_image: "section_images/batteries_just_batteries.png",explanation: "Energy storage is used to keep energy available for later use. We can use energy storage to balance out energy demand and supply. And, energy storage is critical for renewable energy sources like wind and solar power, because we only have sunshine during daylight and wind on windy days.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Our demand for energy does not always match our supply")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "We can use energy storage to take advantage of renewable energy sources like wind and sun when they are available, and then store it for later use when we need it.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "If we have some available stored energy, then it might be possible to use it if there are problems on the electric grid.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of the above are reasons we might want to store energy", correct: "true")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "Which of the following is a way that energy can be stored?", question_image: "section_images/transformers.png",explanation: "People have developed many different ways of storing energy. If a grid has excess electricity at any given time, one way to store it is to use the excess energy to pump water to the top of the dam. Using the excess energy to pump it back up to the top of a dam converts it back into potential energy. Large batteries can be used to store energy for the grid. As battery costs continue to drop, using batteries for grid storage will become more cost effective. And, there are some other ways to store energy, like compressed air storage and something called a flywheel.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Pump water up to the top of a dam")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Store as potential chemical energy in a battery")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Compress air into a container")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "These are all possible ways to store excess energy", correct: "true")

#topic = FactoryGirl.create(:topic, name:"future of energy",  navgraphic: "navgraphics/energyfuture.png", catagory_id: catagory.id, available: "no")

