# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#### Everything for Energy
#catagory = FactoryGirl.create(:catagory, name:"energy", navgraphic: "navgraphics/energy.png", headergraphic: "energy", color: "energy", video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"history of energy", navgraphic: "navgraphics/historyofenergy.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"renewable energy",  navgraphic: "navgraphics/renewableenergy.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"nonrenewable energy",  navgraphic: "navgraphics/nonrenewableenergy.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"energy transmission",  navgraphic: "navgraphics/energytransmission.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"energy storage",  navgraphic: "navgraphics/energystorage.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"energy consumption",  navgraphic: "navgraphics/energyconsumption.png", catagory_id: catagory.id, video: "EPDesign.m4v")

catagory = Catagory.create(name:"Energy", navgraphic: "navgraphics/energy.png", headergraphic: "energy", color: "energy", keypoints: "this is a key point")


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "first", main_idea:"Energy is the capacity to do work", header:"Energy is the <span class='accent1'>capacity</span> to do <span class='accent1'>work</span>", section_image: "section_images/mag_flashlight_with_d_batteries.png", image_position: "imagerightmedium", content: "What does that mean? Well, think about a flashlight. Flashlights use batteries as an energy, or power, source. When you switch on the flashlight, the light comes on. The batteries in your flashlight have the capacity – or ability – to do the work of powering your flashlight. The energy stored in batteries is a form of chemical energy. The energy is provided by a chemical reaction. <br><br> Capacity is also how much work something can do. For example, two D-cell batteries might be able to power a large flashlight, but not an entire home.  Even for the flashlight, those D-cell batteries won’t last forever. Eventually the batteries will be drained and will need to be replaced. The energy capacity of a battery is limited.")


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "second", main_idea:"People get energy from food; we measure the energy provided by food in calories", header:"<span class='accent1'>People</span> get energy from <span class='accent1'>food</span>; we measure the energy provided by food in <span class='accent1'>calories</span>", section_image: "section_images/plate_with_food_gauge.jpg", image_position: "imagerightmedium", content: "Did your parents, or coaches, or teachers ever tell you that &quot;Food is fuel&quot;? Our bodies get energy from food, and the energy we get is measured in calories. A calorie is a unit of energy. (What food labels call a &quot;calorie&quot; is actually 1,000 calories as scientists define a calorie. Bet you didn't know you're eating around 2,000,000 calories a day!) The scientific definition of one calorie is the amount of energy required to increase the temperature of one gram of water (a small amount) one degree Celsius (another small amount). Food really is fuel! ")


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "third", main_idea:"We use energy to power our world", header:"We use energy to <span class='accent1'>power</span> our <span class='accent1'>world</span>", section_image: "section_images/electricity_to_your_home.png", image_position: "imageleftlarge", content: "A hundred years ago, people didn’t have televisions, cell phones, or microwaves. But, today, we are surrounded by these machines in the developed world. We have to provide energy to power those devices just like we need energy – calories from food – to power our bodies. If &quot;food is fuel&quot; for our bodies, what’s the source of power for our modern devices?<br><br>Many of the household devices we own are powered by electricity. You plug a cord into the wall – for example, for a toaster – which uses the electricity provided to your house to power whatever you plugged in. That’s how we power toasters, microwaves, televisions, blenders, mixers, and other household appliances. We don’t normally think about where the energy comes from when we plug them in, but they get their energy from the “electric grid.” When you drive around town, you probably see power lines that deliver that electricity from the grid to businesses, homes, schools, hospitals, and other places. The electric grid is the way that we connect energy sources – which we will cover in the next section – with places that need energy, like houses and businesses.<br><br>Not everything is powered by plugging a power cord into the wall. Lots of things we use everyday use batteries as an energy source. Cars use batteries, too, and non-electric cars also burn gasoline for power (electric cars do plug in to a wall socket to recharge).
")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fourth", main_idea:"Energy sources are all around us, both renewable and non-renewable", header:"Energy sources are all around us, both <span class='accent1'>renewable</span> and <span class='accent1'>non-renewable</span> ", section_image: "section_images/energy_sources.png", image_position: "imagerightlarge", content: "There are a variety of ways that we generate energy to power our modern world, many of which people have used for hundreds or even thousands of years. Some of these are considered renewable, like wind and sunlight, which means that we are not in danger of running out of them. Some of these are being consumed faster than they are being created, such as coal, which means that we will some day run out of that energy source.<br><br>Non-renewable energy sources include coal, petroleum, and natural gas. These three energy sources are called “fossil fuels” because they are created by ancient living things, like plants and animals, that were buried in the ground millions of years ago. Because it takes millions of years to create coal or petroleum, we use them up much faster than new coal or petroleum is created. That’s why they are called “non-renewable”. We extract energy from fossil fuels by burning them, such as burning gas to run a car or burning coal to generate electricty at a power plant.<br><br> Renewable energy sources include wind, sunlight, and water. Solar Power uses the power of the sun's light to create electricity.  Hydroelectric Power refers to making electricity from the power of water in motion. For example, water flowing over a man-made dam falls downward due to the force of gravity (the same reason a ball falls down if you throw it in the air). The power in this falling water can be used to turn turbines at the bottom, which can generate electricity through a process called electromagnetic induction.")
