# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



#### Everything for Machines

catagory = FactoryGirl.create(:catagory, name:"Machines", navgraphic: "navgraphics/machines.png", headergraphic: "machines", color: "machines")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "first", main_idea:"A machine is something with one or more parts that uses energy to do a job", header:"A machine is something with one or more <span class='accent1'>parts</span> that uses <span class='accent1'>energy</span> to do a job", section_image: "section_images/different-machines.png", image_position: "imagerightlarge", content: "You know that a bicycle or a car is a machine, but did you know that a doorknob is also a machine?  A machine is something with one or more parts that uses energy to do a job. Machines include tools like scissors, hammers, and flashlights. Machines also include vehicles like bicycles, cars, and planes, and appliances like refrigerators, washing machines, and microwaves. Electronic devices such as televisions, computers, tablets, and smart phones are also machines. There are machines that do almost any kind of work you can think of, but they all have at least one part and use energy to get something done.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "second", main_idea:"Simple Machines have few parts and make work easier", header:"<span class='accent1'>Simple Machines</span> have <span class='accent1'>few parts</span> and make <span class='accent1'>work easier</span>", section_image: "section_images/moving_van_with_ramp.jpg", image_position: "imageleftlarge", content: "Simple machines are a special class of machines, typically with only one or two parts. There are six types of simple machines:  levers, pulleys, wheels and axels, screws, wedges, and inclined planes.  Some examples of simple machines include doorknobs, ramps, and knives. Simple machines make work easier. In our everyday lives, we use the word work to describe many different efforts. In engineering and science, the mechanical definition of work is: work = force x distance. <br><br> A force is a push or pull. Doing mechanical work means that you are pushing or pulling something, which is another way of saying you are moving it. With a simple machine, you can apply a smaller force over a longer distance to do the same amount of work as a big force over a short distance.  <br><br> To think about how this works, picture a moving truck. If a mover has to lift a heavy box up into the truck, she has to use a lot of strength to lift it straight up. If she uses a ramp (an inclined plane) to roll the box into the truck, she can use less strength over a longer distance. The mover is doing the same amount of work—getting the box into the truck—but it is a lot easier to use the ramp, because it requires less force. ")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "third", main_idea:"Most machines are a combination of parts, which work together to get the job done", header:"Most machines are a <span class='accent1'>combination of parts</span>, which work together to get the job done", section_image: "section_images/parts_of_a_car.jpg", image_position: "imagerightlarge", content: "Simple machines can be parts for more complex machines. For example, any machine that has wheels—like a bicycle, car or wheel barrel—has wheels and axels. Anything that cuts—like a lawn mower or a blender—has a wedge. However, most machines are more than just combinations of simple machines. <br><br> The different parts a machine requires depends on the job the machine will do. Machines that have parts that rub against each other or against the ground need parts like wheels and ball bearings that reduce the friction created when two objects rub against each other. Machines that are meant to travel quickly have parts that reduce drag, which is the resistance created by air or water.  Machines that people ride in or on have parts that provide comfort, such as the seat of a bicycle or the cup holders in a car.  <br><br> Most machines also include structural parts like the frame of a car or bicycle. The structural parts of a machine are designed to support the weight of the machine. If the machine has users, like a car, the structure of the car is also designed to protect the people inside if the machine is in an accident. Engineers work to improve the design and materials used to create machine parts to make them safer, last longer, and more energy efficient.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fourth", main_idea:"Most machines in the modern world get their energy from fossil fuels, electricity, or people power", header:"Most machines in the modern world get their <span class='accent1'>energy</span> from <span class='accent1'>fossil fuels, electricity, or people power</span>", section_image: "section_images/energy_sources_for_machines.png", image_position: "imagerightmedium", content: "There are a lot of different machines, but only a handful of ways to power them.  Most machines in the modern world are powered by fossil fuels, electricity, or people power. To get power from a fossil fuel, like coal or gas, you have to burn it. If you want to convert that energy into motion, you need an engine. Engines turn the potential energy in fossil fuels into motion. For example, when a car engine burns gasoline, it releases a huge amount of energy. That energy is used to create motion in the car, which is channeled to the axles, which spin the wheels. Not all machines that use fossil fuels have parts that move. For example, a gas stove used for cooking does not require any moving parts to do its job. <br><br>  Electricity is another modern power source for machines. Machines usually get electricity either from being plugged into an electrical outlet or from batteries. You can learn how electricity is generated in the Energy section of this website. When you turn an electrically powered machine on, you are closing an electrical circuit.  When an electrical circuit is closed, it creates a flow of electrical energy. We call this flow of energy a 'current'. This electrical energy can be used to power many things like flashlights and televisions.  For machines with moving parts, a motor can be used to turn electrical energy into motion. Some examples of machines with motors include fans, blenders, and electric cars. <br><br> People are still an important source of energy for many machines. From simple machines like doorknobs to bicycles and skateboards, our world would not be complete without people power.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fifth", main_idea:"Electronic machines can be programmed to follow instructions",  header:"<span class='accent1'>Electronic machines</span> can be <span class='accent1'>programmed</span> to follow instructions", content:'An electronic machine is still a machine with parts that uses energy to do a job. What makes electronic machines different is that they have some logic implemented inside, which means that they can be programmed with instructions. Think of a DVR that is programmed to record every episode of a favorite television show. Somewhere in that machine is logic, which tells the machine that "if it is time for favorite show, start recording.” There is also logic that says, "If the end time for the favorite show has now been reached, stop recording." Electronic machines have computer chips inside that allow them to respond to instructions. Examples of electronic machines include computers, smartphones, and printers.')


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "sixth", main_idea:"Machines allow us to do work faster and easier, and allow us do things we could not do without them", header:"Machines allow us to do <span class='accent1'>work faster and easier</span>, and allow us do things we could <span class='accent1'>not do without them</span>", section_image: "section_images/smart_phones_and_tablets.jpg", image_position: "imageleftlarge",content:'Machines allow us to do things much faster and easier than we could do without them. All the vehicles in our world help us get places faster, even machines we power ourselves like skateboards and bicycles. Getting a ride in a car to school is usually a lot faster than walking (unless there is a lot of trafffic!). It is also much faster and easier to make a smoothie with a blender, than to try to make one by hand. <br><br>Modern machines also allow us to do things we could never do without them. There is no way to take a picture or watch a movie without a machine. Now we can do both using a pocket-sized computer called a smartphone. Engineers help to create the machines that have changed and will continue to change our world.')

topic = FactoryGirl.create(:topic, name:"simple machines",  navgraphic: "navgraphics/simplemachines.png", catagory_id: catagory.id)

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Simple machines are a special class of machines, typically with only one or two parts", header:"<span class='accent1'>Simple machines</span> are a <span class='accent1'>special class</span> of machines, typically with only one or two parts", content:"There are two families of simple machines: the lever family and the wedge family.  Simple machines in the lever family include levers, wheels and axles, and pulleys. Simple machines in the wedge family include wedges, inclined planes, and screws. The Greek scientist Archimedes originally made these classifications, over 2,000 years ago.  Modern day machines are more complex and consist of many things other than just simple machines.  However, simple machines are still very important to engineering and are widely used today.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"Simple machines make work easier", header:"Simple machines make <span class='accent1'>work easier</span>", content:"In our everyday lives, we use the word work to describe many different efforts. In engineering and science, the mechanical definition of work is:  <br><br> <div class='txtcenter'>Work (W) = Force (F) * Distance (d) </div> <br><br> The way you read this equation is, “Work is equal to force over a distance”. A force is a push or a pull. Doing mechanical work means that you are pushing or pulling something, which is another way of saying you are moving it. This equation captures the idea that you can move an object in different ways. You can use a greater force over a shorter distance. Or, you can use a smaller force over a longer distance. Simple machines let you change either the direction or amount of the force (or both) in the work equation. <br><br> The amount of force you apply to a simple machine compared to the amount of force produced by the machine is called mechanical advantage. Mechanical advantage is not always about getting more force out of a machine. The “advantage” exists because whether the machine requires more or less force than it produces, it makes the work at hand easier to complete. ")


section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"Machines in the lever family all use rotation to create mechanical advantage", header:"Machines in the <span class='accent1'>lever family</span> all use <span class='accent1'>rotation</span> to create mechanical advantage", content:"All of the simple machines in the lever family use some kind of rotation, or turning motion, around a point that supports the weight of the machine. The simple machines in the lever family are levers, wheels and axles, and pulleys. <br><br> The first simple machine in the lever family is the lever itself. A lever is used to move something, which is referred to as a load, using a pivot force. A lever consists of two parts, a bar that does the turning and a fulcrum, which is the point that supports the weight of the lever and the point on which it turns. You can use a long lever to lift a heavy load with a little amount of force, like lifting someone older and heavier than you on a seesaw. Or you can use a lever to create a great amount of force over a short distance, like using a hammer to pound a nail into piece of wood. <br><br> The second simple machine in the lever family is the wheel and axle. An axle is a long stick that attaches to the middle of the wheel.  A wheel and axle can be used to make spinning the axle easier by increasing the size of the wheel. By increasing the size of the wheel, it is easier for the person applying the force to the wheel to make the wheel spin.  This, in turn, makes the axle easier to spin. An example of a wheel and axle system is a doorknob.  It is much easier to open a door with a doorknob than a stick coming out the door.  Using a doorknob allows you to use a smaller amount of effort over a longer distance to open the door more easily. The wheel and axle on a car is also a type of wheel and axle system, but it works the opposite way a doorknob does. In the case of a car, the axle turns the wheel. The axle is a much smaller in size than the wheel, so the car needs a large amount of force, which it gets from the gas or electricity the car uses, to turn the axle, which then turns the wheel. <br><br> The last simple machine in the lever family is the pulley. The goal of a pulley is to raise, lower, or move a load horizontally, or side-to-side.  Pulleys are made up of ropes and axles.  The greater the number of ropes in a pulley, the greater the mechanical advantage provided by the pulley. Pulleys are typically used to lift heavy items. For example, pulleys are often used in elevators, creating the lift force to allow it to move up and down. Pulleys are also used in cranes to move containers on or off ships and to lift construction materials at building sites. ")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"Machines in the wedge family use an angled surface to create mechanical advantage", header:"Machines in the <span class='accent1'>wedge family</span> use an <span class='accent1'>angled surface</span> to create mechanical advantage", content:"All of the simple machines in the wedge family use an angled surface to make work easier. The simple machines in the wedge family are wedges, inclined planes, and screws. <br><br> The first simple machine in the wedge family is the wedge itself. One use of a wedge is to cut apart another object.  Wedges use the point of an angled edge to separate the object when a force is applied to the opposite, or flat, side of the wedge. For example, think of cutting a sandwich with a knife. The sharp edge of the knife is the wedge, and you press that sharp edge down to cut.  If you’ve ever tried to cut your food with the flat side of a knife, you know how much easier it is to use the wedge side. Another use for a wedge is to lift something slightly off the ground. For example, the ends of the forks on forklift machine are wedges, which allow the operator to push the forks under a heavy load to lift it off the ground. <br><br> The next member of the wedge family is the inclined plane. Inclined planes are used to get something to a higher height with less effort.  This is done by increasing the distance the object is moved to get it to the new height.  Instead of having to lift the object directly up, a person can push the object over a longer distance to get it to  the new height.  An example of an inclined plane is a ramp. It is much easier to roll a heavy box up a ramp than it is to lift it straight up. <br><br> The last member of the wedge family is the screw.  Now, it might be harder to think of how a screw uses an angled surface, but it does too!  Think about the curved ridge, or the thread, that wraps around the outside of a screw.  If you were able to unwind that thread from the screw, you would have an inclined plane.  Basically, a screw is just an inclined plane wrapped around a cylinder or a cone, depending on the type of screw. The screw uses the thread to change a twisting motion into a linear motion. Screws are believed to be the last simple machine that was created.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"By combining simple machines, you create a compound machine", header:"By <span class='accent1'>combining</span> simple machines, you create a <span class='accent1'>compound machine</span>", content:"Simple machines are the building blocks of more complex machines.  By using many simple machines in a compound machine, you can get an even better mechanical advantage.  Compound machines can also accomplish more than a simple machine can on its own.  A bicycle is a good example of a compound machine.  It combines a pulley system of the bike chain with a wheel and axle simple machine in order to create the forward motion of the bike.")

topic = FactoryGirl.create(:topic, name:"parts",  navgraphic: "navgraphics/parts.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"motorsandengines",  navgraphic: "navgraphics/motorsandengines.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"resistanceandfriction",  navgraphic: "navgraphics/resistanceandfriction.png", catagory_id: catagory.id, available: "no")
#topic = FactoryGirl.create(:topic, name:"energy",  navgraphic: "navgraphics/machines-energy.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"electronicmachinesandmotors",  navgraphic: "navgraphics/electronicmachines.png", catagory_id: catagory.id, available: "no")
#topic = FactoryGirl.create(:topic, name:"bikesandcars",  navgraphic: "navgraphics/bikesandcars.png", catagory_id: catagory.id, available: "no")






#topic = FactoryGirl.create(:topic, name:"simple machines", navgraphic: "navgraphics/machinessimplemachines.png", catagory_id: catagory.id, video: "EPDesign.m4v", keypoints: "a simple machine is...")
#topic = FactoryGirl.create(:topic, name:"gears",  navgraphic: "navgraphics/gears.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"motors",  navgraphic: "navgraphics/machinesmotors.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"engines",  navgraphic: "navgraphics/machinesengines.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"electronics",  navgraphic: "navgraphics/machineselectronics.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"robotics",  navgraphic: "navgraphics/machinesrobotics.png", catagory_id: catagory.id, video: "EPDesign.m4v")
