# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



#### Everything for Machines

catagory = FactoryGirl.create(:catagory, name:"Machines", navgraphic: "navgraphics/machines.png", headergraphic: "machines", color: "machines", video:"//www.youtube.com/embed/te50y1zvi9M")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "first", main_idea:"A machine is something with one or more parts that uses energy to do a job", header:"A machine is something with one or more <span class='accent1'>parts</span> that uses <span class='accent1'>energy</span> to do a job", section_image: "section_images/different-machines.png", image_position: "imagerightlarge", content: "You know that a bicycle or a car is a machine, but did you know that a doorknob is also a machine?  A machine is something with one or more parts that uses energy to do a job. Machines include tools like scissors, hammers, and flashlights. Machines also include vehicles like bicycles, cars, and planes, and appliances like refrigerators, washing machines, and microwaves. Electronic devices such as televisions, computers, tablets, and smart phones are also machines. There are machines that do almost any kind of work you can think of, but they all have at least one part and use energy to get something done.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "second", main_idea:"Simple Machines have few parts and make work easier", header:"<span class='accent1'>Simple Machines</span> have <span class='accent1'>few parts</span> and make <span class='accent1'>work easier</span>", section_image: "section_images/moving_van_with_ramp.jpg", image_position: "imageleftlarge", content: "Simple machines are a special class of machines, typically with only one or two parts. There are six types of simple machines:  levers, pulleys, wheels and axels, screws, wedges, and inclined planes.  Some examples of simple machines include doorknobs, ramps, and knives. Simple machines make work easier. In our everyday lives, we use the word work to describe many different efforts. In engineering and science, the mechanical definition of work is: work = force x distance. <br><br> A force is a push or pull. Doing mechanical work means that you are pushing or pulling something, which is another way of saying you are moving it. With a simple machine, you can apply a smaller force over a longer distance to do the same amount of work as a big force over a short distance.  <br><br> To think about how this works, picture a moving truck. If a mover has to lift a heavy box up into the truck, she has to use a lot of strength to lift it straight up. If she uses a ramp (an inclined plane) to roll the box into the truck, she can use less strength over a longer distance. The mover is doing the same amount of work—getting the box into the truck—but it is a lot easier to use the ramp, because it requires less force. ")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "third", main_idea:"Most machines are a combination of parts, which work together to get the job done", header:"Most machines are a <span class='accent1'>combination of parts</span>, which work together to get the job done", section_image: "section_images/parts_of_a_car.jpg", image_position: "imagerightlarge", content: "Simple machines can be parts for more complex machines. For example, any machine that has wheels—like a bicycle, car or wheel barrel—has wheels and axels. Anything that cuts—like a lawn mower or a blender—has a wedge. However, most machines are more than just combinations of simple machines. <br><br> The different parts a machine requires depends on the job the machine will do. Machines that have parts that rub against each other or against the ground need parts like wheels and ball bearings that reduce the friction created when two objects rub against each other. Machines that are meant to travel quickly have parts that reduce drag, which is the resistance created by air or water.  Machines that people ride in or on have parts that provide comfort, such as the seat of a bicycle or the cup holders in a car.  <br><br> Most machines also include structural parts like the frame of a car or bicycle. The structural parts of a machine are designed to support the weight of the machine. If the machine has users, like a car, the structure of the car is also designed to protect the people inside if the machine is in an accident. Engineers work to improve the design and materials used to create machine parts to make them safer, last longer, and more energy efficient.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fourth", main_idea:"Most machines in the modern world get their energy from fossil fuels, electricity, or people power", header:"Most machines in the modern world get their <span class='accent1'>energy</span> from <span class='accent1'>fossil fuels, electricity, or people power</span>", section_image: "section_images/energy_sources_for_machines.png", image_position: "imagerightmedium", content: "There are a lot of different machines, but only a handful of ways to power them.  Most machines in the modern world are powered by fossil fuels, electricity, or people power. To get power from a fossil fuel, like coal or gas, you have to burn it. If you want to convert that energy into motion, you need an engine. Engines turn the potential energy in fossil fuels into motion. For example, when a car engine burns gasoline, it releases a huge amount of energy. That energy is used to create motion in the car, which is channeled to the axles, which spin the wheels. Not all machines that use fossil fuels have parts that move. For example, a gas stove used for cooking does not require any moving parts to do its job. <br><br>  Electricity is another modern power source for machines. Machines usually get electricity either from being plugged into an electrical outlet or from batteries. You can learn how electricity is generated in the Energy section of this website. When you turn an electrically powered machine on, you are closing an electrical circuit.  When an electrical circuit is closed, it creates a flow of electrical energy. We call this flow of energy a 'current'. This electrical energy can be used to power many things like flashlights and televisions.  For machines with moving parts, a motor can be used to turn electrical energy into motion. Some examples of machines with motors include fans, blenders, and electric cars. <br><br> People are still an important source of energy for many machines. From simple machines like doorknobs to bicycles and skateboards, our world would not be complete without people power.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fifth", main_idea:"Electronic machines can be programmed to follow instructions",  header:"<span class='accent1'>Electronic machines</span> can be <span class='accent1'>programmed</span> to follow instructions", content:'An electronic machine is still a machine with parts that uses energy to do a job. What makes electronic machines different is that they have some logic implemented inside, which means that they can be programmed with instructions. Think of a DVR that is programmed to record every episode of a favorite television show. Somewhere in that machine is logic, which tells the machine that "if it is time for favorite show, start recording.” There is also logic that says, "If the end time for the favorite show has now been reached, stop recording." Electronic machines have computer chips inside that allow them to respond to instructions. Examples of electronic machines include computers, smartphones, and printers.')


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "sixth", main_idea:"Machines allow us to do work faster and easier, and allow us do things we could not do without them", header:"Machines allow us to do <span class='accent1'>work faster and easier</span>, and allow us do things we could <span class='accent1'>not do without them</span>", section_image: "section_images/smart_phones_and_tablets.jpg", image_position: "imageleftlarge",content:'Machines allow us to do things much faster and easier than we could do without them. All the vehicles in our world help us get places faster, even machines we power ourselves like skateboards and bicycles. Getting a ride in a car to school is usually a lot faster than walking (unless there is a lot of trafffic!). It is also much faster and easier to make a smoothie with a blender, than to try to make one by hand. <br><br>Modern machines also allow us to do things we could never do without them. There is no way to take a picture or watch a movie without a machine. Now we can do both using a pocket-sized computer called a smartphone. Engineers help to create the machines that have changed and will continue to change our world.')


question = Question.create(catagory_id: catagory.id, question_num: "1", question_content: "What is a machine?", question_image: "section_images/different-machines.png",explanation: "Machines include tools like scissors, hammers, and flashlights. Machines also include vehicles like bicycles, cars, and planes, and appliances like refrigerators, washing machines, and microwaves. A doorknob is also a machine.  Electronic devices such as televisions, computers, tablets, and smart phones are also machines. There are machines that do almost any kind of work you can think of, but they all have at least one part and use energy to get something done.	")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Something you eat for breakfast")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A thing with one or more parts that uses energy to do a job", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Someone with a lot of energy")

question = Question.create(catagory_id: catagory.id, question_num: "2", question_content: "Which of the following are examples of simple machines?", question_image: "section_images/moving_van_with_ramp.jpg",explanation: "Simple machines are a special class of machines, typically with only one or two parts. There are six types of simple machines: levers, pulleys, wheels and axels, screws, wedges, and inclined planes. Some examples of simple machines include doorknobs, ramps, and knives. Simple machines make work easier. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "A lever, an apple, and a raisin")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A lever, a pulley, and an inclined plane", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "A screw, a car, and a bicycle")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "A computer, a pulley, and a grapefruit")

question = Question.create(catagory_id: catagory.id, question_num: "3", question_content: "Which of the following are possible power sources for a machine?", question_image: "section_images/energy_sources_for_machines.png",explanation: "There are a lot of different machines, but only a handful of ways to power them. Most machines in the modern world are powered by fossil fuels, electricity, or people power. People are still an important source of energy for many machines. From simple machines like doorknobs to bicycles and skateboards, our world would not be complete without people power.	")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Just electricity")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Just electricity and natural gas")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Electricity, natural gas, coal, and human energy could all be power sources for a machine", correct: "true")


topic = FactoryGirl.create(:topic, name:"simple machines",  navgraphic: "navgraphics/simplemachines.png", catagory_id: catagory.id)

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Simple machines are a special class of machines, typically with only one or two parts", header:"<span class='accent1'>Simple machines</span> are a <span class='accent1'>special class</span> of machines, typically with only one or two parts", content:"There are two families of simple machines: the lever family and the wedge family.  Simple machines in the lever family include levers, wheels and axles, and pulleys. Simple machines in the wedge family include wedges, inclined planes, and screws. The Greek scientist Archimedes originally made these classifications, over 2,000 years ago.  Modern day machines are more complex and consist of many things other than just simple machines.  However, simple machines are still very important to engineering and are widely used today.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"Simple machines make work easier", header:"Simple machines make <span class='accent1'>work easier</span>", content:"In our everyday lives, we use the word work to describe many different efforts. In engineering and science, the mechanical definition of work is:  <br><br> <div class='txtcenter'>Work (W) = Force (F) * Distance (d) </div> <br><br> The way you read this equation is, “Work is equal to force over a distance”. A force is a push or a pull. Doing mechanical work means that you are pushing or pulling something, which is another way of saying you are moving it. This equation captures the idea that you can move an object in different ways. You can use a greater force over a shorter distance. Or, you can use a smaller force over a longer distance. Simple machines let you change either the direction or amount of the force (or both) in the work equation. <br><br> The amount of force you apply to a simple machine compared to the amount of force produced by the machine is called mechanical advantage. Mechanical advantage is not always about getting more force out of a machine. The “advantage” exists because whether the machine requires more or less force than it produces, it makes the work at hand easier to complete. ")


section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"Machines in the lever family all use rotation to create mechanical advantage", header:"Machines in the <span class='accent1'>lever family</span> all use <span class='accent1'>rotation</span> to create mechanical advantage", content:"All of the simple machines in the lever family use some kind of rotation, or turning motion, around a point that supports the weight of the machine. The simple machines in the lever family are levers, wheels and axles, and pulleys. <br><br> The first simple machine in the lever family is the lever itself. A lever is used to move something, which is referred to as a load, using a pivot force. A lever consists of two parts, a bar that does the turning and a fulcrum, which is the point that supports the weight of the lever and the point on which it turns. You can use a long lever to lift a heavy load with a little amount of force, like lifting someone older and heavier than you on a seesaw. Or you can use a lever to create a great amount of force over a short distance, like using a hammer to pound a nail into piece of wood. <br><br> The second simple machine in the lever family is the wheel and axle. An axle is a long stick that attaches to the middle of the wheel.  A wheel and axle can be used to make spinning the axle easier by increasing the size of the wheel. By increasing the size of the wheel, it is easier for the person applying the force to the wheel to make the wheel spin.  This, in turn, makes the axle easier to spin. An example of a wheel and axle system is a doorknob.  It is much easier to open a door with a doorknob than a stick coming out the door.  Using a doorknob allows you to use a smaller amount of effort over a longer distance to open the door more easily. The wheel and axle on a car is also a type of wheel and axle system, but it works the opposite way a doorknob does. In the case of a car, the axle turns the wheel. The axle is a much smaller in size than the wheel, so the car needs a large amount of force, which it gets from the gas or electricity the car uses, to turn the axle, which then turns the wheel. <br><br> The last simple machine in the lever family is the pulley. The goal of a pulley is to raise, lower, or move a load horizontally, or side-to-side.  Pulleys are made up of ropes and axles.  The greater the number of ropes in a pulley, the greater the mechanical advantage provided by the pulley. Pulleys are typically used to lift heavy items. For example, pulleys are often used in elevators, creating the lift force to allow it to move up and down. Pulleys are also used in cranes to move containers on or off ships and to lift construction materials at building sites. ")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"Machines in the wedge family use an angled surface to create mechanical advantage", header:"Machines in the <span class='accent1'>wedge family</span> use an <span class='accent1'>angled surface</span> to create mechanical advantage", content:"All of the simple machines in the wedge family use an angled surface to make work easier. The simple machines in the wedge family are wedges, inclined planes, and screws. <br><br> The first simple machine in the wedge family is the wedge itself. One use of a wedge is to cut apart another object.  Wedges use the point of an angled edge to separate the object when a force is applied to the opposite, or flat, side of the wedge. For example, think of cutting a sandwich with a knife. The sharp edge of the knife is the wedge, and you press that sharp edge down to cut.  If you’ve ever tried to cut your food with the flat side of a knife, you know how much easier it is to use the wedge side. Another use for a wedge is to lift something slightly off the ground. For example, the ends of the forks on forklift machine are wedges, which allow the operator to push the forks under a heavy load to lift it off the ground. <br><br> The next member of the wedge family is the inclined plane. Inclined planes are used to get something to a higher height with less effort.  This is done by increasing the distance the object is moved to get it to the new height.  Instead of having to lift the object directly up, a person can push the object over a longer distance to get it to  the new height.  An example of an inclined plane is a ramp. It is much easier to roll a heavy box up a ramp than it is to lift it straight up. <br><br> The last member of the wedge family is the screw.  Now, it might be harder to think of how a screw uses an angled surface, but it does too!  Think about the curved ridge, or the thread, that wraps around the outside of a screw.  If you were able to unwind that thread from the screw, you would have an inclined plane.  Basically, a screw is just an inclined plane wrapped around a cylinder or a cone, depending on the type of screw. The screw uses the thread to change a twisting motion into a linear motion. Screws are believed to be the last simple machine that was created.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"By combining simple machines, you create a compound machine", header:"By <span class='accent1'>combining</span> simple machines, you create a <span class='accent1'>compound machine</span>", content:"Simple machines are the building blocks of more complex machines.  By using many simple machines in a compound machine, you can get an even better mechanical advantage.  Compound machines can also accomplish more than a simple machine can on its own.  A bicycle is a good example of a compound machine.  It combines a pulley system of the bike chain with a wheel and axle simple machine in order to create the forward motion of the bike.")


topic = FactoryGirl.create(:topic, name:"motorsandengines",  navgraphic: "navgraphics/motorsandengines.png", catagory_id: catagory.id)

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Motors and engines change energy into useful motion", header:"Motors and engines <span class='accent1'>change energy</span> into useful <span class='accent1'>motion</span>", section_image: "section_images/DC_motors_172906946.jpg", image_position: "imagerightsmall", content:"Bikes get power from you pedaling and using your effort to make it go. Windmills turn because the force of wind pushes them. Horse drawn carriages move because horses pull them. Waterwheels turn from the force of a river or stream flowing. However, how do things move that don’t have  humans or nature putting energy into moving them?  This is the purpose of engines and motors. <br><br>
Engines and motors are machines that change energy into useful motion. An energy source, like fuel, is put into the engine and is turned into this motion.  Engines and motors allow us to create machines that can run without constant supervision and without humans or nature directly moving the parts of the machine. Although the words engine and motor are often used interchangeably, the word “engine” originally referred to any type of machine that converted any source of energy or fuel into a force, while a “motor” was anything that created motion. Now, we use the word engine to refer to a machine that burns fuel to create motion, while a motor runs on energy sources like electricity and pressurized water that do not get chemically changed when used.
")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"Motors and engines are organized based on the type of energy they use to make motion", header:"Motors and engines are <span class='accent1'>organized</span> based on the <span class='accent1'>type of energy</span> they use to make motion", section_image: "section_images/powertools.png", image_position: "imagerightmedium", content:"Different types of motors and engines get power from different types of energy.  There are many types of engines that all use different kinds of energy, but some common ones are heat engines, hydraulic motors, pneumatic motors, and electric motors. Heat engines use the burning of fuel to power the motor and make movement. They can be found in cars, planes, and trains. Hydraulic motors are machines that use tightly pressurized, or tightly squeezed, liquids to make motion. They are mainly used in large equipment like cranes and construction diggers. Pneumatic motors use pressurized air to create motion.  They are now being used in roller coaster launch systems and hand-held tools. Electric motors use electricity from things like a battery or a wall plug to power the engine. They can be found in household appliances and power tools.<br><br>
The kinds of engines you are likely to come across in everyday life are heat engines and electric motors and are talked about below.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"Heat engines burn fuel to create movement", header:"Heat engines <span class='accent1'>burn fuel</span> to create movement ", section_image: "section_images/pistons_126737180.jpg", image_position: "imagerightsmall", content:"Heat engines burn fuel to create heat to get power. This is because to get power from a fossil fuel, like coal or gas, you have to burn it. Engines turn the potential, or stored, energy in fossil fuels into motion through controlling this burn. Heat engines are what you will find in most kinds of transportation like cars, planes, trains, and rockets. Within cars and rockets they are called “internal combustion engines”, while planes use engines called turbines. <br><br>

When a car engine burns gas, it releases a huge amount of energy inside of pistons, which are cylinders with parts that move up and down inside of them. That energy is used to create motion in the car, which is guided to the axles, the part of the car that spins the wheels. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"Heat engines create movement in a four-step process: Suck, Squeeze, Bang, and Blow", header:"Heat engines create movement in a four-step process: <span class='accent1'>Suck</span>, <span class='accent1'>Squeeze</span>, <span class='accent1'>Bang</span>, and <span class='accent1'>Blow</span>", content:"There are four steps in the process to turn the fuel into movement which can best be remembered by these four words: Suck, Squeeze, Bang, and Blow.  <br><br>
<b>Suck:</b> The fuel mixed with air is forced into a cylinder in the engine when the piston goes down. <br><br>
<b>Squeeze:</b> No more fuel is allowed to enter the cylinder and the piston goes up, making the space the fuel and air mixture has in the cylinder much smaller. <br><br>
<b>Bang:</b> At this point a spark plug is set off, igniting the fuel and air mixture. This is where the energy is changing forms and movement is being created. This forces the piston back down. The forcing of the piston back down is the transfer of the energy from the fuel to the car. This piston movement turns the drive shaft of the car. A drive shaft is a part of a car that carries the power to the wheels and makes them turn. <br><br>
<b>Blow:</b> At the piston goes back to the top of the cylinder, the exhaust is opened and the spent fuel and air mixture exits the engine.
Another type of heat engine is a steam engine. Steam engines were the first type of major engine to see a large amount of use and helped to advance the modern world to how it is today. Steam engines also use a piston system, but boil water and use steam to power the engine’s pistons instead of a fuel and air mixture.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"Electric motors change electricity into movement", header:"Electric motors <span class='accent1'>change electricity</span> into movement", content:"Electricity is used to power electric motors.  There are two kinds of electric motors, AC and DC motors.  AC motors are powered by AC (alternating current) electric sources like wall plugs. DC motors are powered by DC (direct current) sources like batteries.<br><br>
Electric motors often use magnetic fields and wire to change the power into motion. A loop of wire is created and put between a north magnetic pole and a south magnetic pole. When a current is run through a magnetic field, a force is created.  Therefore, current is then run through the wire loop, generating force. This makes each side of the loop repel the magnets in opposite directions.  This movement makes the loop rotate and creates motion.<br><br>Electric motors are used in power tools like drills and saws and wall as household appliances like washers and blenders.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"Motors are judged by their efficiency", header:"Motors are judged by their <span class='accent1'>efficiency</span>", content:"Efficiency measures how much energy the engine makes compared to the highest amount of energy the fuel could produce. To know how well a motor works, you must look at its efficiency value.  <br><br>
If a motor has a high efficiency, the amount of energy that can be used for work is close to the amount in the fuel. This is a well working motor.  A motor with low efficiency wastes energy that can be put to better use. Low efficiency motors lose energy through things like heat, friction, sound, and poorly-designed or -fitting parts. These motors are not as well working.<br><br>The goal of engineers is to make engines with a higher efficiency.  These engines are also cost less to run since they use less fuel to do the same task.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"sixth", main_idea:"The first engineers were people that worked on engines", header:"The first <span class='accent1'>engineers</span> were people that worked on <span class='accent1'>engines</span>", section_image: "section_images/catapult_102170398.jpg", image_position: "imagerightsmall",content:"The word “engineer” actually comes from the word “engine” because they first people ever to be called engineers were people that constructed military engines like catapults in the 1380s. By the 1700s people that worked on constructing actual engines like those described above were referred to as engineers. Therefore, the creation of whole engineering fields started with this one machine. ")


topic = FactoryGirl.create(:topic, name:"friction",  navgraphic: "navgraphics/friction.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Friction is a force that resists motion", header:"<span class='accent1'>Friction</span> is a force that <span class='accent1'>resists motion</span>   ", content:"One important force engineers have to consider when making a machine that either moves or has moving parts is friction. Friction is the force that resists motion.  Friction is caused by solids, liquids, or gases rubbing against each other and creating forces in the opposite direction. <br><br>You might know from personal experience that it is a lot easier to slip and fall when you are skating on ice than when you are walking on grass. It is also much easier to move on a slip-n-slide than on a sidewalk. Smoother and slicker surfaces like ice generate much less friction than rough and dry surfaces like sidewalks.<br><br>There are many different kinds of friction, including static friction, kinetic friction, and fluid resistance.  In science, “fluids” are things that can flow, which include both gases (like air) and liquids (like water). Fluid resistance is also called <i>drag</i>. The forms of friction are grouped by the type of solids, liquids, or gases that are interacting with each other and how they are moving. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"Dry friction occurs between dry solid surfaces", header:"<span class='accent1'>Dry friction</span> occurs between <span class='accent1'>dry solid surfaces</span>", content:"Static friction and kinetic friction are both kinds of dry friction.  Static friction is made between two dry objects that are not yet moving.  When you push a heavy box, but it does not move, you have created static friction.  The static friction between the ground and the box resisted the motion you were trying to cause and made the box stay still.  If you were able to overcome this force and make the box move, it would still feel difficult to keep it moving.  This is because of kinetic friction, the friction between two moving surfaces.  Kinetic friction is always less than static friction.  Therefore, it is easier to keep the box moving than it is to initially push the box. <br><br>Higher amounts of dry friction are created by more weight being pressed into another object. Therefore, the heavier the object, the more friction it creates. You can create additional friction by pushing down hard on an object. The more force pushing the surfaces of the objects together, the greater the friction force becomes.<br><br>Values of dry friction are represented by coefficients of friction. If one object is harder to move than another object of the same weight on the same surface, it is said to have a higher coefficient of friction.  The object that can be moved more easily has a lower coefficient of friction.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"Fluid friction depends on viscosity, which is the thickness of a fluid", header:"<span class='accent1'>Fluid friction</span> depends on <span class='accent1'>viscosity</span>, which is the thickness of a fluid", content:"Viscosity is the density and thickness, of a fluid. The thicker a liquid is, the higher the viscosity and the more friction it creates.  Thicker and more viscous fluids like honey and maple syrup are known for moving slower.  This is a result of fluid friction slowing them down. Water has a lower viscosity and lower fluid friction. That is why it is faster to pour water than it is to pour syrup.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"Fluid resistance is the friction created when objects move through gases and liquids", header:"<span class='accent1'>Fluid resistance</span> is the friction created when objects move through <span class='accent1'>gases and liquids</span>", content:"When an object moves quickly through a gas, like air, or a liquid, like water, the gas or liquid pushes back and creates a resistance, commonly known as <i>drag</i>.  At slow speeds this might not be very noticeable, but as you speed up, it becomes a strong force. Drag is a common problem among fast forms of transportation like cars, trains, boats, planes, rockets, and even bicycles. The higher the amount of drag, the more energy has to be used to make the vehicle move.<br><br>Engineers try to lower the amount of air resistance created by objects by making them more <i>aerodynamic</i>.  This means they shape the object in such a way that it moves through the air more easily. Ways to make something more aerodynamic include minimizing flat surfaces and shaping objects with curves and channels such that they funnel the air around them. Small changes in shape can have large changes in the amount of air resistance they cause. Similarly, engineers design boats to reduce the amount of resistance the boat encounters when moving through the water. Something that is shaped to move through the water efficiently is called <i>hydrodynamic</i>.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"Friction makes machines less efficient", header:"Friction makes machines <span class='accent1'>less efficient</span>", content:"With machines, efficiency is a measure of how well the machine is running. A machine with higher efficiency wastes less energy. Machines that have parts that rub against each other or against the ground need parts like wheels and ball bearings that reduce the friction created when two objects rub against each other. If the amount of friction is high, energy that could be used to power the machine will be wasted trying to overcome this friction. This machine will have a lower efficiency. Engineers can also add things like lubrication to help make parts slide more easily. Lubricants include oil, grease, and water. An example of a lubricant is the water on a slip-n-slide.  The water coating on the slide makes it slicker and lubricated, reducing friction when you go sliding down it.<br><br>One research institute estimates that at least one-third of the energy put into a car is used to overcome friction. Only about 21 percent of all the energy put into the car is actual used to make it move.  The rest of the energy is wasted in friction, heat, and inefficiencies in the car. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"sixth", main_idea:"Friction can be a helpful force", header:"Friction can be a <span class='accent1'>helpful</span> force", content:"Friction does have positive uses! Friction helps to create traction which allows us to walk without immediately falling down. Our shoes have bottoms on them with different patterns of ridges and materials that help create more friction with the ground.  Without friction we would be unable to create the force needed for us to walk.<br><br>Additionally, friction can be used to start a fire.  If you have ever watched any survival shows, you may have seen people rubbing two sticks together to start a fire for themselves.  This is because the rubbing of the sticks together creates friction which in turn creates heat.  If they are able to generate enough friction, a fire can be started.<br><br>Friction also creates forward motion in cars.  As the wheels on a car turn, the rubber material of the tires and the hard asphalt ground create a friction force that moves the car forward. If this friction was not generated, the wheels of the car would spin without moving the car at all. If you have ever seen a car stuck in the snow or mud, the tires may spin around and around and not help the car go anywhere, because the tires cannot get a firm purchase on any solid ground. The goal of tires is to create as much friction with the ground as possible to be able to move the car forward. <br><br>Friction is an important concept in engineering. Friction resists motion and often causes a waste of useful energy. Although it is often something to be overcome in the design of a machine, it can also be helpful in everyday life.")

topic = FactoryGirl.create(:topic, name:"bikesandcars",  navgraphic: "navgraphics/bikesandcars.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Bikes and cars are both machines used to move people", header:"Bikes and cars are both <span class='accent1'>machines</span> used to <span class='accent1'>move people</span>", content:"Two machines we see and use in everyday life are bikes and cars.  Both of these machines are called <i>vehicles</i> because they are used to help move people around. Both bikes and cars use many different machine parts in order to turn their wheels to make the machines, and the people using them, move. Below we will talk about the different <i>parts</i> of these machines and the <i>forces</i> that act on them.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"Bike and cars get their power in different ways", header:"Bike and cars get their  <span class='accent1'>power</span> in different ways", content:"Bikes are a more basic machine than cars because they use <i>human power</i> to create motion. The person riding the bike uses the chemical energy from in their body to move their legs. This chemical energy is created as a result of the food you eat. The leg movement rotates the pedals, which are connected to a set of gears that turn a chain. This chain is connected to the wheels, so that when the chain turns, the wheels turn. <br><br>Car engines are powered by <i>burning gasoline</i>. When a car engine burns gas, it releases a huge amount of energy inside of pistons, which are cylinders with parts inside that move up and down. The energy released is used to create motion in the car, by guiding the energy to the axles, the part of the car that spins the wheels. There are four steps in the process to turn the fuel into movement which can best be remembered by these four words: Suck, Squeeze, Bang, and Blow. To learn more details about this process, check out the Motors and Engines section.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"Many different machine parts are combined to make up bikes and cars", header:"Many different machine <span class='accent1'>parts</span> are combined to make up bikes and cars", content:"Both bikes and cars use parts to help with the steering of the vehicle, turning of the wheels, creating a forward force, and transferring power from the power source to the wheels. Bikes and cars do some of these things differently and some of them the same.<br><br>Bikes steer by having the person riding the bike turn the handlebars. These handlebars are directly connected to the front wheel of the bike.  Therefore, the person riding the bike must move their arms the exact distance that they would like to turn the bike tire.<br><br>Cars steer by using a steering wheel on the inside of the car. Then power steering is used to maximize the force applied by the driver to the wheel.  Power steering makes it easier for the driver to turn the wheel of the car. This way the driver doesn’t have to overcome the full force of the car to be able to turn. The steering wheel is connected to a system that translates the turning motion of the steering wheel to the motion of the tires.<br><br>Both bikes and cars use tires on their wheels to create traction with the ground.  By creating increased traction, they create a greater forward force. These tires are mounted on a simple machine, a wheel and axle, to allow for rotation and maximize the mechanical advantage gained from the system.  Read more about wheel and axles systems in the Simple Machines section. <br><br>Cars also have many other parts incorporated for things like safety, comfort, and ensuring that other parts of the car work correctly. These do not have an impact on the forward motion of the car but are important for making the car work. Some of the safety parts include seat belts, mirrors, and air bags. Some of the parts included for comfort are air conditioning, cushioned seats, and a radio. Some of the parts that monitor other parts of the car include a speedometer, which tracks how fast the car is moving, and the fuel gauge, which tracks how much gasoline is left in the car. You could still have a working car without all of these things, but it would not be as safe or as enjoyable to ride in!  Many engineers work on improving these parts of the car as well as the engine and tires.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"Friction is one of the main forces acting on bikes and cars", header:"<span class='accent1'>Friction</span> is one of the main <span class='accent1'>forces</span> acting on bikes and cars", content:"Friction is what allows bikes and cars to create the traction they need with the ground in order to make a forward force. The greater the friction force on the tires, the less energy that is wasted by the tire spinning without creating forward motion.  Lack of friction becomes a problem for people riding and driving on icy or snowy surfaces.  This is because they are slicker and make it harder to create the needed friction.<br><br>However, friction isn’t always helpful for bikes and cars. Drag is a type of friction that is caused by air rubbing up against the surface of the vehicle. Drag is a common problem among fast forms of transportation like cars, trains, planes, and rockets. The higher the amount of drag, the more energy has to be used to make the vehicle move. Therefore, engineers are working to minimize drag forces on cars by creating more sleeker and aerodynamic shapes. Engineers perform tests to see how to make air flow around the vehicle better. These tests help them fine-tune the shape of the vehicle to reduce drag. You can read more about drag in the Friction section.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"Bikes and cars both transfer energy between many parts to allow for forward motion", header:"Bikes and cars both <span class='accent1'>transfer energy</span> between many parts to allow for <span class='accent1'>forward motion</span>", content:"Bikes use the power of a human to power the bike forward.  A bike does this by transferring the energy that was applied by a person to the pedals to move a chain on the bike.  This chain is connected to the bike wheels that then turn, creating traction with the ground and moving the bike forward.  Handlebars are used to turn the bike.<br><br>Cars use the power created by a heat engine to move pistons.  These pistons then turn a drive shaft that transfers this power to the wheels of the car. The car is designed in an aerodynamic way so that drag is minimized.")

topic = FactoryGirl.create(:topic, name:"robotics",  navgraphic: "navgraphics/robotics.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"parts",  navgraphic: "navgraphics/parts.png", catagory_id: catagory.id, available: "no")
#topic = FactoryGirl.create(:topic, name:"energy",  navgraphic: "navgraphics/machines-energy.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"electronicmachinesandmotors",  navgraphic: "navgraphics/electronicmachines.png", catagory_id: catagory.id, available: "no")
#topic = FactoryGirl.create(:topic, name:"bikesandcars",  navgraphic: "navgraphics/bikesandcars.png", catagory_id: catagory.id, available: "no")


#topic = FactoryGirl.create(:topic, name:"energy",  navgraphic: "navgraphics/machines-energy.png", catagory_id: catagory.id, available: "no")






#topic = FactoryGirl.create(:topic, name:"simple machines", navgraphic: "navgraphics/machinessimplemachines.png", catagory_id: catagory.id, video: "EPDesign.m4v", keypoints: "a simple machine is...")
#topic = FactoryGirl.create(:topic, name:"gears",  navgraphic: "navgraphics/gears.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"motors",  navgraphic: "navgraphics/machinesmotors.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"engines",  navgraphic: "navgraphics/machinesengines.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"electronics",  navgraphic: "navgraphics/machineselectronics.png", catagory_id: catagory.id, video: "EPDesign.m4v")
#topic = FactoryGirl.create(:topic, name:"robotics",  navgraphic: "navgraphics/machinesrobotics.png", catagory_id: catagory.id, video: "EPDesign.m4v")
