# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#### Everything for Materials
#catagory = FactoryGirl.create(:catagory, name:"materials", navgraphic: "navgraphics/materials.png", headergraphic: "materials", color: "materials", keypoints: "And here are some key points<p>" )
catagory = Catagory.create(name:"Materials", navgraphic: "navgraphics/materials.png", headergraphic: "materials", color: "materials", keypoints: "materials main point one.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "first", main_idea:"Materials are what things are made of", header:"Materials are what things are <span class='accent1'>made of</span>", content: "What is a material? A material is what something is made of. Some examples are: wood, stone, plastic, glass, cement, cotton, or steel. Engineers have special words they use to describe materials, like <i>properties</i> or <i>behaviors</i>. For now, you can just think about what they <i>seem</i> like to you. For example, glass is hard and it breaks easily. Wood is softer, and you can dent it with something hard like a hammer. A rubber ball is solid but “squishy”. Fabrics like cotton can be bent or crumpled, and then go right back to how they looked before -- but if you step on a soda can and crumple it, it will not go back to its initial shape when you step off it.<br><br>You encounter materials in everything you touch. Look around you to see what materials you can identify. How do they feel? What happens when you try to bend them, or stretch them, or drop them?")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "second", main_idea:"Materials have properties, which describe how they behave under certain conditions", header:"Materials have <span class='accent1'>properties</span>, which describe how they behave under certain conditions", section_image: "section_images/hammers_hitting_different_materials.png", image_position: "imagerightsmall",content: "If you drop a glass container, it is likely to break, but if you drop a pencil, it usually won't. If you stretch a rubber band out a few inches, it will snap right back; if you somehow manage to stretch out a pencil a few inches, it will break instead of stretching and recovering. These types of properties have names. 
	<br><br> Properties are inherent to a material, but can be changed through heating, cooling, hammering, or adding other things to it. One example of changing the properties in a material is the process for making steel by adding carbon to iron. Iron and steel are mostly the same in terms of the elements that compose it (steel is iron with a tiny bit of carbon), but they have different properties; the same is true for copper and bronze (bronze is copper with a small amount of tin). ")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "third", main_idea:"Materials used to build something must be a good fit for how the thing will be used", header:"Materials used to build something must be a <span class='accent1'>good fit</span> for how the thing will be <span class='accent1'>used</span>", section_image: "section_images/different_basketballs.png", image_position: "imageleftsmall", content: "Would you build a bridge out of particle board? Or make a basketball out of glass?<br><br>Particle board is a wood product made from leftover wood, such as wood chips or sawdust. It is used in places where a wood-like material is desired, but low cost is more important than strength: such as kitchen drawers or low-cost furniture. So, it probably not the best choice for a structure - like a bridge - that must hold the weight of lots of large vehicles. And a basketball made of glass would likely not survive the first bounce on the floor - and even if it did, it would not rebound nicely back into your hand to allow you to continue to dribble down the basketball court. Odds are, you would end up with glass pieces all around your feet!<br><br>Clearly then, materials used to build things - devices, machines, or structures - must be a good fit for how those things are to be used, and choice of materials is often part of the design process. This section will describe some basics about how Engineers think about materials.
")

topic = FactoryGirl.create(:topic, name:"behaviors and properties",  navgraphic: "navgraphics/behaviors_and_properties.png", catagory_id: catagory.id, available: "yes")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Materials have properties, which describe how they behave under different conditions", header:"Materials have <span class='accent1'>properties</span>, which describe how they <span class='accent1'>behave</span> under different <span class='accent1'>conditions</span>", section_image: "section_images/rubber_band_stretched_and_not_stretched.png", image_position: "imagerightmedium", content: "If you drop a glass object, it is likely to break. If you drop a pencil, it usually won't. If you stretch a rubber band out a few inches, it will snap right back. If you try to stretch out a pencil a few inches, it won’t stretch (noticeably). If you keep trying, and pull <i>really</i> hard, it will break instead of stretching and recovering like a rubber band would. These types of properties have names. <br><br>Materials have properties, but these properties can be changed by heating, cooling, hammering, or adding other things to the material. For example, if you add a tiny bit of carbon to iron, you can make steel - a different material that has different properties than iron. Iron is very soft and prone to rusting; steel is stronger and harder - these properties are very different, even though most of what makes up steel actually is iron.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"A property is something about the material that is true regardless of its size or shape", header:"A property is something about the material that is <span class='accent1'>true regardless</span> of its <span class='accent1'>size</span> or <span class='accent1'>shape</span>", content: "For example, <i>Density</i> is the amount of mass per unit volume. Think of density as the amount of heaviness of something as compared to its size: a marble is denser than a cotton ball, because it is pretty heavy for its size. However, the density of a small ice cube is the same as the density of a very large block of ice. <br><br>A material's <i>Melting Point</i> is the temperature at which the material will melt; for example, 32° (Fahrenheit, or F) for ice, but 2600° for low carbon steel. The melting point of mercury is about -38° F, which is why mercury is liquid at room temperature.<br><br>There is a property called <i>Yield Strength</i>, which is how much a material can yield - or stretch - without breaking. One that can stretch before it breaks is <i>ductile</i>; one that breaks right away is called <i>brittle</i>. Rubber and copper are ductile; glass is brittle. Copper is made into wiring because it is both ductile and conducts electricity - it has to be ductile to be made into copper wiring; otherwise it would just break when stretched out into thin wire (which would make for lousy circuits!). And, the ductility of rubber is the reason that a rubber ball bounces - it deforms upon contact with the ground, and the reaction to snap back to a fully round shape is what creates the upward movement. That's why a ball will bounce higher off a hard surface, like concrete, than a soft surface, like carpet - a hard surface creates more deformity in the ball. Try that with a glass basketball!")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Strength and Stiffness are important - but different - properties", header:"<span class='accent1'>Strength</span> and <span class='accent1'>Stiffness</span> are important - but different - properties", content: "<i>Strength</i> is a different materials property than <i>stiffness</i>, although they may sound similar. <i>Strength</i> refers to the amount of force or stress required to break something. <br><br>Rubber is strong - what happens if you construct a bridge from it? The rubber bridge may not break - but that doesn't make it a good bridge! Can you imagine a rubber bridge fully loaded with cars? Perhaps - if the rubber bridge were over a fast-moving river - the bridge would bend down so much that the cars are immersed in the water and left to float downstream. You want a bridge made of a material or materials that will be <i>stiff</i>, as well as strong.<br><br>Stiffness is a measure of the inherent elasticity (or stretchiness) of a material. For example, rubber has a very low measure of stiffness - it's not very stiff at all - while diamond has a very high measure of stiffness. We build bridges and buildings out of stiff materials. <br><br>Rubber may be strong and not stiff - but strength and stiffness are not opposites. Here are some examples:<br><br><table>
				<tr>
				    <td></td>
				    <td width='50''><b><u>Material</b></u></td>
				    <td width='120'><b><u>Stiffness</b></u></td>
					<td><b><u>Strength</b></u></td>
				</tr><tr>
				    <td width='40'></td>
				    <td width='100'>Steel:</td>
				    <td width='130'>Stiff</td>
					<td>Strong</td>
				</tr>
				<tr>
				    <td></td>
					<td>Jelly:</td>
			     	<td>Flexible (un-Stiff)</td>
					<td>Weak</td>
				</tr>
				<tr>
				    <td></td>
					<td>Nylon:</td>
			     	<td>Flexible (un-Stiff)</td>
					<td>Strong</td>
				</tr>
				<tr>
				    <td></td>
					<td>Cracker:</td>
			     	<td>Stiff</td>
					<td>Weak</td>
				</tr>
				</table>
					
				<br>We wouldn't build a bridge out of cracker material any more than we would build one out of rubber material. The cracker would just break, while the rubber would bend too much. For heavy-duty construction, we use materials like steel and concrete. (One minor note here is that, when we build structures like bridges, particularly in windy or earthquake-prone regions, we don't want them to be so stiff that they don't have any give. Structures must be able to move based on forces around them; otherwise, they could break if faced with forces beyond what they can handle.)")
#				<br> <img alt='Representation of atoms or molecules in a solid under tension and compression' class='picpadding' src='/assets/springs.png' /><br><br>")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Elastic and Plastic are behaviors in a material", header:"<span class='accent1'>Elastic</span> and Plastic are <span class='accent1'>behaviors</span> in a material", content: "Elasticity is not just about materials we think of as 'stretchy'. Elasticity also refers to how materials go back to their original shape even when we can't tell that they had changed their shape under load.<br><br><i>Elastic</i> behavior is where a material under strain recovers to its original shape after the load is removed (like a rubber band stretching back). <i>Plastic</i> behavior is where the material retains its deformed shape (think of pounding silly putty with your hand into a flat shape - it will stay flat, demonstrating 'plastic' behavior). We normally think of a rubber band <u>being</u> elastic, but if you stretch the rubber band beyond its ability to snap back, it will break - which is plastic behavior, not elastic behavior.<br><br>Here's another example of elastic behavior, this time in a structure (go to the Structures section to learn more about elasticity in structures). When the Golden Gate Bridge is occupied by bumper-to-bumper traffic, there is an small, unnoticeable (to us) deformity in the deck of the bridge caused by the weight of the cars. If all the cars then leave the bridge, the bridge will recover (thankfully, it is a well-designed bridge and does not collapse under heavy traffic). Even though we can't see that the bridge is being somewhat compressed under the load, it does happen. It is made of metal and concrete, and it is demonstrating elastic behavior. In 1987, for the bridge's 50th anniversary, the bridge was closed to car traffic and people swarmed the bridge for the celebration. An estimated 300,000 people were on the bridge for the celebration. A bridge full of people weighs more than a bridge full of cars (an estimated 5400 lbs per square foot, about double the weight of a full load of cars). The bridge was designed expecting a maximum of 5700 lbs per square foot - but as is usual practice, it was over-engineered to be able to handle much more than that. During the event, the bridge was visibly sagging by around 7 feet. The bridge did not break, and after the festival returned to its normal shape, thus demonstrating the principle of elasticity - visible elasticity - in materials we don't normally think of as 'elastic'. The load that day was within the elastic part of what the bridge could handle; something else entirely might happen if an asteroid fell on the bridge!")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Another material property of interest is Electrical Conductivity", header:"Another material property of interest is <span class='accent1'>Electrical Conductivity</span>", section_image: "section_images/conductivity_behavior.png", image_position: "imagerightlarge", content: "Electrical conductivity is a property that refers to the degree to which a material will conduct electricity. Copper is highly conductive, which is why it is used for wiring. Rubber is not, which is why, if you have to be out in a lightning storm, or you're planning to touch exposed electrical wires (neither of which we recommend!), you might be marginally safer in rubber-soled shoes. A material which is semi-conducting, like silicon, will allow current to flow, but less so than copper. The fact that it is a semiconducting material is what enables it to be used in electronics, as the flow can be controlled to allow current or not, enabling a whole digital world.")


topic = FactoryGirl.create(:topic, name:"history of materials",  navgraphic: "navgraphics/history_of_materials_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"steel",  navgraphic: "navgraphics/steel_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"concrete",  navgraphic: "navgraphics/concrete_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"plastics",  navgraphic: "navgraphics/plastics_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"glass",  navgraphic: "navgraphics/glass_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"semiconductors",  navgraphic: "navgraphics/semiconductors_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"metal alloys",  navgraphic: "navgraphics/metal_alloys_coming_soon.png", catagory_id: catagory.id, available: "no")
