# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#### Everything for Materials
#catagory = FactoryGirl.create(:catagory, name:"materials", navgraphic: "navgraphics/materials.png", headergraphic: "materials", color: "materials", keypoints: "And here are some key points<p>" )
catagory = Catagory.create(name:"Materials", navgraphic: "navgraphics/materials.png", headergraphic: "materials", color: "materials", keypoints: "materials main point one.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "first", main_idea:"Materials are what things are made of", header:"Materials are what things are <span class='accent1'>made of</span>", content: "What is a material? A material is what something is made of. Some examples are: wood, stone, plastic, glass, cement, cotton, or steel. Engineers have special words they use to describe materials, like <i>properties</i> or <i>behaviors</i>. For now, you can just think about what they <i>seem</i> like to you. For example, glass is hard and it breaks easily. Wood is softer, and you can dent it with something hard like a hammer. A rubber ball is solid but “squishy”. Fabrics like cotton can be bent or crumpled, and then go right back to how they looked before -- but if you step on a soda can and crumple it, it will not go back to its initial shape when you step off it.<br><br>You encounter materials in everything you touch. Look around you to see what materials you can identify. How do they feel? What happens when you try to bend them, or stretch them, or drop them?")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "second", main_idea:"Materials have properties, which describe how they behave under certain conditions", header:"Materials have <span class='accent1'>properties</span>, which describe how they behave under certain conditions", section_image: "section_images/hammers_hitting_different_materials.png", image_position: "imagerightsmall",content: "If you drop a glass container, it is likely to break, but if you drop a pencil, it usually won't. If you stretch a rubber band out a few inches, it will snap right back; if you somehow manage to stretch out a pencil a few inches, it will break instead of stretching and recovering. These types of properties have names. 
	<br><br> Properties are inherent to a material, but can be changed through heating, cooling, hammering, or adding other things to it. One example of changing the properties in a material is the process for making steel by adding carbon to iron. Iron and steel are mostly the same in terms of the elements that compose it (steel is iron with a tiny bit of carbon), but they have different properties; the same is true for copper and bronze (bronze is copper with a small amount of tin). ")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "third", main_idea:"Materials used to build something must be a good fit for how the thing will be used", header:"Materials used to build something must be a <span class='accent1'>good fit</span> for how the thing will be <span class='accent1'>used</span>", section_image: "section_images/different_basketballs.png", image_position: "imageleftsmall", content: "Would you build a bridge out of particle board? Or make a basketball out of glass?<br><br>Particle board is a wood product made from leftover wood, such as wood chips or sawdust. It is used in places where a wood-like material is desired, but low cost is more important than strength: such as kitchen drawers or low-cost furniture. So, it probably not the best choice for a structure - like a bridge - that must hold the weight of lots of large vehicles. And a basketball made of glass would likely not survive the first bounce on the floor - and even if it did, it would not rebound nicely back into your hand to allow you to continue to dribble down the basketball court. Odds are, you would end up with glass pieces all around your feet!<br><br>Clearly then, materials used to build things - devices, machines, or structures - must be a good fit for how those things are to be used, and choice of materials is often part of the design process. This section will describe some basics about how Engineers think about materials.
")

question = Question.create(catagory_id: catagory.id, question_num: "1", question_content: "When we talk about a material in Engineering, what do we mean?", question_image: "question_images/mtls_q1.png",explanation: "A material is what something is made of. Some examples are: wood, stone, plastic, glass, cement, cotton, or steel. You encounter materials in everything you touch. Look around you to see what materials you can identify. How do they feel? What happens when you try to bend them, or stretch them, or drop them?")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "What something is made of", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Something you eat for lunch")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Something you wear on your head")

question = Question.create(catagory_id: catagory.id, question_num: "2", question_content: "Which of the following things is a material?", question_image: "question_images/mtls_q2.png",explanation: " A material is what something is made of. Some examples are: wood, stone, plastic, glass, cement, cotton, or steel.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Steel")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Wood")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Plastic")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of the above", correct: "true")


question = Question.create(catagory_id: catagory.id, question_num: "3", question_content: "When engineers think about materials, what important characteristics do they think about?", question_image: "section_images/hammers_hitting_different_materials.png",explanation: "Materials have properties, which describe how they behave under certain conditions. If you drop a glass container, it is likely to break, but if you drop a pencil, it usually won't. If you stretch a rubber band out a few inches, it will snap right back; if you somehow manage to stretch out a pencil a few inches, it will break instead of stretching and recovering. These types of properties have names. Properties are inherent to a material, but can be changed through heating, cooling, hammering, or adding other things to it. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Apples and Oranges")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Cats and Dogs")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Behaviors and Properties", correct: "true")


topic = FactoryGirl.create(:topic, name:"behaviors and properties",  navgraphic: "navgraphics/behaviors_and_properties.png", catagory_id: catagory.id, available: "yes")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Materials have properties, which describe how they behave under different conditions", header:"Materials have <span class='accent1'>properties</span>, which describe how they <span class='accent1'>behave</span> under different <span class='accent1'>conditions</span>", section_image: "section_images/rubber_band_stretched_and_not_stretched.png", image_position: "imagerightmedium", content: "If you drop a glass object, it is likely to break. If you drop a pencil, it usually won't. If you stretch a rubber band out a few inches, it will snap right back. If you try to stretch out a pencil a few inches, it won’t stretch (noticeably). If you keep trying, and pull <i>really</i> hard, it will break instead of stretching and recovering like a rubber band would. These types of properties have names. <br><br>Materials have properties, but these properties can be changed by heating, cooling, hammering, or adding other things to the material. For example, if you add a tiny bit of carbon to iron, you can make steel - a different material that has different properties than iron. Iron is very soft and prone to rusting; steel is stronger and harder - these properties are very different, even though most of what makes up steel actually is iron.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"A property is something about the material that is true regardless of its size or shape", header:"A property is something about the material that is <span class='accent1'>true regardless</span> of its <span class='accent1'>size</span> or <span class='accent1'>shape</span>", content: "For example, <i>Density</i> is the amount of mass per unit volume. Think of density as the amount of heaviness of something as compared to its size: a marble is denser than a cotton ball, because it is pretty heavy for its size. However, the density of a small ice cube is the same as the density of a very large block of ice. <br><br>A material's <i>Melting Point</i> is the temperature at which the material will melt; for example, 32° (Fahrenheit, or F) for ice, but 2600° for low carbon steel. The melting point of mercury is about -38° F, which is why mercury is liquid at room temperature.<br><br>There is a property called <i>Yield Strength</i>, which is how much a material can yield - or stretch - without breaking. One that can stretch before it breaks is <i>ductile</i>; one that breaks right away is called <i>brittle</i>. Rubber and copper are ductile; glass is brittle. Copper is made into wiring because it is both ductile and conducts electricity - it has to be ductile to be made into copper wiring; otherwise it would just break when stretched out into thin wire (which would make for lousy circuits!). And, the ductility of rubber is the reason that a rubber ball bounces - it deforms upon contact with the ground, and the reaction to snap back to a fully round shape is what creates the upward movement. That's why a ball will bounce higher off a hard surface, like concrete, than a soft surface, like carpet - a hard surface creates more deformity in the ball. Try that with a glass basketball!")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Strength and Stiffness are important - but different - properties", header:"<span class='accent1'>Strength</span> and <span class='accent1'>Stiffness</span> are important - but different - properties", content: "<i>Strength</i> is a different materials property than <i>stiffness</i>, although they may sound similar. <i>Strength</i> refers to the amount of force or stress required to break something. <br><br>Rubber is strong - what happens if you construct a bridge from it? The rubber bridge may not break - but that doesn't make it a good bridge! Can you imagine a rubber bridge fully loaded with cars? Perhaps - if the rubber bridge were over a fast-moving river - the bridge would bend down so much that the cars are immersed in the water and left to float downstream. You want a bridge made of a material or materials that will be <i>stiff</i>, as well as strong.<br><br>Stiffness is a measure of the inherent elasticity (or stretchiness) of a material. For example, rubber has a very low measure of stiffness - it's not very stiff at all - while diamond has a very high measure of stiffness. We build bridges and buildings out of stiff materials. <br><br>Rubber may be strong and not stiff - but strength and stiffness are not opposites. Here are some examples:<br><br><table>
				<tr>
				    <td></td>
				    <td width='50''><b><u>Material</b></u></td>
				    <td width='120'><b><u>Stiffness</b></u></td>
					<td><b><u>Strength</b></u></td>
				</tr><tr>
				    <td width='40'></td>
				    <td width='100'>Steel:</td>
				    <td width='130'>Stiff</td>
					<td>Strong</td>
				</tr>
				<tr>
				    <td></td>
					<td>Jelly:</td>
			     	<td>Flexible (un-Stiff)</td>
					<td>Weak</td>
				</tr>
				<tr>
				    <td></td>
					<td>Nylon:</td>
			     	<td>Flexible (un-Stiff)</td>
					<td>Strong</td>
				</tr>
				<tr>
				    <td></td>
					<td>Cracker:</td>
			     	<td>Stiff</td>
					<td>Weak</td>
				</tr>
				</table>
					
				<br>We wouldn't build a bridge out of cracker material any more than we would build one out of rubber material. The cracker would just break, while the rubber would bend too much. For heavy-duty construction, we use materials like steel and concrete. (One minor note here is that, when we build structures like bridges, particularly in windy or earthquake-prone regions, we don't want them to be so stiff that they don't have any give. Structures must be able to move based on forces around them; otherwise, they could break if faced with forces beyond what they can handle.)")
#				<br> <img alt='Representation of atoms or molecules in a solid under tension and compression' class='picpadding' src='/assets/springs.png' /><br><br>")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Elastic and Plastic are behaviors in a material", header:"<span class='accent1'>Elastic</span> and Plastic are <span class='accent1'>behaviors</span> in a material", content: "Elasticity is not just about materials we think of as 'stretchy'. Elasticity also refers to how materials go back to their original shape even when we can't tell that they had changed their shape under load.<br><br><i>Elastic</i> behavior is where a material under strain recovers to its original shape after the load is removed (like a rubber band stretching back). <i>Plastic</i> behavior is where the material retains its deformed shape (think of pounding silly putty with your hand into a flat shape - it will stay flat, demonstrating 'plastic' behavior). We normally think of a rubber band <u>being</u> elastic, but if you stretch the rubber band beyond its ability to snap back, it will break - which is plastic behavior, not elastic behavior.<br><br>Here's another example of elastic behavior, this time in a structure (go to the Structures section to learn more about elasticity in structures). When the Golden Gate Bridge is occupied by bumper-to-bumper traffic, there is an small, unnoticeable (to us) deformity in the deck of the bridge caused by the weight of the cars. If all the cars then leave the bridge, the bridge will recover (thankfully, it is a well-designed bridge and does not collapse under heavy traffic). Even though we can't see that the bridge is being somewhat compressed under the load, it does happen. It is made of metal and concrete, and it is demonstrating elastic behavior. In 1987, for the bridge's 50th anniversary, the bridge was closed to car traffic and people swarmed the bridge for the celebration. An estimated 300,000 people were on the bridge for the celebration. A bridge full of people weighs more than a bridge full of cars (an estimated 5400 lbs per square foot, about double the weight of a full load of cars). The bridge was designed expecting a maximum of 5700 lbs per square foot - but as is usual practice, it was over-engineered to be able to handle much more than that. During the event, the bridge was visibly sagging by around 7 feet. The bridge did not break, and after the festival returned to its normal shape, thus demonstrating the principle of elasticity - visible elasticity - in materials we don't normally think of as 'elastic'. The load that day was within the elastic part of what the bridge could handle; something else entirely might happen if an asteroid fell on the bridge!")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Another material property of interest is Electrical Conductivity", header:"Another material property of interest is <span class='accent1'>Electrical Conductivity</span>", section_image: "section_images/conductivity_behavior.png", image_position: "imagerightlarge", content: "Electrical conductivity is a property that refers to the degree to which a material will conduct electricity. Copper is highly conductive, which is why it is used for wiring. Rubber is not, which is why, if you have to be out in a lightning storm, or you're planning to touch exposed electrical wires (neither of which we recommend!), you might be marginally safer in rubber-soled shoes. A material which is semi-conducting, like silicon, will allow current to flow, but less so than copper. The fact that it is a semiconducting material is what enables it to be used in electronics, as the flow can be controlled to allow current or not, enabling a whole digital world.")


#topic = FactoryGirl.create(:topic, name:"history of materials",  navgraphic: "navgraphics/history_of_materials_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"steel",  navgraphic: "navgraphics/steel.png", catagory_id: catagory.id, available: "yes")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"We all use steel", header:"We <span class='accent1'>all</span> use steel", section_image: "section_images/things_made_out_of_steel.png", image_position: "imagerightlarge", content: "Steel is a material that people in the modern world encounter every day. Steel is known for its <i>strength</i>, <i>toughness</i>, and <i>stiffness</i>. This unique combination of properties makes it ideal for building vehicles, structures, and tools. However, steel’s contribution to our world does not just stop there. You can find steel in countless household items including refrigerators, microwaves, paper clips and even the cans you might buy food in at the grocery store. Because of its wide-ranging uses, 1.3 billion tons of steel is produced every year. That is enough to make 21 trillion steel food cans, which, if stacked on top of one another, could reach the moon and back 7,000 times! Together, we will explore the chemistry of steel and find out why this material has such useful properties.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Steel’s key properties are strength, toughness, and stiffness", header:"Steel’s key <span class='accent1'>properties</span> are <span class='accent1'>strength</span>, <span class='accent1'>toughness</span>, and <span class='accent1'>stiffness</span>", section_image: "", section_image: "section_images/properties_of_steel.png", image_position: "imagerightmedium", content: "Steel is more than just a gray, shiny metal. It is also strong, tough and stiff &#8212; a combination of <i>properties</i> that makes steel ideal for many uses. When describing the properties of a material, the words strong, tough, and stiff have particular meanings. Let’s look at these properties one by one.<br><br>
If a material has the property of being <i>strong</i>, that means it can stand up to a lot of force. You exert a force on an object by either pushing or pulling on it. If you push on an object, it is under compression. If you pull on an object, it is under tension. Steel is strong under both tension and compression. Its strength makes steel an ideal material for things that have to support a lot of weight, like the columns and beams used in construction.<br><br>
If a material is <i>tough</i>, it can deform, or permanently change shape, without fracturing or breaking. With materials, the opposite of being tough is being brittle. A brittle material will break without first deforming under stress. A material can be strong and tough, like steel, or strong and brittle like a ceramic mug. A ceramic mug is strong. For example, you can put a lot of heavy items on top of a ceramic mug and it won’t break. But if you accidentally knock it off a counter, it will probably break when it hits the floor. A mug made out of steel, on the other hand, will not break if you knock it off the counter, although it might get a dent in it. This ability to deform without breaking makes steel handy for things like camping mugs and dishes. Toughness is also a critical property for things like car frames, which are designed to crumple to protect passengers. Toughness is also the property that makes steel an ideal material for things like staples, which are designed to bend and then hold that shape.<br><br>
If a material is <i>stiff</i>, it is not very stretchy. With materials, the opposite of being stiff is being flexible. If something is very flexible, that means it’s going to stretch under pressure, like when you pull on a rubber band. A material can be strong and stiff, like steel, or strong and flexible, like rubber. Rubber might be able to support a lot of weight, but you would not want to use it to build a bridge. A rubber bridge would bend under the weight of its users and maybe even under the force of just its own weight. Steel, on the other hand, is ideal for building large structures like bridges because it can support the force of the weight of its users without stretching down. Strong, tough and stiff, steel has a unique combination of properties, making it an ideal material for a wide range of uses, from staples to bridges.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Carbon makes steel strong and tough", header:"<span class='accent1'>Carbon</span> makes steel <span class='accent1'>strong</span> and <span class='accent1'>tough</span>", section_image: "", content: "Steel is an <i>alloy</i>, which is a material made up of a metal plus something else. That something else can be another metal or can be nonmetal. The two key elements of steel are iron, a metal, and carbon, a nonmetal. There are different types of steels, which depend on the amount of carbon and other elements present in the alloy. To understand steel’s behavior, we must look more closely at iron and carbon. <br><br>Steel is mostly iron, with a very small amount of carbon. Yet, thanks to carbon, steel can be 1,000 times stronger than pure iron! Adding carbon to iron makes steel stronger and tougher, but only up to a point. Iron with too much carbon will be strong, but instead of being tough, it will turn <i>brittle</i>. Different types of steel contain different amounts of carbon. An engineer, builder, or manufacturer must use the type of steel that has the right amount of carbon and therefore the right amount of strength and toughness for what she is building.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"The other elements in steel also affect steel’s properties", header:"The<span class='accent1'> other elements</span> in steel also <span class='accent1'>affect</span> steel’s <span class='accent1'>properties</span>", section_image: "section_images/stainless_steel_cuttlery.png", image_position: "imageleftlarge", content: "Although all steels contain carbon and iron, some steels also contain other elements that affect the steel’s properties. Many steels contain the elements nickel, manganese, chromium, and vanadium, which change the properties of the steels. For example, by adding a large amount of chromium, stainless steel can be made. Stainless steel has a very shiny finish and is highly resistant to <i>corrosion</i>, a gradual wearing away of a material. Stainless steel is used to make jewelry, silverware, surgical instruments, and other objects where the finish and non-corrosive attributes of stainless steel are desired. Stainless steel has even been used on the outside of some of the world’s tallest skyscrapers!")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"Steel has only been in wide usage for less than 200 years", header:"Steel has only been in <span class='accent1'>wide usage</span> for <span class='accent1'>less than 200 years</span>", section_image: "", content: "Steel made its earliest appearance around 1800 BCE. Ancient Rome, Greece, India, and China all used steel. In ancient times, steel was largely used for making weapons. Since steel is strong and can bend without breaking, a steel sword could be used in a sword fight without snapping. However because the methods used to manufacture steel were not very advanced, steel was not widely used prior to the 1800s. <br><br>Although steel was known in the ancient world, it started becoming widely used in the late 1800s. In 1856, Henry Bessemer patented the Bessemer process for manufacturing steel, which revolutionized the steel industry. The Bessemer process allowed steel to be mass-produced at low costs.")


section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"Today’s steel manufacturers can precisely control the amount of carbon in steel", header:"Today’s steel manufacturers can <span class='accent1'>precisely control</span> the amount of carbon in steel", section_image: "section_images/steel_manufacturing.png", image_position: "imagerightlarge", content: "To start the steelmaking process, iron must first be extracted from iron ore. An ore is a natural formation like a rock, which is partly made up of a mineral like iron. The process of getting a mineral out of rock is called smelting. When iron ore is smelted, the result is iron in a metallic form. This iron contains a high amount of carbon from the smelting process. But remember, the alloy of iron and carbon is only considered steel if the alloy has a particular range of carbon, typically under about 2%. Too much carbon and the metal will be brittle and therefore not steel. So the second step of making steel is to reduce the amount of carbon in the iron to the desired amount. Carbon is removed by blowing oxygen through molten, or melted, iron. The melting point of iron is 2800 °F (1538 °C), so the steelmaking process requires some pretty intense heat. <br><br>Today’s steel manufacturers are able to control exactly how much carbon remains in the steel. Thus, they can make different steels for almost any project and know precisely how each steel will behave. Whether we need steel with a tiny percentage of carbon for making car bodies or a steel with a larger percentage of carbon for making tools, steel manufacturers have the ability to produce it.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "seventh", main_idea:"Steel is a defining material of the modern world", header:"Steel is a <span class='accent1'>defining material</span> of the modern world", section_image: "", content: "From eating with stainless steel utensils, to driving around in vehicles built with steel parts, to going to school or work in buildings made with steel columns and beams, we benefit from steel every day. The ability to cost-effectively manufacture high-quality steel, with its unique combination of strength, toughness and stiffness has been critical to the development of our modern world. Our lives would simply not be the same without it. ")

#topic = FactoryGirl.create(:topic, name:"glass",  navgraphic: "navgraphics/glass_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"glass",  navgraphic: "navgraphics/glass.png", catagory_id: catagory.id, available: "yes")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Glass has very diverse uses in the modern world", header:"Glass has very <span class='accent1'>diverse uses</span> in the modern world", content: "You are probably quite familiar with the material known as glass. When you look out a window, you are looking through glass. When you watch something on television or a computer screen, you are looking at a glass screen. We often call something you drink out of “a glass” – even when it is made of plastic! <br><br> These are all examples glass made from <i>silica</i>, which you’ll learn is the main ingredient of sand. But, scientists refer to other materials as “glass,” too. Glass feels like a solid, but internally is a little bit like a liquid, because the molecules are arranged irregularly, or not in a pattern, inside. In this article we are focusing on what we normally think of as glass – the material made from silica.<br><br> Most of the examples above are probably items you think of as being fragile. If you knock a glass off a counter, it will likely break. So you might be surprised to learn that glass is also used in making things like fiberglass boats and fiber optic cables. Fiberglass boats and fiber optic cables are not fragile at all. These forms of glass have some different <i>properties</i> than the glass used for windows. In addition to everyday items like glasses and windows, glass has made some surprising contributions to the modern world. 
")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Key properties of glass include transparency, non-reactivity, brittleness, and strength in compression", header:"Key <span class='accent1'>properties</span> of glass include <span class='accent1'>transparency</span>, <span class='accent1'>non-reactivity</span>, <span class='accent1'>brittleness</span>, and <span class='accent1'>strength in compression</span>", content: "One of the most obvious physical properties of most glass is that it is <i>transparent</i>. You probably know that if something is transparent you can see through it. Something that is transparent allows light to pass through it. Glass transmits, reflects, and refracts (bends) light, instead of <i>absorbing</i> it. Because light passes through it, we can see what is on the other side of the glass. Being transparent makes glass an ideal material for windows or anything else we need to see through. <br><br> Another important property of glass is that it is <i>non-reactive</i>. Something <i>re</i>active can react with things it comes into contact with – like how iron can rust from exposure to air. Something that is <i>non</i>-reactive does not react with other things it comes into contact with. Because glass is non-reactive, if you put something in glass, like tomato sauce, the glass will not change the taste or composition of the sauce. That makes glass great for uses like storing food or chemicals. <br><br> Glass is also <i>brittle</i>. If something is brittle it will not bend before breaking if it experiences a large force, like getting knocked off a counter. That’s why people sometimes prefer to store food in plastic instead of glass.<br><br> Glass is strong under <i>compression</i> (pushing forces) and can hold a lot of weight. For example, you can stand on a floor made of thick glass, and it won’t break under your weight. Have you ever been in a glass-bottom boat? They actually exist! However, the glass used in things like drinking glasses and windows is not strong under <i>tension</i> (pulling forces). This type of glass would not be a useful material for making things like the chains on a swing, which get pulled when someone sits down on the seat.")


section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"Glass can be modified to change its properties", header:"Glass can be <span class='accent1'>modified</span> to change its <span class='accent1'>properties</span>", section_image: "section_images/shattered_glass_windshield.jpg", image_position: "imagerightlarge",content: "Like other materials, glass can be modified to change its <i>properties</i>. A material’s properties can be changed by heating, cooling, or <i>working</i> (which means doing something to it, like hammering or stretching) the material. You can also change the properties of a material by adding other ingredients to it.<br><br> One example of glass with modified properties is <i>safety glass</i>. If you have ever broken a drinking glass, you know that it breaks into lots of different sized pieces, some of which can be very large and sharp. You can image how dangerous that kind of glass would be in a car accident. Instead, car windows are made from safety glass.  Both thermal (heat) and chemical treatments are used to make safety glass.  The result is that the outer surfaces of the safety glass are in <i>compression</i> (being pushed in) and its inner surfaces are in <i>tension</i> (being pulled out). The stress is balanced between the molecules, causing the glass to shatter evenly. This makes the glass harder and causes it to shatter into very small pieces. So, if your car’s front windshield is broken in accident, it will shatter evenly into small pieces instead of large dangerous shards. That makes safety glass a much safer material for a car windshield.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"Glass fibers are a glass-based material with an additional key property: tensile strength", header:"Glass <span class='accent1'>fibers</span> are a glass-based material with an additional key property: <span class='accent1'>tensile strength</span>", content: "Glass fibers are long, thin strands of glass. Glass fibers are made by heating and stretching glass into very thin strands, or “fibers”. Unlike regular glass, glass fibers have a lot of <i>tensile strength</i>. A material with high tensile strength can withstand being pulled really hard before breaking. <br><br> One use of glass fibers is as a material for insulating buildings. Insulating materials help to slow heat from moving. A home that is insulated will stay cooler in the summer and warmer in the winter. For insulating materials, flexible glass fibers are intertwined into a form sometimes called “glass wool”. If you have ever seen insulating material, it does kind of look like fabric, doesn’t it? The glass fibers trap blocks of air. Gases like air do not conduct heat easily. Glass wool insulation traps air, which makes it an excellent heat insulator. <br><br> Another material made with glass fibers is fiberglass. Fiberglass is plastic reinforced with glass fibers. Fiberglass is widely used as a reinforcement material because of its strength. Items reinforced with fiberglass include circuit boards for televisions, radios, and computers. It is also used to reinforce the shells of pools, bathtubs, and boats – not things we typically think of as being made with glass! Although fiberglass contains glass, it has different properties than what we normally think of when we think of glass. Glass fibers used for reinforcement material or insulation do not require transparency, unlike so many other uses of glass.
")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"Optical fibers are glass fibers used to transmit light", header:"<span class='accent1'>Optical fibers</span> are glass fibers used to <span class='accent1'>transmit light</span>", content: "Glass fibers that <i>do</i> utilize the transparency property of glass are called optical fibers.   Optical fibers are long, thin glass threads that are used to transmit light. Each thread is as thin as human hair. Threads that are grouped into bundles are called fiber optic cables. These cables are used to transmit light, just like a window transmits light. The light that is transmitted represents data that is moving through the wire as a series of light signals. That data might be a conversation you are having on the phone, a text message you are sending, or a video you are streaming online. <br><br> Light travels through the center of the fiber optic cable by bouncing off the insides of the cable. Light can travel great distances through fiber optics because the inside of the cable does not absorb any light. Only impurities in the glass cause the light signal to degrade.<br><br> Fiber optic cables are replacing the copper wires that were historically used for transmitting data. Fiber optic cables are cheaper, thinner, more flexible, and more lightweight than copper. They also transmit data faster than copper can. Not all communications data is sent over optical fibers. However where optical fibers are used, there is a significant improvement in the capacity and speed of transmitting that data.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "seventh", main_idea:"The main ingredient of glass is the main ingredient in sand", header:"The main <span class='accent1'>ingredient</span> of glass is the main ingredient in <span class='accent1'>sand</span>", content: "Glass is used for many things in the modern world from windows to insulation and communication cables. Part of the success of glass has to do with the fact that it is inexpensive to make. It is inexpensive to make because the ingredients for glass are so abundant. The main ingredient in most glass is a compound called silicon dioxide, also known as silica. If you have ever been to the beach or played in a sandbox, you are actually pretty familiar with silica, because it is also the main ingredient in sand. Sand and glass look nothing alike, but sand heated up to very high temperatures forms glass! <br><br> To make glass, other ingredients are added to the silica sand. These ingredients are added to change and improve the properties of the glass. For example, something called sodium carbonate lowers the temperature required to make glass. Lead oxide makes glass softer so it is easier to cut, and is also what causes crystal glassware to sparkle. Chemicals can also be added to change the color of glass. The mixture is then heated to high temperatures to melt and become glass.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "eighth", main_idea:"Glass is found in nature", header:"<span class='accent1'>Glass</span> is found in <span class='accent1'>nature</span>", content: "Before people began <i>making</i> glass, they used glass that was made naturally. Because glass is sand heated to very high temperatures, glass can found in nature near very hot sources. One example of naturally occurring glass comes from lightning striking sand. Another source is volcanoes. Obsidian is one type of volcanic glass that was used in ancient times to make arrowheads, knives, and jewelry. Obsidian is still used in jewelry today. Although transparency is one of the key properties of much of the glass we use today, glass does not have to be transparent. For example, obsidian is often black and might look more like a shiny rock than a type of glass. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "ninth", main_idea:"Glass is a critical material for building and communicating", header:"Glass is a critical material for <span class='accent1'>building</span> and <span class='accent1'>communicating</span>", content: "Glass has very diverse uses. We have relied on glass windows to bring natural light into our homes, schools, and businesses for centuries. More recently, we have also come to rely on glass fibers to move massive amounts of data around the world. Sometimes the use of glass is obvious. When you use a drinking glass or look out a window, you know that you are using glass. Other times, glass is hidden in fiberglass insulation or in the fiber optic cables we use to communicate. Now that you know its many uses, you may never see (or see through) glass the same way again!")



topic = FactoryGirl.create(:topic, name:"concrete",  navgraphic: "navgraphics/concrete_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"plastics",  navgraphic: "navgraphics/plastics_coming_soon.png", catagory_id: catagory.id, available: "no")

topic = FactoryGirl.create(:topic, name:"semiconductors",  navgraphic: "navgraphics/semiconductors_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"metal alloys",  navgraphic: "navgraphics/metal_alloys_coming_soon.png", catagory_id: catagory.id, available: "no")
