# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#### Everything for Materials
#catagory = FactoryGirl.create(:catagory, name:"materials", navgraphic: "navgraphics/materials.png", headergraphic: "materials", color: "materials", keypoints: "And here are some key points<p>" )
catagory = Catagory.create(name:"Materials", navgraphic: "navgraphics/materials.png", headergraphic: "materials", color: "materials", keypoints: "materials main point one.", video:"//www.youtube.com/embed/sWYa0bUt4_4")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "first", main_idea:"Materials are what things are made of", header:"Materials are what things are <span class='accent1'>made of</span>", content: "What is a material? A material is what something is made of. Some examples are: wood, stone, plastic, glass, cement, cotton, or steel. Engineers have special words they use to describe materials, like <i>properties</i> or <i>behaviors</i>. For now, you can just think about what they <i>seem</i> like to you. For example, glass is hard and it breaks easily. Wood is softer, and you can dent it with something hard like a hammer. A rubber ball is solid but “squishy”. Fabrics like cotton can be bent or crumpled, and then go right back to how they looked before -- but if you step on a soda can and crumple it, it will not go back to its initial shape when you step off it.<br><br>You encounter materials in everything you touch. Look around you to see what materials you can identify. How do they feel? What happens when you try to bend them, or stretch them, or drop them?")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "second", main_idea:"Materials have properties, which describe how they behave under certain conditions", header:"Materials have <span class='accent1'>properties</span>, which describe how they behave under certain conditions", section_image: "section_images/hammers_hitting_different_materials.png", image_position: "imagerightsmall",content: "If you drop a glass container, it is likely to break, but if you drop a pencil, it usually won't. If you stretch a rubber band out a few inches, it will snap right back; if you somehow manage to stretch out a pencil a few inches, it will break instead of stretching and recovering. These types of properties have names. 
	<br><br> Properties are inherent to a material, but can be changed through heating, cooling, hammering, or adding other things to it. One example of changing the properties in a material is the process for making steel by adding carbon to iron. Iron and steel are mostly the same in terms of the elements that compose it (steel is iron with a tiny bit of carbon), but they have different properties; the same is true for copper and bronze (bronze is copper with a small amount of tin). ")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "third", main_idea:"Materials used to build something must be a good fit for how the thing will be used", header:"Materials used to build something must be a <span class='accent1'>good fit</span> for how the thing will be <span class='accent1'>used</span>", section_image: "section_images/different_basketballs.png", image_position: "imageleftsmall", content: "Would you build a bridge out of particle board? Or make a basketball out of glass?<br><br>Particle board is a wood product made from leftover wood, such as wood chips or sawdust. It is used in places where a wood-like material is desired, but low cost is more important than strength: such as kitchen drawers or low-cost furniture. So, it probably not the best choice for a structure - like a bridge - that must hold the weight of lots of large vehicles. And a basketball made of glass would likely not survive the first bounce on the floor - and even if it did, it would not rebound nicely back into your hand to allow you to continue to dribble down the basketball court. Odds are, you would end up with glass pieces all around your feet!<br><br>Clearly then, materials used to build things - devices, machines, or structures - must be a good fit for how those things are to be used, and choice of materials is often part of the design process. This section will describe some basics about how Engineers think about materials.
")

question = Question.create(catagory_id: catagory.id, question_num: "1", question_content: "When we talk about a material in Engineering, what do we mean?", question_image: "question_images/mtls_q1.png",explanation: "A material is what something is made of. Some examples are: wood, stone, plastic, glass, cement, cotton, or steel. You encounter materials in everything you touch. Look around you to see what materials you can identify. How do they feel? What happens when you try to bend them, or stretch them, or drop them?")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "What something is made of", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Something you eat for lunch")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Something you wear on your head")

question = Question.create(catagory_id: catagory.id, question_num: "2", question_content: "Which of the following things is a material?", question_image: "question_images/mtls_q2.png",explanation: " A material is what something is made of. Some examples are: wood, stone, plastic, glass, cement, cotton, or steel.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Steel")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Wood")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Plastic")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of the above", correct: "true")


question = Question.create(catagory_id: catagory.id, question_num: "3", question_content: "When engineers think about materials, what important characteristics do they think about?", question_image: "section_images/hammers_hitting_different_materials.png",explanation: "Materials have properties, which describe how they behave under certain conditions. If you drop a glass container, it is likely to break, but if you drop a pencil, it usually won't. If you stretch a rubber band out a few inches, it will snap right back; if you somehow manage to stretch out a pencil a few inches, it will break instead of stretching and recovering. These types of properties have names. Properties are inherent to a material, but can be changed through heating, cooling, hammering, or adding other things to it. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Apples and Oranges")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Cats and Dogs")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Behaviors and Properties", correct: "true")


topic = FactoryGirl.create(:topic, name:"behaviors and properties",  navgraphic: "navgraphics/behaviors_and_properties.png", catagory_id: catagory.id, available: "yes")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Materials have properties, which describe how they behave under different conditions", header:"Materials have <span class='accent1'>properties</span>, which describe how they <span class='accent1'>behave</span> under different <span class='accent1'>conditions</span>", section_image: "section_images/rubber_band_stretched_and_not_stretched.png", image_position: "imagerightmedium", content: "If you drop a glass object, it is likely to break. If you drop a pencil, it usually won't. If you stretch a rubber band out a few inches, it will snap right back. If you try to stretch out a pencil a few inches, it won’t stretch (noticeably). If you keep trying, and pull <i>really</i> hard, it will break instead of stretching and recovering like a rubber band would. These types of properties have names. <br><br>Materials have properties, but these properties can be changed by heating, cooling, hammering, or adding other things to the material. For example, if you add a tiny bit of carbon to iron, you can make steel - a different material that has different properties than iron. Iron is very soft and prone to rusting; steel is stronger and harder - these properties are very different, even though most of what makes up steel actually is iron.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"A property is something about the material that is true regardless of its size or shape", header:"A property is something about the material that is <span class='accent1'>true regardless</span> of its <span class='accent1'>size</span> or <span class='accent1'>shape</span>", content: "For example, <i>Density</i> is the amount of mass per unit volume. Think of density as the amount of heaviness of something as compared to its size: a marble is denser than a cotton ball, because it is pretty heavy for its size. However, the density of a small ice cube is the same as the density of a very large block of ice. <br><br>A material's <i>Melting Point</i> is the temperature at which the material will melt; for example, 32° (Fahrenheit, or F) for ice, but 2600° for low carbon steel. The melting point of mercury is about -38° F, which is why mercury is liquid at room temperature.<br><br>There is a property called <i>Yield Strength</i>, which is how much a material can yield - or stretch - without breaking. One that can stretch before it breaks is <i>ductile</i>; one that breaks right away is called <i>brittle</i>. Rubber and copper are ductile; glass is brittle. Copper is made into wiring because it is both ductile and conducts electricity - it has to be ductile to be made into copper wiring; otherwise it would just break when stretched out into thin wire (which would make for lousy circuits!). And, the ductility of rubber is the reason that a rubber ball bounces - it deforms upon contact with the ground, and the reaction to snap back to a fully round shape is what creates the upward movement. That's why a ball will bounce higher off a hard surface, like concrete, than a soft surface, like carpet - a hard surface creates more deformity in the ball. Try that with a glass basketball!")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Strength and Stiffness are important - but different - properties", header:"<span class='accent1'>Strength</span> and <span class='accent1'>Stiffness</span> are important - but different - properties", section_image: "section_images/strengthstiffness.png", image_position: "imagerightsmall",content: "<i>Strength</i> is a different materials property than <i>stiffness</i>, although they may sound similar. <i>Strength</i> refers to the amount of force or stress required to break something. <br><br>Rubber is strong - what happens if you construct a bridge from it? The rubber bridge may not break - but that doesn't make it a good bridge! Can you imagine a rubber bridge fully loaded with cars? Perhaps - if the rubber bridge were over a fast-moving river - the bridge would bend down so much that the cars are immersed in the water and left to float downstream. You want a bridge made of a material or materials that will be <i>stiff</i>, as well as strong.<br><br>Stiffness is a measure of the inherent elasticity (or stretchiness) of a material. For example, rubber has a very low measure of stiffness - it's not very stiff at all - while diamond has a very high measure of stiffness. We build bridges and buildings out of stiff materials. <br><br>Rubber may be strong and not stiff - but strength and stiffness are not opposites. Here are some examples:<br><br><table>
				<tr>
				    <td></td>
				    <td width='50''><b><u>Material</b></u></td>
				    <td width='120'><b><u>Stiffness</b></u></td>
					<td><b><u>Strength</b></u></td>
				</tr><tr>
				    <td width='40'></td>
				    <td width='100'>Steel:</td>
				    <td width='130'>Stiff</td>
					<td>Strong</td>
				</tr>
				<tr>
				    <td></td>
					<td>Jelly:</td>
			     	<td>Flexible (un-Stiff)</td>
					<td>Weak</td>
				</tr>
				<tr>
				    <td></td>
					<td>Nylon:</td>
			     	<td>Flexible (un-Stiff)</td>
					<td>Strong</td>
				</tr>
				<tr>
				    <td></td>
					<td>Cracker:</td>
			     	<td>Stiff</td>
					<td>Weak</td>
				</tr>
				</table>
					
				<br>We wouldn't build a bridge out of cracker material any more than we would build one out of rubber material. The cracker would just break, while the rubber would bend too much. For heavy-duty construction, we use materials like steel and concrete. (One minor note here is that, when we build structures like bridges, particularly in windy or earthquake-prone regions, we don't want them to be so stiff that they don't have any give. Structures must be able to move based on forces around them; otherwise, they could break if faced with forces beyond what they can handle.)")
#				<br> <img alt='Representation of atoms or molecules in a solid under tension and compression' class='picpadding' src='/assets/springs.png' /><br><br>")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Elastic and Plastic are behaviors in a material", header:"<span class='accent1'>Elastic</span> and Plastic are <span class='accent1'>behaviors</span> in a material", content: "Elasticity is not just about materials we think of as 'stretchy'. Elasticity also refers to how materials go back to their original shape even when we can't tell that they had changed their shape under load.<br><br><i>Elastic</i> behavior is where a material under strain recovers to its original shape after the load is removed (like a rubber band stretching back). <i>Plastic</i> behavior is where the material retains its deformed shape (think of pounding silly putty with your hand into a flat shape - it will stay flat, demonstrating 'plastic' behavior). We normally think of a rubber band <u>being</u> elastic, but if you stretch the rubber band beyond its ability to snap back, it will break - which is plastic behavior, not elastic behavior.<br><br>Here's another example of elastic behavior, this time in a structure (go to the Structures section to learn more about elasticity in structures). When the Golden Gate Bridge is occupied by bumper-to-bumper traffic, there is an small, unnoticeable (to us) deformity in the deck of the bridge caused by the weight of the cars. If all the cars then leave the bridge, the bridge will recover (thankfully, it is a well-designed bridge and does not collapse under heavy traffic). Even though we can't see that the bridge is being somewhat compressed under the load, it does happen. It is made of metal and concrete, and it is demonstrating elastic behavior. In 1987, for the bridge's 50th anniversary, the bridge was closed to car traffic and people swarmed the bridge for the celebration. An estimated 300,000 people were on the bridge for the celebration. A bridge full of people weighs more than a bridge full of cars (an estimated 5400 lbs per square foot, about double the weight of a full load of cars). The bridge was designed expecting a maximum of 5700 lbs per square foot - but as is usual practice, it was over-engineered to be able to handle much more than that. During the event, the bridge was visibly sagging by around 7 feet. The bridge did not break, and after the festival returned to its normal shape, thus demonstrating the principle of elasticity - visible elasticity - in materials we don't normally think of as 'elastic'. The load that day was within the elastic part of what the bridge could handle; something else entirely might happen if an asteroid fell on the bridge!")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Another material property of interest is Electrical Conductivity", header:"Another material property of interest is <span class='accent1'>Electrical Conductivity</span>", section_image: "section_images/conductivity_behavior.png", image_position: "imagerightlarge", content: "Electrical conductivity is a property that refers to the degree to which a material will conduct electricity. Copper is highly conductive, which is why it is used for wiring. Rubber is not, which is why, if you have to be out in a lightning storm, or you're planning to touch exposed electrical wires (neither of which we recommend!), you might be marginally safer in rubber-soled shoes. A material which is semi-conducting, like silicon, will allow current to flow, but less so than copper. The fact that it is a semiconducting material is what enables it to be used in electronics, as the flow can be controlled to allow current or not, enabling a whole digital world.")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What is a property of a material?", question_image: "section_images/rubber_band_stretched_and_not_stretched.png", explanation: "A property is something that does not change based on a material's size or shape. For example, the density of a small ice cube is the same as the density of a very large block. A material's Melting Point is another property. Ice melts at 32° (Fahrenheit, or F), but low carbon steel will not melt below 2600°. The melting point of mercury is about -38° F, which is why mercury is liquid at room temperature. Density and Melting Point are properties of a material.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "A property is something that is true about a material ONLY if it is a particular size or shape")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A property is something you own in Monopoly")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "A property is something about the material that is true regardless of its size or shape", correct: "true")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "What is Density?", question_image: "section_images/rubber_band_stretched_and_not_stretched.png", explanation: "Think of density as the amount of heaviness of something as compared to its size: a marble is denser than a cotton ball, because it is pretty heavy for its size. However, the density of a small ice cube is the same as the density of a very large block of ice.  ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Density is the amount of mass per unit volume: a measure of the heaviness of something for its size", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Density is a trait of not-so-smart people")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Density is the temperature at which something will melt")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "Which material below is both STIFF and STRONG?", question_image: "section_images/strengthstiffness.png", explanation: "Strength is a different materials property than stiffness, although they may sound similar. Strength refers to the amount of force or stress required to break something. Stiffness is a measure of the inherent elasticity (or stretchiness) of a material. For example, rubber has a very low measure of stiffness - it's not very stiff at all - while diamond has a very high measure of stiffness. A cracker is stiff but not strong - it will break very easily. Jello is not stiff at all. Nylon is very strong, but not stiff at all! Steel is both stiff and strong. We build bridges and buildings out of materials that are both stiff and strong. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Cracker")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Jello")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Nylon")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "Steel", correct: "true")


#topic = FactoryGirl.create(:topic, name:"history of materials",  navgraphic: "navgraphics/history_of_materials_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"steel",  navgraphic: "navgraphics/steel.png", catagory_id: catagory.id, available: "yes")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"We all use steel", header:"We <span class='accent1'>all</span> use steel", section_image: "section_images/things_made_out_of_steel.png", image_position: "imagerightlarge", content: "Steel is a material that people in the modern world encounter every day. Steel is known for its <i>strength</i>, <i>toughness</i>, and <i>stiffness</i>. This unique combination of properties makes it ideal for building vehicles, structures, and tools. However, steel’s contribution to our world does not just stop there. You can find steel in countless household items including refrigerators, microwaves, paper clips and even the cans you might buy food in at the grocery store. Because of its wide-ranging uses, 1.3 billion tons of steel is produced every year. That is enough to make 21 trillion steel food cans, which, if stacked on top of one another, could reach the moon and back 7,000 times! Together, we will explore the chemistry of steel and find out why this material has such useful properties.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Steel’s key properties are strength, toughness, and stiffness", header:"Steel’s key <span class='accent1'>properties</span> are <span class='accent1'>strength</span>, <span class='accent1'>toughness</span>, and <span class='accent1'>stiffness</span>", section_image: "", section_image: "section_images/properties_of_steel.png", image_position: "imagerightmedium", content: "Steel is more than just a gray, shiny metal. It is also strong, tough and stiff &#8212; a combination of <i>properties</i> that makes steel ideal for many uses. When describing the properties of a material, the words strong, tough, and stiff have particular meanings. Let’s look at these properties one by one.<br><br>
If a material has the property of being <i>strong</i>, that means it can stand up to a lot of force. You exert a force on an object by either pushing or pulling on it. If you push on an object, it is under compression. If you pull on an object, it is under tension. Steel is strong under both tension and compression. Its strength makes steel an ideal material for things that have to support a lot of weight, like the columns and beams used in construction.<br><br>
If a material is <i>tough</i>, it can deform, or permanently change shape, without fracturing or breaking. With materials, the opposite of being tough is being brittle. A brittle material will break without first deforming under stress. A material can be strong and tough, like steel, or strong and brittle like a ceramic mug. A ceramic mug is strong. For example, you can put a lot of heavy items on top of a ceramic mug and it won’t break. But if you accidentally knock it off a counter, it will probably break when it hits the floor. A mug made out of steel, on the other hand, will not break if you knock it off the counter, although it might get a dent in it. This ability to deform without breaking makes steel handy for things like camping mugs and dishes. Toughness is also a critical property for things like car frames, which are designed to crumple to protect passengers. Toughness is also the property that makes steel an ideal material for things like staples, which are designed to bend and then hold that shape.<br><br>
If a material is <i>stiff</i>, it is not very stretchy. With materials, the opposite of being stiff is being flexible. If something is very flexible, that means it’s going to stretch under pressure, like when you pull on a rubber band. A material can be strong and stiff, like steel, or strong and flexible, like rubber. Rubber might be able to support a lot of weight, but you would not want to use it to build a bridge. A rubber bridge would bend under the weight of its users and maybe even under the force of just its own weight. Steel, on the other hand, is ideal for building large structures like bridges because it can support the force of the weight of its users without stretching down. Strong, tough and stiff, steel has a unique combination of properties, making it an ideal material for a wide range of uses, from staples to bridges.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Carbon makes steel strong and tough", header:"<span class='accent1'>Carbon</span> makes steel <span class='accent1'>strong</span> and <span class='accent1'>tough</span>", section_image: "", content: "Steel is an <i>alloy</i>, which is a material made up of a metal plus something else. That something else can be another metal or can be nonmetal. The two key elements of steel are iron, a metal, and carbon, a nonmetal. There are different types of steels, which depend on the amount of carbon and other elements present in the alloy. To understand steel’s behavior, we must look more closely at iron and carbon. <br><br>Steel is mostly iron, with a very small amount of carbon. Yet, thanks to carbon, steel can be 1,000 times stronger than pure iron! Adding carbon to iron makes steel stronger and tougher, but only up to a point. Iron with too much carbon will be strong, but instead of being tough, it will turn <i>brittle</i>. Different types of steel contain different amounts of carbon. An engineer, builder, or manufacturer must use the type of steel that has the right amount of carbon and therefore the right amount of strength and toughness for what she is building.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"The other elements in steel also affect steel’s properties", header:"The<span class='accent1'> other elements</span> in steel also <span class='accent1'>affect</span> steel’s <span class='accent1'>properties</span>", section_image: "section_images/stainless_steel_cuttlery.png", image_position: "imageleftlarge", content: "Although all steels contain carbon and iron, some steels also contain other elements that affect the steel’s properties. Many steels contain the elements nickel, manganese, chromium, and vanadium, which change the properties of the steels. For example, by adding a large amount of chromium, stainless steel can be made. Stainless steel has a very shiny finish and is highly resistant to <i>corrosion</i>, a gradual wearing away of a material. Stainless steel is used to make jewelry, silverware, surgical instruments, and other objects where the finish and non-corrosive attributes of stainless steel are desired. Stainless steel has even been used on the outside of some of the world’s tallest skyscrapers!")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"Steel has only been in wide usage for less than 200 years", header:"Steel has only been in <span class='accent1'>wide usage</span> for <span class='accent1'>less than 200 years</span>", section_image: "", content: "Steel made its earliest appearance around 1800 BCE. Ancient Rome, Greece, India, and China all used steel. In ancient times, steel was largely used for making weapons. Since steel is strong and can bend without breaking, a steel sword could be used in a sword fight without snapping. However because the methods used to manufacture steel were not very advanced, steel was not widely used prior to the 1800s. <br><br>Although steel was known in the ancient world, it started becoming widely used in the late 1800s. In 1856, Henry Bessemer patented the Bessemer process for manufacturing steel, which revolutionized the steel industry. The Bessemer process allowed steel to be mass-produced at low costs.")


section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"Today’s steel manufacturers can precisely control the amount of carbon in steel", header:"Today’s steel manufacturers can <span class='accent1'>precisely control</span> the amount of carbon in steel", section_image: "section_images/steel_manufacturing.png", image_position: "imagerightlarge", content: "To start the steelmaking process, iron must first be extracted from iron ore. An ore is a natural formation like a rock, which is partly made up of a mineral like iron. The process of getting a mineral out of rock is called smelting. When iron ore is smelted, the result is iron in a metallic form. This iron contains a high amount of carbon from the smelting process. But remember, the alloy of iron and carbon is only considered steel if the alloy has a particular range of carbon, typically under about 2%. Too much carbon and the metal will be brittle and therefore not steel. So the second step of making steel is to reduce the amount of carbon in the iron to the desired amount. Carbon is removed by blowing oxygen through molten, or melted, iron. The melting point of iron is 2800 °F (1538 °C), so the steelmaking process requires some pretty intense heat. <br><br>Today’s steel manufacturers are able to control exactly how much carbon remains in the steel. Thus, they can make different steels for almost any project and know precisely how each steel will behave. Whether we need steel with a tiny percentage of carbon for making car bodies or a steel with a larger percentage of carbon for making tools, steel manufacturers have the ability to produce it.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "seventh", main_idea:"Steel is a defining material of the modern world", header:"Steel is a <span class='accent1'>defining material</span> of the modern world", section_image: "", content: "From eating with stainless steel utensils, to driving around in vehicles built with steel parts, to going to school or work in buildings made with steel columns and beams, we benefit from steel every day. The ability to cost-effectively manufacture high-quality steel, with its unique combination of strength, toughness and stiffness has been critical to the development of our modern world. Our lives would simply not be the same without it. ")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What are three key properties of steel?", question_image: "section_images/things_made_out_of_steel.png", explanation: "Steel is strong, tough and stiff, which makes it ideal for many uses. If a material is Strong, it can stand up to a lot of force. If a material is Tough, it can deform, or permanently change shape, without fracturing or breaking. The opposite of being Tough is being Brittle. A brittle material will break without first deforming under stress. A material can be strong and tough, like steel, or strong and brittle like a ceramic mug. If a material is Stiff, it is not very stretchy. With materials, the opposite of being stiff is being flexible. If something is very flexible, that means it’s going to stretch under pressure, like a rubber band. A material can be strong and stiff, like steel, or strong and flexible, like rubber. Rubber might be able to support a lot of weight, but you would not want to build a bridge with it! ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Stiffness, Shiny-ness, and Weakness")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Strength, Toughness, and Stiffness", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Strength, high Melting Point, and Flexibility")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "What is added to Iron to make Steel?", question_image: "section_images/steelironplant.png", explanation: "Steel is an alloy, which is a material made from a metal plus something else. There are different types of steels, which depend on the amount of carbon and other elements present in the alloy. Steel is mostly iron, with a very small amount of carbon. Yet, thanks to carbon, steel can be 1,000 times stronger than pure iron. Adding carbon to iron makes steel stronger and tougher, but only up to a point. Iron with too much carbon will be strong, but instead of being tough, it will turn brittle. Different types of steel contain different amounts of carbon. An engineer must use the type of steel that has the right amount of carbon and therefore the right amount of strength and toughness for what she is building. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Helium")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Oxygen")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Carbon", correct: "true")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "What is stainless steel?", question_image: "section_images/stainless_steel_cuttlery.png", explanation: "Some steels also contain other elements that affect that type of steel’s properties. For example, stainless steel can be made by adding chromium. Stainless steel has a very shiny finish and is highly resistant to corrosion, which is the gradual wearing away of a material. Stainless steel is used to make jewelry, silverware, surgical instruments, and other objects where the finish and non-corrosive attributes of stainless steel are desired. Stainless steel has even been used on the outside of some of the world’s tallest skyscrapers! ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Steel that is really corrosive: prone to wearing away quickly")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Steel that is really dull to look at")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Steel with chromium added so that it has a very shiny finish and is highly resistant to corrosion", correct: "true")


#topic = FactoryGirl.create(:topic, name:"glass",  navgraphic: "navgraphics/glass_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"glass",  navgraphic: "navgraphics/glass.png", catagory_id: catagory.id, available: "yes")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Glass has very diverse uses in the modern world", header:"Glass has very <span class='accent1'>diverse uses</span> in the modern world", section_image: "section_images/examples_of_glass.png", image_position: "imagerightlarge", content: "You are probably quite familiar with the material known as glass. When you look out a window, you are looking through glass. When you watch something on television or a computer screen, you are looking at a glass screen. We often call something you drink out of “a glass” – even when it is made of plastic! <br><br> These are all examples glass made from <i>silica</i>, which you’ll learn is the main ingredient of sand. But, scientists refer to other materials as “glass,” too. Glass feels like a solid, but internally is a little bit like a liquid, because the molecules are arranged irregularly, or not in a pattern, inside. In this article we are focusing on what we normally think of as glass – the material made from silica.<br><br> Most of the examples above are probably items you think of as being fragile. If you knock a glass off a counter, it will likely break. So you might be surprised to learn that glass is also used in making things like fiberglass boats and fiber optic cables. Fiberglass boats and fiber optic cables are not fragile at all. These forms of glass have some different <i>properties</i> than the glass used for windows. In addition to everyday items like glasses and windows, glass has made some surprising contributions to the modern world. 
")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Key properties of glass include transparency, non-reactivity, brittleness, and strength in compression", header:"Key <span class='accent1'>properties</span> of glass include <span class='accent1'>transparency</span>, <span class='accent1'>non-reactivity</span>, <span class='accent1'>brittleness</span>, and <span class='accent1'>strength in compression</span>", section_image: "section_images/properties_of_glass.png", image_position: "imagerightmedium", content: "One of the most obvious physical properties of most glass is that it is <i>transparent</i>. You probably know that if something is transparent you can see through it. Something that is transparent allows light to pass through it. Glass transmits, reflects, and refracts (bends) light, instead of <i>absorbing</i> it. Because light passes through it, we can see what is on the other side of the glass. Being transparent makes glass an ideal material for windows or anything else we need to see through. <br><br> Another important property of glass is that it is <i>non-reactive</i>. Something <i>re</i>active can react with things it comes into contact with – like how iron can rust from exposure to air. Something that is <i>non</i>-reactive does not react with other things it comes into contact with. Because glass is non-reactive, if you put something in glass, like tomato sauce, the glass will not change the taste or composition of the sauce. That makes glass great for uses like storing food or chemicals. <br><br> Glass is also <i>brittle</i>. If something is brittle it will not bend before breaking if it experiences a large force, like getting knocked off a counter. That’s why people sometimes prefer to store food in plastic instead of glass.<br><br> Glass is strong under <i>compression</i> (pushing forces) and can hold a lot of weight. For example, you can stand on a floor made of thick glass, and it won’t break under your weight. Have you ever been in a glass-bottom boat? They actually exist! However, the glass used in things like drinking glasses and windows is not strong under <i>tension</i> (pulling forces). This type of glass would not be a useful material for making things like the chains on a swing, which get pulled when someone sits down on the seat.")


section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"Glass can be modified to change its properties", header:"Glass can be <span class='accent1'>modified</span> to change its <span class='accent1'>properties</span>", section_image: "section_images/regular_and_safety_glass.png", image_position: "imagerightmedium", content: "Like other materials, glass can be modified to change its <i>properties</i>. A material’s properties can be changed by heating, cooling, or <i>working</i> (which means doing something to it, like hammering or stretching) the material. You can also change the properties of a material by adding other ingredients to it.<br><br> One example of glass with modified properties is <i>safety glass</i>. If you have ever broken a drinking glass, you know that it breaks into lots of different sized pieces, some of which can be very large and sharp. You can image how dangerous that kind of glass would be in a car accident. Instead, car windows are made from safety glass.  Both thermal (heat) and chemical treatments are used to make safety glass.  The result is that the outer surfaces of the safety glass are in <i>compression</i> (being pushed in) and its inner surfaces are in <i>tension</i> (being pulled out). The stress is balanced between the molecules, causing the glass to shatter evenly. This makes the glass harder and causes it to shatter into very small pieces. So, if your car’s front windshield is broken in accident, it will shatter evenly into small pieces instead of large dangerous shards. That makes safety glass a much safer material for a car windshield.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"Glass fibers are a glass-based material with an additional key property: tensile strength", header:"Glass <span class='accent1'>fibers</span> are a glass-based material with an additional key property: <span class='accent1'>tensile strength</span>", section_image: "section_images/fiberglass_and_glass_wool.png", image_position: "imageleftmedium", content: "Glass fibers are long, thin strands of glass. Glass fibers are made by heating and stretching glass into very thin strands, or “fibers”. Unlike regular glass, glass fibers have a lot of <i>tensile strength</i>. A material with high tensile strength can withstand being pulled really hard before breaking. <br><br> One use of glass fibers is as a material for insulating buildings. Insulating materials help to slow heat from moving. A home that is insulated will stay cooler in the summer and warmer in the winter. For insulating materials, flexible glass fibers are intertwined into a form sometimes called “glass wool”. If you have ever seen insulating material, it does kind of look like fabric, doesn’t it? The glass fibers trap blocks of air. Gases like air do not conduct heat easily. Glass wool insulation traps air, which makes it an excellent heat insulator. <br><br> Another material made with glass fibers is fiberglass. Fiberglass is plastic reinforced with glass fibers. Fiberglass is widely used as a reinforcement material because of its strength. Items reinforced with fiberglass include circuit boards for televisions, radios, and computers. It is also used to reinforce the shells of pools, bathtubs, and boats – not things we typically think of as being made with glass! Although fiberglass contains glass, it has different properties than what we normally think of when we think of glass. Glass fibers used for reinforcement material or insulation do not require transparency, unlike so many other uses of glass.
")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"Optical fibers are glass fibers used to transmit light", header:"<span class='accent1'>Optical fibers</span> are glass fibers used to <span class='accent1'>transmit light</span>", section_image: "section_images/fiber_optic_cable_graphic.jpg", image_position: "imagerightlarge", content: "Glass fibers that <i>do</i> utilize the transparency property of glass are called optical fibers.   Optical fibers are long, thin glass threads that are used to transmit light. Each thread is as thin as human hair. Threads that are grouped into bundles are called fiber optic cables. These cables are used to transmit light, just like a window transmits light. The light that is transmitted represents data that is moving through the wire as a series of light signals. That data might be a conversation you are having on the phone, a text message you are sending, or a video you are streaming online. <br><br> Light travels through the center of the fiber optic cable by bouncing off the insides of the cable. Light can travel great distances through fiber optics because the inside of the cable does not absorb any light. Only impurities in the glass cause the light signal to degrade.<br><br> Fiber optic cables are replacing the copper wires that were historically used for transmitting data. Fiber optic cables are cheaper, thinner, more flexible, and more lightweight than copper. They also transmit data faster than copper can. Not all communications data is sent over optical fibers. However where optical fibers are used, there is a significant improvement in the capacity and speed of transmitting that data.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "seventh", main_idea:"The main ingredient of glass is the main ingredient in sand", header:"The main <span class='accent1'>ingredient</span> of glass is the main ingredient in <span class='accent1'>sand</span>", section_image: "section_images/sand_castle.jpg", image_position: "imagerightlarge", content: "Glass is used for many things in the modern world from windows to insulation and communication cables. Part of the success of glass has to do with the fact that it is inexpensive to make. It is inexpensive to make because the ingredients for glass are so abundant. The main ingredient in most glass is a compound called silicon dioxide, also known as silica. If you have ever been to the beach or played in a sandbox, you are actually pretty familiar with silica, because it is also the main ingredient in sand. Sand and glass look nothing alike, but sand heated up to very high temperatures forms glass! <br><br> To make glass, other ingredients are added to the silica sand. These ingredients are added to change and improve the properties of the glass. For example, something called sodium carbonate lowers the temperature required to make glass. Lead oxide makes glass softer so it is easier to cut, and is also what causes crystal glassware to sparkle. Chemicals can also be added to change the color of glass. The mixture is then heated to high temperatures to melt and become glass.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "eighth", main_idea:"Glass is found in nature", header:"<span class='accent1'>Glass</span> is found in <span class='accent1'>nature</span>", section_image: "section_images/obsidian_samples.png", image_position: "imagerightlarge", content: "Before people began <i>making</i> glass, they used glass that was made naturally. Because glass is sand heated to very high temperatures, glass can found in nature near very hot sources. One example of naturally occurring glass comes from lightning striking sand. Another source is volcanoes. Obsidian is one type of volcanic glass that was used in ancient times to make arrowheads, knives, and jewelry. Obsidian is still used in jewelry today. Although transparency is one of the key properties of much of the glass we use today, glass does not have to be transparent. For example, obsidian is often black and might look more like a shiny rock than a type of glass. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "ninth", main_idea:"Glass is a critical material for building and communicating", header:"Glass is a critical material for <span class='accent1'>building</span> and <span class='accent1'>communicating</span>", content: "Glass has very diverse uses. We have relied on glass windows to bring natural light into our homes, schools, and businesses for centuries. More recently, we have also come to rely on glass fibers to move massive amounts of data around the world. Sometimes the use of glass is obvious. When you use a drinking glass or look out a window, you know that you are using glass. Other times, glass is hidden in fiberglass insulation or in the fiber optic cables we use to communicate. Now that you know its many uses, you may never see (or see through) glass the same way again!")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What are some properties of glass in its typical form?", question_image: "section_images/properties_of_glass_nohints.png", explanation: "Key properties of glass include transparency, non-reactivity, brittleness, and strength in compression. Glass transmits, reflects, and refracts (bends) light, instead of absorbing it, so we can see through it. Transparency makes glass great for windows. Glass is non-reactive - it does not react with other things it contacts - which makes glass great for storing food or chemicals. Glass is also brittle: it will break if it experiences a large force. Glass is strong under compression: it can hold a lot of weight, and you you can stand on a floor made of thick glass. However, glass used in drinking glasses is not strong under tension, or pulling forces. It would be a poor material for the chains on a swing, which get pulled when someone sits down on the seat. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Non-reactivity: Glass does not react to things it comes in contact with")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Brittleness: it will break if it experiences a large force, like being dropped on a floor")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Strength under compression: It can hold a lot of weight")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "Transparency: You can see through it")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_e.png", answer_content: "All of the above", correct: "true")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "What are glass-related materials used for?", question_image: "section_images/examples_of_glass.png", explanation: "Glass has very diverse uses. Glass feels like a solid, but internally is a little bit like a liquid, because the molecules are arranged irregularly - not in a pattern - inside. Many examples of glass you may think of may be fragile. You might be surprised to learn that glass is also used to make things like fiberglass boats and fiber optic cables. Fiberglass boats and fiber optic cables are not fragile at all. These forms of glass have some different properties than the glass used for windows.  ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Fiber optic cables for computer networks")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Boats")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Windows")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of the above are uses of glass materials", correct: "true")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "What is the main ingredient in glass?", question_image: "section_images/sand_castle.jpg", explanation: "The main ingredient in most glass is a compound called silicon dioxide, also known as silica. Silica is also the main ingredient in sand. Sand and glass look nothing alike, but sand heated up to very high temperatures forms glass! To make glass, other ingredients are added to the silica sand. These ingredients are added to change and improve the properties of the glass. Chemicals can also be added to change the color of glass. The mixture is then heated to high temperatures to melt and become glass. Because glass is sand heated to very high temperatures, glass can found in nature near very hot sources. One example of naturally occurring glass comes from lightning striking sand.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Aluminum: the most abundant element in the earth's crust")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Titanium: a metal that is as strong as steel, but 45% lighter")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Silica: the main ingredient in sand", correct: "true")



#topic = FactoryGirl.create(:topic, name:"plastics",  navgraphic: "navgraphics/plastics_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"plastics",  navgraphic: "navgraphics/plastics.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Plastic is used in items as different as toys and spaceships", header:"Plastic is used in items as different as <span class='accent1'>toys</span> and <span class='accent1'>remote controls</span>", section_image: "section_images/plastic_truck_rc.png", image_position: "imagerightsmall",content: "Have you ever wondered why items as different as dolls and remote controls can both be made out of the same material? The glasses you see through, shoes you wear, and pen you use are all likely made of <i>plastic</i>. Plastic can be easily molded into different shapes. This ability allows plastics to be found in so many products. We know that plastic shows up everywhere. Now it’s time to explore why.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Plastics are modern, man-made materials that can be molded into different shapes", header:"Plastics are modern, <span class='accent1'>man-made</span> materials that can be <span class='accent1'>molded</span> into different shapes", content: "We use the word plastic to refer to a range of <i>synthetic</i>, or man-made, materials. Plastic is lightweight, durable, and inexpensive. We often use plastics as a replacement for other types of materials. For example, vinyl, a plastic product, is often used to replace more expensive <i>leather</i>. Some furniture, shoes, and clothes are made of vinyl. <br><br>We also use plastic as a replacement for <i>glass</i>. Some examples are plastic water bottles and plastic lenses for your glasses. Compared to glass, plastic is lighter and will not break. Plastic can be a replacement for <i>wood</i>. Some people use plastic instead of paper bags, because plastic is strong and does not absorb moisture. Finally, we use plastic to replace <i>steel</i>, because it is lightweight and durable.  Some companies make plastic silverware instead of stainless steel silverware or plastic parts instead of steel parts for cars.<br><br>We use plastics to make some things that just cannot be made with other materials. There are lots of different kinds of plastics. Just remember that all plastics share some key <i>properties</i>.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Plasticity, the ability to change shape when force is applied, is a key behavior of plastic", header:"<span class='accent1'>Plasticity</span>, the ability to <span class='accent1'>change shape</span> when force is applied, is a key behavior", section_image: "section_images/plastic_containers.png", image_position: "imageleftsmall", content: "The word plastic comes from the Greek word <i>plastikos</i>. Plastikos means capable of being shaped or molded. Plasticity - the ability to permanently change shape when a force is applied - is a behavior all plastics have. Because they easily deform under compressive stress, plastics can be made into almost any shape imaginable.<br><br>Plastic has the properties we want in a product. As good <i>insulators</i>, plastics conserve energy. This property is useful in refrigerators and air conditioners. The containers inside your refrigerator are also likely made of plastic. This plastic does not <i>react</i> with your food. It keeps air out and food fresh. It is also transparent so you can see the food. Many plastics are lighter today. Plastic bottles, for example, are 25 percent lighter than they were in the 1970s.  <br><br>Another important property is <i>durability</i>. Plastics are made to last. Their chemical bonds slowly degrade in nature. Plastic bottles can last between 450 and 1000 years. That means that a bottle you drank out of today could still be around in the year 3000! A plastic toy will not break when dropped and the plastic parts of your refrigerator are going to last.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:" Plastics are carbon-based polymers", header:" Plastics are <span class='accent1'>carbon</span>-based <span class='accent1'>polymers</span>", section_image: "section_images/plastic_polymer_ex.jpg", image_position: "imagerightmedium", content: "What makes something a plastic? Well, all plastics are carbon-based polymers. Every plastic is a <i>polymer</i>: a long chain of molecules that repeat. There are lots of other polymers in the world. DNA, the building block of all life, and proteins are both polymers. The difference is that plastic polymers are mostly made of <i>carbon</i> atoms. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"Most plastic is made from oil and natural gas", header:"Most plastic is made from <span class='accent1'>oil</span> and <span class='accent1'>natural gas</span>", content: "It is amazing to see the final products that are made out of different raw materials. For example, you might know that paper (even toilet paper!) is made from trees. Metals come from ores often found in rocks. But did you know that most plastic is made out of oil and natural gas? We refer to oil and natural gas as <i>fossil fuels</i>. They are the remains of plants and animals that lived millions of years ago. We don’t just use these fossil fuels to power machines and heat our homes. We use parts of these fossil fuels to produce plastic. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"tbd", header:"Plastics contain <span class='accent1'>other materials</span> that affect their <span class='accent1'>properties</span>", content: "Plastics can also contain other organic or inorganic compounds. Most plastics used today have had a filler, plasticizer, or colorant added. <i>Fillers</i> enhance the properties of plastic. Flame retardants, for example, are added to make plastic less flammable. Fillers are also used to lower the cost of production. <i>Plasticizers</i> are oily compounds that reduce how rigid plastic is. <i>Colorants</i> change the color of plastic.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"Plastics can be classified by their structure and behavior", header:"Plastics can be classified by their <span class='accent1'>structure</span> and <span class='accent1'>behavior</span>", content: "There are many different kinds of plastics. Two important groups to know are <i>thermoplastics</i> and <i>thermosets</i>. Thermoplastics do not go through a chemical change when made. They can be melted and remolded. Polystyrene, which we know as <i>styrofoam</i>,  and nylon are both thermoplastics. Most of the plastics we use are thermoplastics. <br><br>Thermosets do undergo a chemical change. Consequently, they cannot return to their original state. Making a thermoset plastic is like baking a cake. The molded plastic or the “cake” is the final product. It cannot return to what it was before. <br><br>A few additional methods for grouping this material include deciding if the plastic is natural or manmade. You can also categorize plastics by how degradable they are. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"We have changed natural plastics and invented synthetic ones", header:"We have <span class='accent1'>changed natural</span> plastics and <span class='accent1'>invented synthetic</span> ones", section_image: "section_images/plastics_uses.png", image_position: "imagerightsmall", content: "The history of plastic includes examples of many common plastics. To improve this material, humans have changed plastic in many ways. Plastic’s development has three main parts. First, over 5,000 years ago, natural plastic substances were used. The first chewing gum was actually a natural plastic made from the tar of birch trees. Yum! Ancient Mesoamericans would make balls and sandals from natural rubber. <br><br>Then, beginning in the Middle Ages, humans began chemically changing natural plastics. People of this time made a type of plastic by treating cattle horns with lye. During the Industrial Revolution, <i>vulcanization</i> was invented. Vulcanization is a chemical process to harden rubber. After vulcanization, the plastic has greater chemical resistance and a smooth, soft surface. Vulcanization allows rubber to be used as a material for tires on bikes and motorcycles.<br><br>The last major plastic development was the creation of completely man-made plastics. The first man-made plastic dates back to 1856. This plastic, called Parkesine at the time, but celluloid in modern times, is made of cellulose (wood fibers) and nitrate. The cellulose nitrate is dissolved in solvent, then hardened. It forms an elastic, transparent material which can be molded when heated. Buttons and combs are made of parkesine. Bakelite, invented in 1907, was the first synthetic plastic. Synthetic means unnatural. Synthetic plastics are made out of fossil fuels rather than plants or animals. <br><br>Many plastics used today are man-made. The most popular include: <i>polystyrene</i>, <i>polyester</i>, and <i>nylon</i>. Polystyrene is used to make disposable cutlery and for protective packaging. Fabric often contains polyester. Nylon is found in cloth, cookware, screws, and bolts. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"Plastics are molded into the durable, diverse items we desire", header:"Plastics are molded into the <span class='accent1'>durable</span>, <span class='accent1'>diverse</span> items we desire", content: "Over time, the role of plastics in our world has grown immensely. People used to make simple toys and trinkets out of plastic. Now, it plastic is found in a majority of everyday items. Perhaps you were just sitting on a plastic chair or reaching into your plastically-insulated fridge. It is obvious that this material shows up everywhere. Plastics are molded into the durable, diverse items we need and want. ")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What is a key defining behavior of a plastic?", question_image: "section_images/plastic_169794539.jpg",explanation: "The word plastic comes from the Greek word plastikos. Plastikos means capable of being shaped or molded. Plasticity - the ability to irreversibly deform, or permanently change shape when a force is applied, without breaking - is a behavior all plastics have. Because they easily deform under compressive stress, or are “malleable”, plastics can be made into almost any shape imaginable.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Conductivity: The ability for a material to conduct an electric current")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Density: The amount of heaviness of something compared to its size")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Plasticity: The ability to change shape when force is applied", correct: "true")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "Which of the following is a type of plastic?", question_image: "section_images/plastic_169794539.jpg",explanation: "All of these are types of plastics. Polystyrene is used to make disposable cutlery and for protective packaging. Fabric often contains polyester. Nylon is found in cloth, cookware, screws, and bolts.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "rubber")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "polystyrene")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "nylon")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "all of the above", correct: "true")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "What is vulcanization?", question_image: "section_images/plastic_169794539.jpg",explanation: "Vulcanization is a chemical process to harden rubber. After vulcanization, the plastic has greater chemical resistance and a smooth, soft surface. Vulcanization allows rubber to be used as a material for tires on bikes and motorcycles.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "a chemical process that makes a harder type of rubber", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "a modern way to degrade plastic materials")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "a technique used to separate two different plastics")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "a physical process that alters the properties of natural plastic")


#topic = FactoryGirl.create(:topic, name:"concrete",  navgraphic: "navgraphics/concrete_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"concrete",  navgraphic: "navgraphics/concrete.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Cement holds different material together and is a key  ingredient in concrete", header:"<span class='accent1'>Cement</span> holds different material together and is a key ingredient in <span class='accent1'>concrete</span>", section_image: "section_images/Buffalo_City_Court_Building,_1971-74,_Pfohl,_Roberts_and_Biggie.jpg", image_position: "imagerightsmall", image_caption: "Buffalo City Court Building. &#169; Pfohl, Roberts and Biggie/Wikimedia Creative Commons 2.0 Generic license", content: "Engineers use many different materials. Your house is made of cement, wood, and glass, among other things. Now these materials do not magically stick to one another. An engineer must find a material to hold any structure together. For many building projects, this connecting material is cement.  Cement is a grey powder made out of limestone and clay which must be mixed with water to harden.  Just think of cement as a glue. It holds different materials together.<br><br>Concrete and cement have allowed countries to build beautiful structures and durable buildings. These two materials are often confused with one another. It is important to remember that cement and concrete are not the same thing. They do, however, have similarities.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:"Cement is the main ingredient of concrete", header:"Cement is the <span class='accent1'>main ingredient</span> of concrete", section_image: "section_images/redbrickwall_155114558.jpg", image_position: "imageleftmedium", image_caption: "The bricks of this wall are held together with cement mortar. The actual bricks are made of concrete. &#169; kevin brine/Shutterstock", content: "Cement is the main ingredient of concrete. Cement combined with sand, gravel, and water forms concrete. In concrete, the cement binds the materials together.<br><br>When first formed, concrete is in a liquid form. It can easily be shaped. Like cement, concrete is a strong building material. Both are durable and have been used since ancient times. Concrete is the most used construction material in the world. Many dams, highways, and bridges are made of concrete. Most concrete contains Portland cement. An exception is roads. They are made of asphaltic concrete.  Asphaltic concrete is commonly known as asphalt. It is a mixture of asphaltic cement and other materials, such as sand, stone, and gravel. <br><br>Cement is also used in mortar. Mortar is a paste that binds building materials together. We said earlier to think of cement as a glue. Mortar is what allows cement to act as a glue. Mortar is a mixture of cement and crushed stone or sand. Bricks and stones are held together with cement mortar. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Cement was used in Ancient times, but Portland cement is relatively new", header:"Cement was used in <span class='accent1'>Ancient</span> times, but <span class='accent1'>Portland cement</span> is relatively <span class='accent1'>new</span>", section_image: "section_images/512px-Pantheon_dome.jpg", image_position: "imagerightmedium", image_caption: "Misleadingly low, the Pantheon's exterior dome steps outwards as it meets the uppermost ring of the drum. &#169; Anthony M. from Rome, Italy/Wikimedia Creative Commons 2.0 Generic license", content: "Incredibly old and beautiful structures were built with the help of cement and concrete. The Ancient Egyptians, Greeks, and Romans built with this material. Cement mortar, which pastes stones, bricks, and concrete together, is a very old material. The Coliseum and Egyptian Pyramids are held together with cement mortar. <br><br>A major difference between ancient and modern concrete is their cure time. Cure time is how long a material takes to completely harden. The cement ancient Romans used could take up to two years to completely harden. Modern concrete, by comparison hardens in days or even a few hours. This fast curing time helps construction to occur quickly. A downside is that when concrete cools too quickly, it contracts and cracks. These cracks are caused by a type of stress called thermal stress and they make concrete less durable. Thermal stress occurs when a material is heated and cooled too quickly. <br><br>Remember that ancient Roman buildings still stand thousands of years later because they are extremely durable. Concrete structures made today will likely not last more than 100 years. <br><br>Just as modern concrete is different, cement has changed.  In the 1820s, Joseph Aspdin, a British stonemason, wanted to create a better cement. To do this, Aspdin heated limestone and clay on his kitchen stove. He then ground the mixture into a powder. This formed the first hydraulic cement. Hydraulic cement is just a fancy term meaning cement that hardens in water. <br><br>Aspdin’s new material, which he named Portland cement, has been a reliable and popular building material. Portland cement is good because it dries hard and quickly. This allows construction to happen quicker.<br><br> We often use Portland cement, but we manufacture it in a different way. It is no longer made on a kitchen stove out of limestone and clay. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"Raw materials are ground, blended, and heated to make cement", header:"Raw materials are <span class='accent1'>ground</span>, <span class='accent1'>blended</span>, and <span class='accent1'>heated</span> to make cement", section_image: "section_images/256px-Stockage_de_ciments.JPG", image_position: "imageleftmedium",  image_caption: "Construction in Tunisia. &#169; Oussama zrafi/Wikimedia Creative Commons Attribution-Share Alike 3.0 Unported license", content: "Modern cement is made in three steps: grinding, blending, and heating.  Cement is a combination of many different elements. The necessary elements are found in limestone, sand and clay. These elements are calcium, aluminum, iron, and silicon. <br><br>Dry cement and wet cement can be made. In the dry method, the raw materials are first ground into smaller pieces. The pieces are then blended together. Finally, the mixture is heated in a kiln. <br><br>In the wet method, water is added to the raw materials before they are ground. Next, they are blended together and heated. The wet process uses more energy. This is because more water must be evaporated from the cement. The dry process is therefore favorable because it requires less energy. <br><br>Both dry and wet cement are heated to over 2700℉. At this high temperature, chemical reactions occur, fusing the materials together. <br><br>The result is cement clinkers. Clinkers are little grey balls. The clinkers are removed from the kiln and cooled. Then the clinkers and gypsum, a mineral, are ground together into a powder.  Each piece of the powder is so small that it could pass through a mesh sieve. This powder is cement.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"Cement is durable, and its strength can be controlled", header:"Cement is <span class='accent1'>durable</span>, and its strength can be <span class='accent1'>controlled</span>", section_image: "section_images/USMC-110806-M-IX060-148.jpg", image_position: "imagerightmedium", image_caption: "A soldier with 84th Battalion, 30th Brigade, 643rd Company from Schofield Barracks, Hawaii, empties a bag of cement that will be mixed into brick mortar during the Engineering Civic Action Program portion of Exercise Khaan Quest 2011 in Ulaanbaatar, Mongolia, Aug. 1. The purpose of the program is to improve medical care in the area by adding on to the Ayut Family Hospital, a 17,000 sq. ft. urgent care clinic, which will serve the 9th sub-district of khaan-Uul District. Public domain image.",content: "Cement is extremely durable. To recognize how long cement lasts, just look to the Ancient world. The Pantheon in Rome is the world’s largest unreinforced concrete dome. It is over 2000 years old and relies on cement, the key ingredient of concrete.  <br><br>High Performance Concrete bridges also exhibit this durability. Made of Portland cement, these bridges last for 100 years. They can withstand extreme weather and harmful chemicals.  <br><br>Unlike its durability, cement’s strength is easily controlled. It is dependent on the amount of water added to it. Maximum strength occurs when 2.8 gallons of water are added to each sack of cement. Such strength, however, has a drawback. At its maximum strength, cement has a high viscosity. Viscosity means the resistance to flow, so something with a high viscosity will not flow easily. For example, honey has a high viscosity, which means that it sticks together and flows slowly. Water has a low viscosity and easily flows.  <br><br>Cement’s high viscosity makes it difficult to use. When dealing with cement, builders must decide what balance of strength and viscosity is ideal. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"Cement can be improved to help the environment", header:"Cement can be <span class='accent1'>improved</span> to help the <span class='accent1'>environment</span>", content: "Cement is a strong building material and the key ingredient of concrete.  Its impact spans from Ancient Rome to Modern America. This material, however, could be improved. <br><br>Cement production releases carbon dioxide - CO2 - into the atmosphere. This is bad for the environment. CO2 is considered a greenhouse gas that contributes to global warming. It also takes a large amount of energy to make cement. Over time, companies have improved their manufacturing process. Eco-cement, for example, absorbs CO2 while it hardens. Such reabsorption is better for the environment and is more energy efficient. <br><br>Remember that any building material can be enhanced. Perhaps you will be the one to create a completely  environmentally-friendly cement!")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "How did ancient civilizations use cement?", question_image: "section_images/512px-Pantheon_dome.jpg", explanation: "Incredibly old and beautiful structures were built with the help of cement and concrete. The Ancient Egyptians, Greeks, and Romans built with this material. Cement mortar, which pastes stones, bricks, and concrete together, is a very old material. The Coliseum and Egyptian Pyramids are held together with cement mortar.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "the Native Americans made cement houses")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "the Roman Empire made many buildings out of cement and concrete, such as the Pantheon", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "cement did not exist in the ancient world")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "cement was used to make most weapons")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "What is mortar?", question_image: "section_images/redbrickwall_155114558.jpg", explanation: "Mortar is a paste that binds building materials together. You can think of cement as a glue. Mortar is what allows cement to act as a glue. Mortar is a mixture of cement and crushed stone or sand. Bricks and stones are held together with cement mortar.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "the main ingredient of cement")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "a paste made out of cement and crushed stone or sand", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "a type of concrete")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "What is a difference between cement and concrete?", question_image: "section_images/Buffalo_City_Court_Building,_1971-74,_Pfohl,_Roberts_and_Biggie.jpg", explanation: "Cement is the main ingredient of concrete. Cement combined with sand, gravel, and water forms concrete. In concrete, the cement binds the materials together.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "There is no difference. Cement is another word for concrete")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Cement is the key ingredient of concrete. ", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Concrete is the key ingredient of cement.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "Cement is used to make houses and bridges, while concrete is not.")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "4", question_content: "Cement is: ", question_image: "section_images/USMC-110806-M-IX060-148.jpg", explanation: "Cement is extremely durable, and its strength can be controlled. To recognize how long cement lasts, just look to the Ancient world. The Pantheon in Rome is the world’s largest unreinforced concrete dome. It is over 2000 years old and relies on cement, the key ingredient of concrete. Unlike its durability, cement’s strength is easily controlled. It is dependent on the amount of water added to it. Maximum strength occurs when 2.8 gallons of water are added to each sack of cement. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "durable", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "always strong")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "a white powder")



#topic = FactoryGirl.create(:topic, name:"semiconductors",  navgraphic: "navgraphics/semiconductors_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"silicon",  navgraphic: "navgraphics/silicon.png", catagory_id: catagory.id)
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "first", main_idea:"Silicon is found in sand and in our computers", header:"Silicon is found in <span class='accent1'>sand</span> and in our <span class='accent1'>computers</span>", section_image: "section_images/pertable_107507240.png", image_position: "imagerightmedium", content: "Silicon is the second most common element on Earth. You might have noticed this element on the periodic table, as <i>Si</i>. <br><br>Silicon has many different functions. You stand on it at the beach. Heated up, silica sand forms glass. This same material allows our computers to work. Silicon is a building block. It is used to make bricks and electronics. This material supports our tech world today. It also has a place in the electrical and medical worlds of our future.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "second", main_idea:" Silicon is a good semiconductor, a material that sometimes conducts electricity", header:" Silicon is a good <span class='accent1'>semiconductor</span>, a material that <span class='accent1'>sometimes conducts</span> electricity", section_image: "section_images/transistors_132844529.jpg", image_position: "imageleftsmall", content: "A semiconductor is a material that sometimes conducts electricity and sometimes does not. Silicon is a <i>metalloid</i>; something between a metal and a non-metal. Like a metal, silicon conducts electricity. However, it only conducts if the voltage is high enough. Otherwise, it does not. This makes it a <i>semiconductor</i>.<br><br>Unlike most metals, silicon becomes a better conductor as temperatures rise. A silicon semiconductor is used in <i>transistors</i> to switch electrical currents.<br><br>Transistors were made of germanium until the 1950s. Then, silicon took over. Silicon transistors are superior. Silicon is physically strong. It becomes a better electrical conductor at higher temperatures. Therefore, if a silicon transistor heats up, it can still operate. Thanks to silicon, we can control the electrical conductivity of a transistor. Before silicon can become an effective conductor, it must first be chemically altered. To do this, we add <i>impurities</i>. Small amounts of other elements are hurled at silicon. These elements bond to the silicon and free some electrons. The free electrons can now move throughout the silicon. They carry the electric current.<br><br>Transistors are the building blocks of modern calculators, cell phones, and computers. As you can imagine, silicon is extremely important in this age of technology.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "third", main_idea:"Many Silicon Valley companies use silicon in their technology products", header:"Many <span class='accent1'>Silicon Valley</span> companies use silicon in their <span class='accent1'>technology</span> products", section_image: "section_images/microprocessor_166751039.jpg", image_position: "imagerightsmall", content: "The area of Silicon Valley is named after silicon.  Silicon plays a large role in the tech world. This region is home to many famous companies. Apple, Facebook, and Intel operate here. The Silicon Valley is the largest high tech manufacturing area in the U.S. It has the highest average salary for tech jobs. Consequently, the Silicon Valley is known to be a center for innovation and success. And guess what! The transistor, which relies on silicon, is the historic backbone of Silicon Valley. <br><br>In 1974, Intel released the first usable microprocessor. Think of a microprocessor as a “computer on a chip”. This chip contained all of the main functions of a computer on one tiny circuit. Silicon was the backbone of this chip. Today, computers and even smartphones contain these chips. <br><br>Transistors are an important part of microchips. Microchips are made of transistors. The transistors do the computing work of a chip. A transistor acts like a switch. It can be turned on and off. Everything on a chip is also attached to silicon. It acts as a good semiconductor. <br><br>With new advances, chips and transistors have shrunk. A chip used to only hold a few dozen transistors. Today, some chips contain several billion!  And keep in mind that most chips are the size of a grain of rice. Also, the transistors on these chips are so small that they are invisible to the naked eye. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fourth", main_idea:"Different forms of silicon are used in construction and manufacturing", header:"Different <span class='accent1'>forms</span> of silicon are used in <span class='accent1'>construction</span> and <span class='accent1'>manufacturing</span>", section_image: "section_images/concrete_glass_bldg_137458115.jpg", image_position: "imageleftmedium", content: "In nature, you will find <i>silicate</i> materials. These are often used in construction. Silicate is made of <i>silicon</i> and <i>oxygen</i>. It makes up 90% of the Earth’s crust. You can find this material in cement and concrete. Many houses contain a good deal of silicate. <br><br>Silica is also made of silicon and oxygen. It is the main ingredient of traditional glass, optical fibers, and fiberglass. The windows of your house and glass items inside are made of silicon.<br><br>Silicon can also be made into polymers. Polymers are large molecules made of repeating monomers. Silicon polymers are called <i>silicones</i>. Silicones are used to bond glass to other compounds. Silicones have many important functions. They can be used as waterproof treatments and mechanical seals. Silicones can also be found in explosives and contact lenses.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "fifth", main_idea:"Silicon will be used in electronics and medicine of the future", header:"Silicon will be used in <span class='accent1'>electronics</span> and <span class='accent1'>medicine</span> of the future", section_image: "section_images/compsgps_300978869.jpg", image_position: "imagerightsmall", content: "The chemist Jons Jacob Berzelius first isolated silicon in 1824. He heated silica with potassium to obtain pure silicon. Today, we get silicon by heating silica with carbon. Sand is used, since silica and silicon are the main ingredients of sand. <br><br>Silicon is a good material to use in electronics is because it resists heat well. If a computer heats up, then the silicon will not overheat. For this same reason, silicon is used in simpler products that encounter heat. A few examples are oven mitts and baking sheets. <br><br>Looking forward, silicon has a place in our future. New electronic gadgets will contain silicon. The latest computer or GPS will run on a silicon chip.<br><br>In the medical field, doctors are experimenting with using electronic devices. These could possibly treat disorders in the brain. A new technology is the “neuro-chip”. The neuro-chip is a  silicon chip attached to a brain cell. More than 16,000 transistors fit onto this tiny “neuro-chip”. Also, neuro-chips can help with the screening of drugs. <br><br>Silicon is also used to create <i>nanoneedles</i>. These needles are so tiny that they can be inserted into the nucleus, or center, of a cell. Biologists use nanoneedles to deliver compounds to cells. Proteins can be delivered with nanoneedles. This is helpful for tracking and treating diseases. Biodegradable silicon is used to make the needles. This lets them decay in the body. Such decay ensures that no harmful toxins will be remain to hurt a patient.  ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking: "sixth", main_idea:"Silicon allowed our lives to advance", header:"Silicon allowed our lives to advance", content: "Silicon has allowed our lives to advance. Technology now works better and quicker. The companies of the Silicon Valley rely on silicon. If you use modern technology, you do as well. Whether you cruised the web or stood in a concrete building today, you benefited from silicon.")
#topic = FactoryGirl.create(:topic, name:"silicon",  navgraphic: "navgraphics/silicon.png", catagory_id: catagory.id, available: "no")


question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "Which of the following does not contain silicon?", question_image: "section_images/silicon_examples.png",explanation: "Silicon is found in many useful places. You can find it on the beach as silica sand. You can find it in silicone form in contact lenses and other places. Silica is a key component of both glass and concrete. Silicon is an incredibly useful element in our modern world!")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "silica")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "silicones")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "glass")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "metal roofs", correct: "true")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "How did Silicon Valley get its name?", question_image: "section_images/silicon_examples.png",explanation: "Silicon Valley was so named during the early days of electronics and computing. Early discoveries in transistors and semiconductors took place in the Silicon Valley area, and ended up creating a rich, innovative environment in which many new companies and inventions are still made.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "It is the center of the US economy")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Silicon was first discovered in this area")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "It is an important high-tech center in the US, and silicon plays an important role in electronics and computing", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "A controversial court case about the environmental impacts of silicon usage occurred here")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "How is silicon used in construction?", question_image: "section_images/silicon_examples.png",explanation: "Silicate is made of silicon and oxygen. It makes up 90% of the Earth’s crust. You can find this material in cement and concrete. Many houses contain a good deal of silicate. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "as a type of “super” glue")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "to make cement, stucco, and bricks", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "to coat drainpipes")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "in the thick, long-lasting paint used on tall buildings")

topic = FactoryGirl.create(:topic, name:"metal alloys",  navgraphic: "navgraphics/metal_alloys_coming_soon.png", catagory_id: catagory.id, available: "no")
