# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#### Everything for Structures
catagory = Catagory.create(name:"Structures", navgraphic: "navgraphics/structures.png", headergraphic: "structures", color: "structures", video:"//www.youtube.com/embed/kWsXIIqVy_Q", keypoints: "structures main point one.", game_name:"bridge_game.js")


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "first", main_idea:"A structure is something that has parts put together in a particular way and is load bearing", header:"A structure is something that has <span class='accent3'>parts</span> put together in a <span class='accent3'>particular way</span> and is <span class='accent3'>load bearing</span>", section_image: "section_images/boy_using_tablet_in_car.png", image_position: "imagerightsmall",content: "Are you at home sitting on a chair looking at your iPad? Or maybe you are at the library sitting at a desk watching on a computer. You might even be in a car or an airplane looking at a smartphone or a tablet. Wherever you are, you are likely sitting on a structure, like a chair, and sitting in a structure, like a building. If you are sitting in a vehicle like a car or an airplane, then you are in a machine with structural components, or parts. So what is a structure anyway?<br><br> The simplest definition of a structure is that it is something with parts put together in a particular way. From an engineer's point of view, a structure is something that is 'load bearing'. Let's take a closer look at what each of these two words mean, so we can understand what it means to be 'load bearing'.")


section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "second", main_idea:"Load bearing means to hold up against one or more forces", header:"Load bearing means to <span class='accent3'>hold up against</span> one or more <span class='accent3'>forces</span>", content: 'When you hear the word "load", you might think about carrying a load, like your backpack or a load of laundry. In the case of structures, load is another word for force. A force is a push or a pull on a structure or any other kind of object. "Bearing" might be a word you have never heard before, and it can have a few different definitions (none of them having to do with bears!). In this case, bearing means to hold up or stay strong against something. Putting these two ideas together, a structure is something that can hold up or stay strong against one or more forces, which means it will not break apart, collapse, or otherwise fall down.')

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "third", main_idea:"Structures support their own weight, which is the force gravity exerts on the structure", header:"Structures support their own <span class='accent3'>weight</span>, which is the <span class='accent3'>force gravity exerts</span> on the structure", section_image: "section_images/chair_alone_and_with_backpack.png", image_position: "imagerightlarge", content: "Structures serve different purposes, but they are all load bearing. A chair's purpose is to be sat on (and maybe it's the place you put your backpack when you come home from school...). A house provides shelter. A bridge gives you a way to cross an obstacle. Each of these structures does something different, but they all have one load or force in common: their own weight. An object’s weight is the measure of the pull of gravity on that object. Before a chair can support the force of your weight, it has to support its own weight.  The same thing is true for the house and the bridge. A structure's own weight is called its 'dead load'. Any other force the object supports (like you or your backpack) is called its 'live load'.")

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fourth", main_idea:"Large structures must also stand up to environmental forces like wind and earthquakes", header:"<span class='accent3'>Large structures</span> must also stand up to <span class='accent3'>environmental forces</span> like wind and earthquakes", section_image: "section_images/golden_gate_bridge.jpg", image_position: "imageleftlarge",content: "Some structures have to support more then the force of the weight of people and things that use it. For example, a bridge is designed to support the weight of the vehicles and people crossing it and also to resist the force of the wind blowing against it. It wouldn't be a very useful bridge if it could support a lot of users, but blew over in the first strong wind. Depending on where the bridge is located, it might also be designed to resist the movement of the earth during an earthquake. Earthquakes and wind create environmental forces that act on structures, and they are important considerations for large structures like buildings and bridges.")
 

section = FactoryGirl.create(:section, catagory_id: catagory.id, linking: "fifth", main_idea:"Engineers help to ensure structures are safe", header:"<span class='accent3'>Engineers</span> help to ensure structures are <span class='accent3'>safe</spam>", content: "Engineers help to make sure that buildings and other large structures are safe to use. Engineers also help to ensure the structural safety of other kinds of technology like vehicles and other machines. For example, an engineer would help to make sure that the frame (a structural component) of your car can support the weight of your car, your family, and your stuff. An engineer will also make sure that the frame protects you if you get in an accident.<br><br> We rely on the structural safety of not only our buildings and bridges but also the vehicles we use to travel and the other machines that we encounter in our modern world. From chairs to buildings and bridges, we are surrounded by structures. What structures do you see around you?")

question = Question.create(catagory_id: catagory.id, question_num: "1", question_content: "Which of the items in this picture are structures?", question_image: "question_images/four_structures.png", explanation: "A structure is something that is load bearing. All of the items in this picture from the chair to the bridge are all load bearing, which means they can support or stand strong against one or more forces.")

answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Only the bridge and the skyscraper are structures.")

answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "The bridge, house, skyscraper, and the chair are all structures.", correct: "true")

answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Only the skyscraper and the house are structures.")


question = Question.create(catagory_id: catagory.id, question_num: "2", question_content: "Which of these two chairs has a “live load”?", question_image: "question_images/chair_alone_and_with_backpack.png",explanation: "A structure’s own weight is called its “dead load”. Any other force the structure supports is called its “live load”. In this example, the backpack is the “live load” of the chair.")

answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "The chair without the backpack")

answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "The chair with the backpack", correct: "true")


question = Question.create(catagory_id: catagory.id, question_num: "3", question_content: "What forces does a bridge have to stand up to?", question_image: "question_images/golden_gate_bridge.jpg", explanation: "All structures have to support their own weight and the weight of their users. Large structures like bridges and buildings have to stand up to environmental forces like wind and earthquakes as well.")

answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "The bridge has to support its own weight and the weight of its users.  It also has to stand up to environmental forces like wind and earthquakes.", correct: "true")

answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png",answer_content: "The bridge has to support its own weight.")

answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png",answer_content: "The bridge has to support its own weight and the weight of its users.")

topic = FactoryGirl.create(:topic, name:"forces",  navgraphic: "navgraphics/forces.png", catagory_id: catagory.id)


section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Tension, compression, and torsion are three different ways that structures respond to the forces, pushes and pulls, exerted on them", header:"<span class='accent3'>Tension, compression, and torsion</span> are three different ways that structures <span class='accent3'>respond</span> to the <span class='accent3'>forces</span>, pushes and pulls, exerted on them", section_image: "section_images/forcesdiagram.png", image_position: "imagerightmedium", content:"Structures are load bearing, which means they can support or stay strong against all of the forces acting on them. A force is a push or a pull on one object by another object. When you think about pushing or pulling something, you might think about moving it. For example you might open a door by either pushing or pulling on it. But not all objects move when you push or pull on them. If you push on a wall, you are definitely exerting a force, but unlike the door, it isn't going to move. Structures still experience the force being exerted, but since their job is to stay put, they have other ways of reacting to forces besides moving. Tension, compression and torsion are three different ways that structures respond to the pushes and pulls exerted on them.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"When a structure is being pulled, it is under tension", header:"When a structure is being <span class='accent3'>pulled</span>, it is under <span class='accent3'>tension</span>", content:"When a structure is being pulled, it is under tension. For example when you sit down on a swing, the force of your weight pulls down on the swing, creating tension in the swing. The chains on the swing act like a rubber band and stretch. Unlike a rubber band, you can't actually see the chain stretch because the amount of the stretch is incredibly small. Imagine instead that the chain links are made of rubber bands instead of metal. With rubber bands, you would definitely be able to see the stretch. But since the purpose of a swing is to allow you to swing, not to bounce or sink straight to the ground, it has to be built with something that stretches just a tiny amount under tension. <br><br> When you get off the swing, the chains return to their normal length. If they didn't, the swing would eventually sink to the ground, and it wouldn't be able to continue being a swing. The swing chains act just like a rubber band that returns to its original size once you stop pulling on it.  This ability to stretch and then return back to its original size is a behavior known as elasticity.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"When a structure is being pushed, it is under compression", header:"When a structure is being <span class='accent3'>pushed</span>, it is under <span class='accent3'>compression</span>", section_image: "section_images/chair_alone_and_with_backpack.png", image_position: "imagerightsmall", content:"When you sit on a chair, the force of your weight pushes down on the chair, putting the chair under compression. Much as the chains on the swing got a little bit longer when your weight pulled down on them, the chair gets a little bit shorter when you push down on it. When you stand up, the chair goes back to its normal height. Just like the chains on the swing, the chair has elastic behavior.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"When a structure is being twisted, it is under torsion", header:"When a structure is being <span class='accent3'>twisted</span>, it is under <span class='accent3'>torsion</span>", content:"When a structure is being twisted, it is under torsion. If instead of swinging back and forth, you twist your swing up instead, then the swing is under torsion. You know what happens once you lift your feet off the ground: the chair spins right back to its resting position. Not only is the twisted swing a fun ride, it also demonstrates how a structure is able to return to its normal position after being twisted.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"All structures, no matter what size, or what they do, are either under compression or tension, or both forces at the same time", header:"<span class='accent3'>All structures</span>, no matter what size, or what they do, are either <span class='accent3'>under compression or tension</span>, or both forces at the same time.", content:"We used small structures like swings and chairs to demonstrate how structures respond to different pushes and pulls through tension, compression, and torsion. Larger structures like buildings and bridges react to forces these exact same ways. The cables on a suspension bridge experience tension as they help support the weight of the bridge and its users. The roof of your house experiences compression if there is a lot of snow on top of it. A skyscraper can experience torsion if it twists slightly in the wind. Structures can also experience a combination of these reactions. For example a twisted swing is experiencing both torsion from the twist and tension as you are still pulling down on the chains. Tension, compression and torsion describe three ways structures respond to the different forces acting on them.")

question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What are three ways a structure will respond to forces on it?", question_image: "section_images/forcesdiagram.png",explanation: "Structures are load bearing, which means they can support or stay strong against all of the forces acting on them. A force is a push or a pull on one object by another object. Structures experience forces being exerted on them, but since their job is to stay put, they have other ways of reacting to forces besides moving. Tension, compression and torsion are three different ways that structures respond to the pushes and pulls exerted on them. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Tension, compression, and torsion", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Apples, bananas, and cherries")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "School, teachers, and homework")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "Which of the following are true?", question_image: "section_images/forcesdiagram.png",explanation: "When a structure is being pulled, it is under tension.When a structure is being pushed, it is under compression. When a structure is being twisted, it is under torsion. All structures, no matter what size, or what they do, are either under compression tension, or both forces at the same time. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "When a structure is being pushed, it is under compression")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "When a structure is being pulled, it is under tension")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "When a structure is being twisted, it is under torsion")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of these are true", correct: "true")


topic = FactoryGirl.create(:topic, name:"arches",  navgraphic: "navgraphics/arches_coming_soon.png", catagory_id: catagory.id, available: "no")



topic = FactoryGirl.create(:topic, name:"bridges",  navgraphic: "navgraphics/bridges.png", catagory_id: catagory.id)

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Bridges are structures that allow people to cross over obstacles", header:"<span class='accent3'>Bridges</span> are structures that allow people to <span class='accent3'>cross over obstacles</span>", section_image: "section_images/different_bridges.png", image_position: "imagerightlarge", image_caption: "Bridges allow us to cross over many different obstacles. Clockwise from top left: Pedestrian Bridge, Spain, &#169; JCVStock. Millau Viaduct, France, &#169; PHB.cz (Richard Semik)/Shutterstock.com. Peace Bridge, Canada, &#169; Jeff Whyte/Shutterstock.com. Tower Bridge, England, &#169; pcruciatti.", content:"Bridges are structures that allow people to cross over obstacles. An obstacle might be something found in nature, like a river or another large body of water like a bay.  Other obstacles are man-made, like a freeway that you need to safely cross over to get to school. Bridges solve transportation problems by shortening the distance people have to travel to get from one place to another. <br><br>We live in a world full of bridges. There are over 600,000 bridges in the United States alone. Bridges are some of the most beautiful and well know structures in the world. Like all structures, bridges are load bearing. Unlike many structures, the structural components of a bridge are usually on display, making it easier to understand how they support their loads.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"When helping to design a bridge, engineers must consider the obstacle to be crossed and the forces that will act on the bridge", header:"When helping to design a bridge, engineers must consider the <span class='accent3'>obstacle</span> to be crossed and the <span class='accent3'>forces</span> that will act on the bridge.", section_image: "section_images/drawing_a_bridge.jpg", image_position: "imageleftmedium", content:"There are lots of facts engineers need to know before they can help design a bridge, including environmental factors like what obstacle needs to be crossed and how far down the ground is in case additional supports are needed. Engineers will also need to know if the area experiences any natural events like earthquakes. All of these environmental factors will help the engineer develop a set of design constraints, or requirements, that the bridge must meet to be safe.  These requirements are called design constraints, because they will represent limitations on the design, or plan, of the bridge. <br><br> Another key design constraint is ensuring the bridge is strong enough to stand up to the forces (pushes and pulls) that will be acting it. If you’ve watched the structures video, you know that if a structure is load bearing, it is designed to stand up to forces acting on it. In addition to planning for all of the environmental factors above, engineers must also plan for the bridge to stand up to, or support, its own weight – its dead load – along with the weight of the users of the bridge – its live load. The environment also holds potential forces engineers must plan for, such as the possibility of high winds blowing against the bridge.<br><br>Along with the different forces and environmental factors, an important design constraint with every engineering project is the budget, or amount of money, available to complete the project. Materials, equipment, and labor – the work done by people – are expensive and will place additional restrictions on the design. Once an engineer understands all of the design constraints on building a particular bridge, she can figure out what kind of bridge design will work best.")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"third", main_idea:"Different types of bridges, including the beam bridge, the suspension bridge, and the arch bridge, use different structural elements to support their loads", header:"Different types of bridges, including the beam bridge, the suspension bridge, and the arch bridge, use different <span class='accent3'>structural elements</span> to <span class='accent3'>support their loads</span>", section_image: "section_images/different_types_of_bridges.png", image_position: "imagerightmedium", content:"A bridge has two components: the deck, which is the horizontal part of the bridge on which users cross, and the supports for that deck. The deck can be made up of one or more spans. A span is the distance between two supports. The key distinction between the different types of bridges is how the deck of the bridge – and therefore all of the users of the bridge – is supported. Let’s look more closely at three different types of bridges, the beam bridge, the suspension bridge and the arch bridge to see how they support their loads.<br><br>A beam is a horizontal structural element supported on both ends. With bridges, this beam is called a span. A beam bridge can have a single span or it can be continuous and have many spans and therefore many supports. As with all beams, each span of a beam bridge is under both tension and compression. Compression on the top of the deck from the weight of the deck and the people and vehicles using the bridge, and tension on the bottom of the deck, as the deck is pushed down from the load it is supporting. <br><br> A suspension bridge supports its deck with a pair of cables. These two cables run along the top of two towers and are then anchored to the earth at each end. Suspender cables attach the deck to these  top two cables. All of the cables are under tension (being pulled) from the weight of holding the deck up. The towers are under compression (being pushed) from the weight of cables (and the deck they are supporting) pushing down on them.<br><br>An arch bridge works by diverting the force of its load to abutments on either side of the arch. Because of its semicircular shape, every part of an arch is under compression. If you were to stand on top of arch, it would not bend under your weight like a beam would. An arch bridge can be designed as a single arch with a deck on top, or as a series of arches that are connected with a deck on top. Arch bridges can also be built with the span of the deck passing through the arch, called a through arch bridge. A through arch bridge uses cables or beams to support the deck, which work like the suspender cables in a suspension bridge.  The oldest bridges in the world that are still standing (some still in use) are arch bridges. Modern arch bridge designs look very different than ancient arch bridges, but they still rely on the strength of the arch to support their users. ")

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"One main distinction between the different bridge designs is the maximum length a single span of the bridge can be", header:"One main <span class='accent3'>distinction</span> between the different bridge designs is the <span class='accent3'>maximum length</span> a <span class='accent3'>single span</span> of the bridge can be", section_image: "section_images/ak_vs_lp_bridge.png", image_position: "imageleftlarge", image_caption: "Top: Lake Pontchartrain Causeway, &#169; pisaphotograpy/Shutterstock.com, Bottom: Akashi Kaikyo Bridge, &#169; Sean Pavone.",content: "Just as skyscrapers challenge engineers to build vertically, or up, bridges challenge engineers to build horizontally, or across. Bridges are noted both for their overall length, and for the length of their longest span. Beam bridges are the longest bridges in the world, but a single span on a beam bridge is shorter than a single span on many of the other bridge designs. For example, the Lake Pontchartrain Causeway, part of the highway system in Louisiana, is 23.8 miles long, but the individual spans of its deck are only 56 feet. <br><br>On the other end of the spectrum, the longest suspension bridge in the world is the Akashi Kaikyo Bridge in Japan. Like the Lake Pontchartrain Causeway, the Akashi Kaikyo Bridge is part of a highway system. This bridge is only 2.4 miles long, but its longest span is 6,532 feet long. The Akashi Kaikyo Bridge is about a tenth the length of the Lake Pontchartrain Causeway, but its longest span is 116 times longer than any span on the Causeway. <br><br>These distances and lengths point out not only the differences in the bridge designs, but also the different design constraints that each bridge must meet. Bridges are a critical part of our transporation infrastructure, or system. They are each are designed to meet the unique requirements of the many obstacles that people cross every day on their way to work, school, and play.")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What are some types of bridges?", question_image: "section_images/different_bridges.png",explanation: "Different types of bridges include the beam bridge, the suspension bridge, and the arch bridge. Each type of bridge used different structural elements to support their loads. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "The beam bridge, the suspension bridge, and the arch bridge", correct: "true")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "The plank bridge, the log bridge, and the card game bridge")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "The book bridge, the Lego bridge, and the jello bridge")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "Which of the following are true?", question_image: "section_images/different_bridges.png",explanation: "A bridge has two components: the deck and the supports for the deck. The deck is the horizontal part of the bridge that people or vehicles move across. The deck can be made up of one or more spans. A span is the distance between two supports. The key distinction between the different types of bridges is how the deck of the bridge – and therefore all of the weight of vehicles or people on the bridge – is supported.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "A bridge has two components: the deck and the supports for the deck .")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A span is the distance between two supports.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "The deck can be made up of one or more spans.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of these are true", correct: "true")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "What kind of bridges are these?", question_image: "section_images/different_types_of_bridges_subset_small.png",explanation: "A beam is a horizontal structural element supported on both ends. With bridges, this beam is called a span. A beam bridge can have a single span or it can be continuous and have many spans and therefore many supports. A suspension bridge supports its deck with a pair of cables. These two cables run along the top of two towers and are then anchored to the earth at each end. Suspender cables attach the deck to these top two cables. An arch bridge works by diverting the force of its load to abutments on either side of the arch. An arch bridge can be designed as a single arch with a deck on top, or as a series of arches that are connected with a deck on top. Arch bridges can also be built with the span of the deck passing through the arch, called a through arch bridge. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "1. Beam Bridge, 2. Arch Bridge, 3. Suspension Bridge")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "1. Arch Bridge, 2. Suspension Bridge, 3. Beam Bridge")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "1. Suspension Bridge, 2. Beam Bridge, 3. Arch Bridge ", correct: "true")



#topic = FactoryGirl.create(:topic, name:"skyscrapers",  navgraphic: "navgraphics/skyscrapers_coming_soon.png", catagory_id: catagory.id, available: "no")
topic = FactoryGirl.create(:topic, name:"skyscrapers",  navgraphic: "navgraphics/skyscrapers.png", catagory_id: catagory.id)

section = FactoryGirl.create(:section, topic_id: topic.id, linking:"first", main_idea:"Skyscrapers are really tall buildings that seem to scrape the sky", header:"Skyscrapers are <span class='accent3'>really tall</span> buildings that seem to <span class='accent3'>scrape the sky</span>", section_image: "section_images/TP101_59857945.jpg", image_position: "imagerightmedium", image_caption: "Dramatic cityscape of Taipei and trees in park, Taiwan, Asia. &#169; elwynn/Shutterstock.com.",content:"Skyscrapers are tall buildings with many stories (floors). There is not one specific definition how tall a skyscraper is. Some people might call a 20-story building a skyscraper. Others think a skyscraper must be at least 40-50 floors.<br><br>We call them “skyscrapers,” because they are so tall they seem to scrape the sky. The tallest buildings in the world are over 2000 feet tall. For example, the Burj Khalifa in Dubai is 2717 feet tall, with 163 floors. That’s more than half a mile tall! <br><br>Before the Burj Khalifa was built, the Taipei 101 building in Taipei, Taiwan was the tallest skyscraper. The Taipei 101 is 101 floors tall above ground, with an additional five floors below ground, and is 1671 feet tall. As shown in the image, it rises well above the rest of the Taipei skyline.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"second", main_idea:"Inspiration for skyscrapers came from a disaster", header:"<span class='accent3'>Inspiration</span> for skyscrapers came from a <span class='accent3'>disaster</span>", section_image: "section_images/olearyscow.png", image_position: "imageleftsmall", content:"Up until the early 1800s, the tallest buildings anywhere were only five or six stories tall. Some inventions needed to be made before buildings could be made taller. The inspiration to create tall buildings came from an unexpected place. In 1871, the “Great Fire of Chicago” burned thousands of buildings in Chicago, Illinois. Believe it or not, this fire was blamed on a cow! Many people thought that a cow owned by the O’Leary family on DeKoven Street had kicked over a lantern and started the fire that destroyed much of the city. But no one has ever found out for sure what caused the Great Fire.<br><br>After the fire, Chicago needed to be rebuilt. There were many buildings destroyed, and those buildings had held many businesses and people. So, to rebuild Chicago, they decided to build tall buildings that could fit many people and businesses.<br><br>Some inventions were required to enable the building of skyscrapers. First, people had to figure out efficient ways to make steel - a major material for skyscrapers. Another major invention was the elevator. People probably would not have wanted to walk up and down twenty or more floors every day. A man named Elisha Otis invented the modern elevator, with a safety break, in the 1850s. Third, in order to power the elevator system - and light the building - electricity needed to be available. Electricity was made available in small areas in the early 1880s. ")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fourth", main_idea:"Skyscrapers use a steel frame to hold up the building", header:"Skyscrapers use a <span class='accent3'>steel frame</span> to <span class='accent3'>hold up</span> the building",section_image: "section_images/steelframecage.png", image_position: "imagerightsmall", image_caption: "Left: Colorful parrot in captivity. He is looking at camera &#169;Gracanin Dusan / Shutterstock.com. Right: Structural steel framework &#169; Joe Gough / Shutterstock.com.", content:"Before skyscrapers were invented, tall buildings were built out of stone. The stone walls were what held up the building. Any openings in the stone walls made them weaker, so windows are few and small. However, skyscrapers use a steel frame that holds up the building. The frame uses steel beams (horizontal bars) and columns (vertical bars) connected together. Because the frame, not the walls, holds the building up, windows are not a problem at all. <br><br>Believe it or not, the person who came up with the idea for a steel frame got the inspiration for it from a wire bird cage. He watched his wife place a book on top of the bird cage, and saw that the cage could hold a heavy book. He realized that a similar frame might be possible for a building.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"fifth", main_idea:"Designing skyscrapers starts with needs and use", header:"Designing skyscrapers starts with <span class='accent3'>needs</span> and <span class='accent3'>use</span>", section_image: "section_images/skyscraperchecklist.png", image_position: "imagerightmedium", content:"Like any other engineering design problem, designing skyscrapers starts with needs and use. Architects and engineers work together to design the skyscraper. The architects may focus on the desired look, and feel, and the spaces in the building. They want it to look nice, and get plenty of sunlight, and be an enjoyable place for people using the building. <br><br>The engineers have to think about materials and structural soundness, so that the beautiful building doesn’t fall down. There are actually multiple types of engineers that get involved in designing a skyscraper. Skyscrapers are complicated!  Engineers need to consider the site where the skyscraper will be built. For example:
<br><br>
<i>Soil:</i> What is the soil made of? How deep is the bedrock?<br>
<i>Weather:</i> Does the region have strong typhoons or tornados?<br>
<i>Geology:</i> Is the region in a strong earthquake zone?")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"sixth", main_idea:"Skyscrapers are designed for forces like their own weight and wind", header:"Skyscrapers are designed for <span class='accent3'>forces</span> like their <span class='accent3'>own weight</span> and <span class='accent3'>wind</span>", section_image: "section_images/John_Hancock_Center_2.jpg", image_position: "imageleftsmall", image_caption: "Picture of John Hancock Center in Chicago Illinois. Photo by Joe Ravi. Image used under Creative Commons Share-Alike CC-BY-SA 3.0", content:"Remember “dead loads” and “live loads” from the main Structures section? The dead load is the force from the structure’s own weight. The live load is the set of temporary forces on the structure at a point of time – such as the weight of a person sitting in a chair.<br><br>For a skyscraper, the dead load (its own weight) is much higher than the live load (such as the people inside). So, a lot of the design results from having to hold up the great weight of the building itself.<br><br>Wind is also a major force on a skyscraper. The wind gets stronger the higher you go in the building. Did you know that skyscrapers bend in the wind? If a skyscraper didn’t bend at all, a big wind could break it. However, if the building bends too much, a big wind could blow it over.  Also, people at the top of the building might not like to experience too much movement from the wind. So, the building designers want to allow the building to move a little – but not too much.<br><br>There are different ways to keep a skyscraper from moving too much. One way is to use steel cross-bracing (called “X-bracing”) inside or outside the building. The John Hancock Center in Chicago (shown at left) uses X-bracing outside the building. Another way is to use something called “supercolumns.” Supercolumns are wider columns of metal-reinforced concrete that are placed in the corners or on the sides of the building. Another design approach is to use something called a “damper” to lessen the movement in a building. A damper is a heavy block at the top of a building that is connected to springs. When the wind blows, the building moves a bit, but the damper does not – so the springs stretch in one direction and compress in the other. The springs help pull the building back into position.")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"seventh", main_idea:"The foundation of a skyscraper depends on the ground where it will be built", header:"The <span class='accent3'>foundation</span> of a skyscraper depends on the <span class='accent3'>ground</span> where it will be built", content:"There is more to a skyscraper than what you see. Skyscrapers are built on really strong foundations. Those foundations are built down into the ground. Building a skyscraper requires a lot of digging. The foundation design depends on what the ground is like where the skyscraper will be built. If the foundation is not strong enough, the building could sink or collapse!<br><br>The important thing to know for the foundation is how deep the bedrock is. The bedrock is the solid rock layer beneath the ground’s soil. If the bedrock is near the surface, then the foundation does not need to be as deep. In that case, the soil on top will be removed, the bedrock evened out, and then holes made for the building’s support columns. These holes are called “footings.” The building’s support columns are made from steel or reinforced concrete and are placed in the footings.<br><br>If the bedrock is deep, then the design is a little more complicated. The design may require some things called “piles” – which are like long columns – to be driven down deep into the earth. The piles may be steel or reinforced concrete. The design may also call for a thick slab of concrete to be built down in the earth to make a strong mat or “raft” for the building to sit on. For example, the Shanghai Tower design required both deep piles and a thick concrete mat. They used 980 piles driven down 282 feet into the ground, and then poured in more than 2 million cubic feet of reinforced concrete. The concrete mat for the Shanghai Tower is 20 feet thick!")
section = FactoryGirl.create(:section, topic_id: topic.id, linking:"eighth", main_idea:"Skyscrapers require a lot of design but they are often iconic buildings", header:"Skyscrapers require a lot of <span class='accent3'>design</span> but they are often <span class='accent3'>iconic</span> buildings", content:"Skyscrapers are more than “just a tall building.” When people think of certain cities, often what comes to mind are the skyscrapers the cities the cities are known for. <br><br>When the decision is made to build a skyscraper, many types of people get involved. Architects figure out how best to have the building stand out, yet fit well into its surroundings, while also meeting the needs in a beautiful way. Architects and engineers have to work together to ensure the beautifully designed building is structurally sound as well. Different types of engineers are required, too. Engineers who understand the soil and rock under the building work with structural engineers to design the foundation. Electrical engineers and mechanical engineers design some of the internal parts of the building, like the electrical systems, heating and cooling, plumbing, and more. Building skyscrapers is a complicated team effort involving many people. But look at some of the beautiful buildings that have resulted!")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "1", question_content: "What inventions were needed in order to make skyscrapers possible?", question_image: "section_images/olearyscow.png",explanation: "Some inventions were required to enable the building of skyscrapers. First, people had to figure out efficient ways to make steel - a major material for skyscrapers. Another major invention was the elevator. People probably would not have wanted to walk up and down twenty or more floors every day. A man named Elisha Otis invented the modern elevator, with a safety break, in the 1850s. Third, in order to power the elevator system and light the building, electricity needed to be available. Electricity was made available in small areas in the early 1880s. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Electricity needed to be available to the building")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "The elevator needed to be invented")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "People had to figure out efficient ways to make steel")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of these inventions were needed", correct: "true")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "2", question_content: "What can be used to stabilize a skyscraper so it does not move too much from the wind or other forces?", question_image: "section_images/John_Hancock_Center_2.jpg", explanation: "There are different ways to keep a skyscraper from moving too much. One way is to use steel cross-bracing, or X-bracing, inside or outside the building. Supercolumns, wider columns of metal-reinforced concrete that are placed in the corners or on the sides of the building, can also be used. And, another design approach is to use a damper to lessen the movement in a building. A damper is a heavy block at the top of a building connected to springs. ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "Use steel cross-bracing, called “X-bracing,” inside or outside the building.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "Use supercolumns: wider columns of metal-reinforced concrete that are placed in the corners or on the sides of the building.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "Use a damper to lessen the movement in a building: a heavy block at the top of a building that is connected to springs")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_d.png", answer_content: "All of these are possible design approaches to minimize movement ", correct: "true")
question = Question.create(catagory_id: catagory.id, topic_id: topic.id, question_num: "3", question_content: "What is a skyscraper exactly?", question_image: "section_images/TP101_59857945.jpg",explanation: "Skyscrapers are tall buildings with many stories (floors). There is not an agreed-upon definition of how tall a skyscraper is. Some people might call a 20-story building a skyscraper. Others think a skyscraper must be at least 40-50 floors.
We call them skyscrapers, because they are so tall they seem to scrape the sky. The tallest buildings in the world are over 2000 feet tall. For example, the Burj Khalifa in Dubai is 2717 feet tall, with 163 floors. That’s more than half a mile tall! ")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_a.png", answer_content: "A skyscraper is at least 20-stories tall.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_b.png", answer_content: "A skyscraper is be at least 40-50 stories tall.")
answer = Answer.create(question_id: question.id, image: "answer_images/answer_c.png", answer_content: "There is not a clear definition exactly how tall a building must be to be called a skyscraper.  ", correct: "true")


topic = FactoryGirl.create(:topic, name:"infrastructure",  navgraphic: "navgraphics/infrastructure_coming_soon.png", catagory_id: catagory.id, available: "no")


#catagory = FactoryGirl.create(:catagory, name:"structures", navgraphic: "navgraphics/structures.png", headergraphic: "structures", color: "structures", video: "StructuresMain.m4v", keypoints: "The chair you are sitting on...is a structure<p> The building you're sitting in...is a structure<p>A structure is something that is 'load bearing'" )
#topic = FactoryGirl.create(:topic, name:"push and pull",  navgraphic: "navgraphics/push_and_pull.png", catagory_id: catagory.id, video: "EPDesign.m4v", keypoints: "Structures react to different forces on them<p>Structures are designed to stand up to those forces without breaking<p>Two important types of forces are pushes and pulls")
#topic = FactoryGirl.create(:topic, name:"beams",  navgraphic: "navgraphics/beams.png", catagory_id: catagory.id, video: "EPDesign.m4v", keypoints: "beams are pretty, beams are great, there'll be key points, but not until late-r")
#topic = FactoryGirl.create(:topic, name:"bridges", navgraphic: "navgraphics/bridges.png", catagory_id: catagory.id, video: "EPDesign.m4v", keypoints: "bridges have key points too")
#topic = FactoryGirl.create(:topic, name:"skyscrapers",  navgraphic: "navgraphics/skyscrapers.png", catagory_id: catagory.id)
